{
  "nav.dashboard": "Dashboard",
  "nav.workflowBuilder": "Workflow Builder",
  "nav.subscription": "Subscription",
  "nav.referrals": "Referrals",
  "nav.settings": "Settings",
  "nav.accountGroups": "Account Groups",
  "nav.logOut": "Log Out",
  "dashboard.title": "Dashboard",
  "dashboard.subtitle": "Overview of your automation activity",
  "dashboard.agentStatus": "Agent Status",
  "dashboard.online": "Online",
  "dashboard.efficiency": "Efficiency",
  "dashboard.totalRuns": "Total Runs",
  "dashboard.totalAccounts": "Total Accounts",
  "dashboard.successful": "Successful",
  "dashboard.failed": "Failed",
  "dashboard.automationActivity": "Automation Activity",
  "dashboard.runsAndEfficiency": "Runs and efficiency over time",
  "dashboard.last7days": "Last 7 days",
  "dashboard.last30days": "Last 30 days",
  "dashboard.recentActivity": "Recent Activity",
  "dashboard.latestEvents": "Latest events across all accounts",
  "dashboard.batchExecutions": "Batch Executions",
  "dashboard.groupsSubtitle": "Groups across all workflows",
  "dashboard.all": "All",
  "dashboard.success": "Success",
  "dashboard.partial": "Partial",
  "dashboard.noGroupsMatch": "No groups match this filter.",
  "dashboard.accounts": "accounts",
  "dashboard.ok": "ok",
  "dashboard.err": "err",
  "dashboard.wait": "wait",
  "dashboard.retryGroup": "Retry Group",
  "dashboard.retryAccount": "Retry",
  "dashboard.failedAccounts": "Failed Accounts",
  "dashboard.pending": "Pending",
  "dashboard.allCompleted": "All {count} accounts completed successfully.",
  "dashboard.noAccountsInGroup": "No accounts in this group yet.",
  "dashboard.recentExecutions": "Recent Executions",
  "dashboard.step": "Step",
  "workflow.title": "Workflow Builder",
  "workflow.save": "Save",
  "workflow.simulate": "Simulate",
  "workflow.stopSim": "Stop Sim",
  "workflow.export": "Export",
  "workflow.import": "Import",
  "workflow.clear": "Clear",
  "workflow.undo": "Undo",
  "workflow.redo": "Redo",
  "workflow.zoomIn": "Zoom In",
  "workflow.zoomOut": "Zoom Out",
  "workflow.nodeLibrary": "Node Library",
  "workflow.dragToAdd": "Drag to add",
  "workflow.nodeConfig": "Node Config",
  "workflow.selectNode": "Select a node to configure",
  "workflow.delete": "Delete",
  "workflow.type": "Type",
  "workflow.label": "Label",
  "workflow.interval": "Interval",
  "workflow.duration": "Duration (days)",
  "workflow.splitPercentage": "Split %",
  "workflow.splitCount": "Split Count",
  "workflow.executionMode": "Execution Mode",
  "workflow.sequential": "Sequential",
  "workflow.parallel": "Parallel",
  "workflow.randomize": "Randomize order",
  "workflow.targetGroup": "Target Group",
  "workflow.allAccounts": "All Accounts",
  "workflow.selectGroup": "Select group...",
  "workflow.noNodes": "No nodes yet",
  "workflow.dropHere": "Drag nodes from the library or drop them here",
  "subscription.title": "Subscription",
  "subscription.subtitle": "Choose the billing period that works best for you",
  "subscription.monthly": "Monthly",
  "subscription.3months": "3 Months",
  "subscription.yearly": "Yearly",
  "subscription.billedMonthly": "Billed monthly",
  "subscription.billedEvery3Months": "Billed every 3 months",
  "subscription.billedAnnually": "Billed annually",
  "subscription.saveVsMonthly": "Save {percent}% vs monthly",
  "subscription.perMonth": "mo",
  "subscription.currentPlan": "Current Plan",
  "subscription.status": "Status",
  "subscription.active": "Active",
  "subscription.freeTrial": "Free Trial",
  "subscription.freeMode": "You are on Free Mode",
  "subscription.freeModeSub": "Limited features available. Unlock the full power of automation.",
  "subscription.unlockFull": "Unlock Full Automation",
  "subscription.trialEnds": "Trial ends in",
  "subscription.days": "days",
  "subscription.upgradePlan": "Upgrade Plan",
  "subscription.currentPlanBadge": "Current Plan",
  "subscription.mostPopular": "Most Popular",
  "subscription.allPlansUnlimited": "All plans include unlimited accounts",
  "subscription.feat.unlimitedAccounts": "Unlimited accounts",
  "subscription.feat.highSpeed": "High-speed execution tier",
  "subscription.feat.priorityQueue": "Priority queue",
  "subscription.feat.advancedErrors": "Advanced error handling",
  "subscription.feat.workflowAnalytics": "Workflow analytics",
  "subscription.feat.aiAssistant": "AI workflow assistant",
  "subscription.feat.premiumSupport": "Premium support",
  "subscription.why.fasterExec": "Faster Execution",
  "subscription.why.fasterExecDesc": "Priority queue ensures lightning-fast automation",
  "subscription.why.smarterRecovery": "Smarter Recovery",
  "subscription.why.smarterRecoveryDesc": "AI-powered error handling recovers from failures automatically",
  "subscription.why.aiAssist": "AI Assistance",
  "subscription.why.aiAssistDesc": "Intelligent workflow suggestions and optimization",
  "subscription.why.priorityInfra": "Priority Infrastructure",
  "subscription.why.priorityInfraDesc": "Dedicated resources for maximum reliability",
  "subscription.why.premiumReliability": "Premium Reliability",
  "subscription.why.premiumReliabilityDesc": "Enterprise-grade stability for critical automation",
  "subscription.whyUpgrade": "Why Upgrade?",
  "subscription.cryptoPayments": "Crypto payments supported",
  "subscription.paymentMethods": "Payment Methods",
  "referrals.title": "Referrals",
  "referrals.subtitle": "Invite friends. Earn credits.",
  "referrals.creditsTitle": "What are Credits?",
  "referrals.creditsDesc": "Credits are bonus balance earned from referrals.",
  "referrals.creditsUseIntro": "You can use credits to:",
  "referrals.creditUse1": "Pay for subscriptions",
  "referrals.creditUse2": "Upgrade plans",
  "referrals.creditUse3": "Unlock premium features",
  "referrals.creditsAutoApply": "Credits are automatically applied at checkout.",
  "referrals.heroText": "Get rewarded every time your referrals subscribe.",
  "referrals.earnPercent": "You earn 20% of every payment in platform credits",
  "referrals.yourLink": "Your Referral Link",
  "referrals.shareLink": "Share this link to earn rewards",
  "referrals.copied": "Copied",
  "referrals.copy": "Copy",
  "referrals.shareTelegram": "Telegram",
  "referrals.shareX": "X",
  "referrals.shareDiscord": "Discord",
  "referrals.activeReferrals": "Active Referrals",
  "referrals.totalEarned": "Total Earned Credits",
  "referrals.currentLevel": "Current Level",
  "referrals.lifetimeCommission": "Lifetime Commission %",
  "referrals.yourLevel": "Your referral level",
  "referrals.level1": "Starter",
  "referrals.level1Req": "1-4 active referrals",
  "referrals.level1Perk": "20% credits on payments",
  "referrals.level2": "Growth",
  "referrals.level2Req": "5-9 active referrals",
  "referrals.level2Perk1": "30% credits on payments",
  "referrals.level2Perk2": "20% subscription discount",
  "referrals.level3": "Partner",
  "referrals.level3Req": "10+ active referrals",
  "referrals.level3Perk1": "10% lifetime commission",
  "referrals.level3Perk2": "Partner status badge",
  "referrals.level4": "Ambassador",
  "referrals.level4Req": "50+ active referrals",
  "referrals.level4Perk1": "Ambassador badge",
  "referrals.level4Perk2": "Exclusive rewards",
  "referrals.unlocked": "Unlocked",
  "referrals.locked": "Locked",
  "referrals.current": "Current",
  "referrals.activity": "Referral activity",
  "referrals.colUserId": "User ID",
  "referrals.colPlan": "Plan purchased",
  "referrals.colAmount": "Payment amount",
  "referrals.colReward": "Your reward",
  "referrals.colStatus": "Status",
  "referrals.statusPending": "Pending",
  "referrals.statusActive": "Active",
  "referrals.statusExpired": "Expired",
  "referrals.creditsWallet": "Credits wallet",
  "referrals.availableCredits": "Available credits",
  "referrals.lifetimeEarned": "Lifetime earned",
  "referrals.creditsUsed": "Credits used",
  "referrals.applyCredits": "Apply credits to subscription",
  "referrals.creditsTooltip": "Credits automatically reduce your next payment",
  "referrals.achievements": "Achievements",
  "referrals.achFirstRef": "First Referral",
  "referrals.achFiveRef": "5 Referrals",
  "referrals.achTopPartner": "Top Partner",
  "referrals.emptyTitle": "Start inviting friends to unlock rewards",
  "referrals.emptyCta": "Copy referral link",
  "settings.title": "Settings",
  "settings.subtitle": "Manage your account preferences",
  "settings.profile": "Profile",
  "settings.displayName": "Display Name",
  "settings.email": "Email",
  "settings.saveChanges": "Save Changes",
  "settings.notifications": "Notifications",
  "settings.emailNotifications": "Email notifications",
  "settings.emailNotificationsDesc": "Receive updates about your workflows",
  "settings.workflowAlerts": "Workflow alerts",
  "settings.workflowAlertsDesc": "Get notified when workflows complete or fail",
  "settings.marketingEmails": "Marketing emails",
  "settings.marketingEmailsDesc": "Product updates and announcements",
  "settings.security": "Security",
  "settings.changePassword": "Change Password",
  "settings.lastPasswordChange": "Last password change: Never",
  "settings.language": "Language",
  "settings.languageDesc": "Select your preferred language",
  "groups.title": "Account Groups",
  "groups.subtitle": "Organize accounts into logical groups",
  "groups.createGroup": "Create Group",
  "groups.newGroup": "New Group",
  "groups.groupName": "Group Name",
  "groups.enterGroupName": "Enter group name",
  "groups.create": "Create",
  "groups.cancel": "Cancel",
  "groups.rename": "Rename",
  "groups.delete": "Delete",
  "groups.deleteConfirm": "Are you sure you want to delete this group? Accounts will be unassigned.",
  "groups.noGroups": "No groups yet. Create one to organize your accounts.",
  "groups.accountCount": "{count} accounts",
  "groups.lastActivity": "Last activity",
  "groups.activeWorkflows": "Active workflows",
  "groups.successRate": "Success rate",
  "groups.manageAccounts": "Manage Accounts",
  "groups.availableAccounts": "Available Accounts",
  "groups.groupAccounts": "Group Accounts",
  "groups.dragToAssign": "Drag accounts or use buttons to assign",
  "groups.noAvailable": "All accounts are assigned to groups.",
  "groups.noAccountsInGroup": "No accounts in this group yet.",
  "groups.addToGroup": "Add",
  "groups.removeFromGroup": "Remove",
  "groups.overview": "Overview",
  "groups.backToGroups": "Back to Groups",
  "groups.totalInGroup": "Total in Group",
  "groups.successfulRuns": "Successful Runs",
  "groups.failedRuns": "Failed Runs",
  "groups.recentExecutions": "Recent Executions",
  "groups.noExecutions": "No executions yet for this group.",
  "groups.status": "Status",
  "groups.workflow": "Workflow",
  "groups.time": "Time",
  "groups.moveToGroup": "Move to group",
  "groups.notFound": "Group not found.",
  "nodeType.wallet": "Wallet Action",
  "nodeType.delay": "Delay",
  "nodeType.split": "Split Group",
  "nodeType.condition": "Conditional",
  "nodeType.swap": "Swap Action",
  "nodeType.loop": "Loop",
  "nodeType.bridge": "Bridge",
  "nodeType.notify": "Notification",
  "nodeType.repeat": "Repeat Loop",
  "nodeType.airdrop": "Airdrop Claim",
  "nodeType.script": "Custom Script",
  "nodeType.website": "Website Action",
  "nodeType.apiCall": "API Call",
  "nodeType.conditionBranch": "Conditional Branch",
  "nodeType.randomDelay": "Random Delay",
  "nodeType.multiSplit": "Multi Account Split",
  "nodeType.smartRetry": "Smart Retry",
  "nodeType.logging": "Logging Node",
  "workflow.myWorkflows": "My Workflows",
  "workflow.newWorkflow": "New Workflow",
  "workflow.templates": "Templates",
  "workflow.lastEdited": "Last edited",
  "workflow.runCount": "Runs",
  "workflow.noWorkflows": "No workflows yet",
  "workflow.createFirst": "Create your first workflow to get started",
  "workflow.templateTitle": "Choose a Template",
  "workflow.templateTestnet": "Testnet Template",
  "workflow.templateTestnetDesc": "Pre-built workflow for testnet interactions with wallet, delay, repeat, and airdrop nodes",
  "workflow.templateSocial": "Social Activities",
  "workflow.templateSocialDesc": "Social interaction workflow with website actions, social nodes, delay, and repeat",
  "workflow.templateBlank": "Blank Workflow",
  "workflow.templateBlankDesc": "Start with an empty canvas and build from scratch",
  "workflow.savedSuccess": "Workflow saved",
  "workflow.autoSaved": "Auto-saved",
  "workflow.versionHistory": "Version History",
  "workflow.restoreVersion": "Restore",
  "workflow.nodeLabel": "Node Label",
  "workflow.enabled": "Enabled",
  "workflow.linkUrl": "Link URL",
  "workflow.errorHandling": "Error Handling",
  "workflow.retryAttempts": "Retry Attempts",
  "workflow.errorSkip": "Skip on error",
  "workflow.errorRetry": "Retry on error",
  "workflow.errorStop": "Stop on error",
  "workflow.advancedMode": "Advanced Mode",
  "workflow.basicSettings": "Basic Settings",
  "workflow.timingIntervals": "Timing & Intervals",
  "workflow.executionLogic": "Execution Logic",
  "workflow.accountTargeting": "Account Targeting",
  "workflow.advancedSettings": "Advanced Settings",
  "workflow.websiteTargetUrl": "Website / Target URL",
  "workflow.accountGroup": "Account Group",
  "workflow.executionPriority": "Execution Priority",
  "workflow.delayBeforeStart": "Delay Before Start",
  "workflow.delayRandomization": "Delay Randomization Range (sec)",
  "workflow.timeoutBehavior": "Timeout Behavior",
  "workflow.conditionalExecution": "Conditional Execution",
  "workflow.successConfirmation": "Success Confirmation Rule",
  "workflow.concurrency": "Concurrency",
  "workflow.executionOrder": "Execution Order",
  "workflow.errorStrategy": "Error Strategy",
  "workflow.retryStrategy": "Retry Strategy",
  "workflow.failSafeStop": "Fail-Safe Stop",
  "workflow.loggingLevel": "Logging Level",
  "workflow.maxAttemptsLimit": "Max Attempts Limit",
  "workflow.riskLevel": "Risk Level",
  "workflow.backToLibrary": "Back to Library",
  "status.success": "Success",
  "status.partial": "Partial",
  "status.failed": "Failed",
  "status.pending": "Pending",
  "status.running": "Running",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.close": "Close",
  "common.confirm": "Confirm",
  "common.search": "Search",
  "common.noResults": "No results found.",
  "guide.title": "Card Settings Guide",
  "guide.section.overview": "Basic Controls",
  "guide.section.advanced": "Advanced Settings",
  "guide.section.timing": "Timing & Delays",
  "guide.section.risk": "Risk Indicators",
  "guide.section.simulation": "Simulation Mode",
  "guide.overview.accountGroup": "Account Group",
  "guide.overview.accountGroupDesc": "Select which group of accounts will execute this action. Groups can be managed in the Account Groups page.",
  "guide.overview.urlTarget": "URL / Target",
  "guide.overview.urlTargetDesc": "The destination URL or contract address that this action will interact with.",
  "guide.overview.delay": "Delay",
  "guide.overview.delayDesc": "Time to wait before executing this action. Helps avoid detection and rate limits.",
  "guide.overview.onSuccess": "On Success",
  "guide.overview.onSuccessDesc": "What happens after this action completes successfully — continue to next node, repeat, or stop.",
  "guide.advanced.concurrency": "Concurrency",
  "guide.advanced.concurrencyDesc": "How many accounts run this action at the same time. Higher values are faster but riskier.",
  "guide.advanced.interval": "Interval",
  "guide.advanced.intervalDesc": "Time between each batch of accounts. Controls the pace of execution.",
  "guide.advanced.jitter": "Jitter",
  "guide.advanced.jitterDesc": "Adds random variation to timing, making actions look more human and natural.",
  "guide.advanced.retryLogic": "Retry Logic",
  "guide.advanced.retryLogicDesc": "How failed actions are retried — number of attempts, delay between retries, and backoff strategy.",
  "guide.advanced.conditions": "Conditions",
  "guide.advanced.conditionsDesc": "Pre-checks before executing: minimum balance, gas price limits, and other requirements.",
  "guide.advanced.errorHandling": "Error Handling",
  "guide.advanced.errorHandlingDesc": "What happens when an action fails — skip the account, retry, or stop the entire workflow.",
  "guide.timing.delays": "Delay Types",
  "guide.timing.delaysDesc": "Fixed delays wait a set time. Random delays add variation within a range for more natural behavior.",
  "guide.timing.batching": "Batch Processing",
  "guide.timing.batchingDesc": "Accounts are processed in batches. Batch size equals concurrency, with interval delays between each batch.",
  "guide.timing.retries": "Retry Timing",
  "guide.timing.retriesDesc": "Failed accounts wait before retrying. Exponential backoff doubles the wait time with each attempt.",
  "guide.risk.safe": "Safe",
  "guide.risk.safeDesc": "Low-risk actions like reading data or checking balances. No funds at risk.",
  "guide.risk.medium": "Medium",
  "guide.risk.mediumDesc": "Moderate-risk actions like token approvals or swaps on tested protocols.",
  "guide.risk.risky": "Risky",
  "guide.risk.riskyDesc": "High-risk actions involving untested contracts or large fund movements. Use with caution.",
  "guide.simulation.preview": "Preview Mode",
  "guide.simulation.previewDesc": "Simulate the entire workflow without executing real transactions. See estimated timing and account flow.",
  "guide.simulation.howTo": "How to Simulate",
  "guide.simulation.howToDesc": "Click the play button on any card or use the top toolbar simulate button to preview execution.",
  "settings.nav.account": "Account",
  "settings.nav.interface": "Interface",
  "settings.nav.execution": "Execution",
  "settings.nav.security": "Security",
  "settings.nav.notifications": "Notifications",
  "settings.nav.data": "Data",
  "settings.nav.advanced": "Advanced",
  "settings.emailDesc": "Your registered email address",
  "settings.changePasswordDesc": "Set a new password for your account",
  "settings.twoFactor": "Two-Factor Authentication",
  "settings.twoFactorDesc": "Add an extra layer of security to your account",
  "settings.activeSessions": "Active Sessions",
  "settings.activeSessionsDesc": "Devices currently logged into your account",
  "settings.active": "active",
  "settings.logoutAll": "Sign Out Everywhere",
  "settings.logoutAllDesc": "Sign out from all devices and sessions",
  "settings.logoutAllBtn": "Sign Out All",
  "settings.timezone": "Timezone",
  "settings.timezoneDesc": "Set your preferred timezone for scheduling",
  "settings.timeFormat": "Time Format",
  "settings.timeFormatDesc": "Choose 12-hour or 24-hour time display",
  "settings.compactUI": "Compact UI",
  "settings.compactUIDesc": "Reduce spacing for a denser interface",
  "settings.executionNote": "These settings affect how workflows are executed across your accounts.",
  "settings.speedProfile": "Speed Profile",
  "settings.speedProfileDesc": "Controls delay between actions",
  "settings.speedSafe": "Safe",
  "settings.speedSafeDesc": "Maximum delays between actions",
  "settings.speedBalanced": "Balanced",
  "settings.speedBalancedDesc": "Moderate delays between actions",
  "settings.speedAggressive": "Aggressive",
  "settings.speedAggressiveDesc": "Minimal delays between actions",
  "settings.retryStrategy": "Retry Strategy",
  "settings.retryStrategyDesc": "How failed actions are retried",
  "settings.retryCons": "Conservative",
  "settings.retrySmart": "Smart",
  "settings.retryMax": "Maximum",
  "settings.randomization": "Randomization Level",
  "settings.randomizationDesc": "Adds random variance to timings and actions",
  "settings.randomLow": "Low",
  "settings.randomMedium": "Medium",
  "settings.randomHigh": "High",
  "settings.failureTolerance": "Failure Tolerance",
  "settings.failureToleranceDesc": "How the system handles individual account failures",
  "settings.failStrict": "Strict",
  "settings.failFlexible": "Flexible",
  "settings.privacyMode": "Privacy Mode",
  "settings.privacyModeDesc": "Mask wallet addresses and sensitive data in the UI",
  "settings.localExecution": "Local Execution Only",
  "settings.localExecutionDesc": "Process all workflows locally without cloud sync",
  "settings.dataRetention": "Data Retention Period",
  "settings.dataRetentionDesc": "How long execution logs are stored",
  "settings.days": "days",
  "settings.autoLogDeletion": "Auto Log Deletion",
  "settings.autoLogDeletionDesc": "Automatically delete old logs after the retention period",
  "settings.notifErrors": "Error Alerts",
  "settings.notifErrorsDesc": "Get notified when workflows encounter errors",
  "settings.notifCompletion": "Completion Alerts",
  "settings.notifCompletionDesc": "Get notified when workflows complete successfully",
  "settings.notifBilling": "Billing Alerts",
  "settings.notifBillingDesc": "Get notified about billing events and subscription changes",
  "settings.notifReferrals": "Referral Alerts",
  "settings.notifReferralsDesc": "Get notified when someone uses your referral link",
  "settings.notifUpdates": "Product Updates",
  "settings.notifUpdatesDesc": "Get notified about new features and platform updates",
  "settings.channels": "Notification Channels",
  "settings.channelEmail": "Email",
  "settings.channelInApp": "In-App",
  "settings.exportWorkflows": "Export Workflows",
  "settings.importWorkflows": "Import Workflows",
  "settings.backupSettings": "Backup Settings",
  "settings.resetEnvironment": "Reset Environment",
  "settings.confirmTitle": "Confirm Reset",
  "settings.confirmResetDesc": "This will reset all your settings to default values. This action cannot be undone.",
  "settings.confirmReset": "Reset All",
  "settings.enableAdvanced": "Enable Advanced Mode",
  "settings.enableAdvancedDesc": "Unlock debug logs, experimental features, and diagnostics",
  "settings.debugLogs": "Debug Logs",
  "settings.debugLogsDesc": "Show detailed debug logs in the console",
  "settings.experimentalFeatures": "Experimental Features",
  "settings.experimentalFeaturesDesc": "Enable experimental features that may be unstable",
  "settings.extendedDiagnostics": "Extended Diagnostics",
  "settings.extendedDiagnosticsDesc": "Run extended diagnostics on workflow execution",
  "paywall.title": "Unlock Execution",
  "paywall.description": "Upgrade your plan to run real automations and scale workflows.",
  "paywall.trialExhausted": "You've used all 3 free trial runs. Upgrade to continue executing workflows.",
  "paywall.trialUsed": "All 3 free trial executions used",
  "paywall.upgradePlan": "Upgrade Plan",
  "paywall.continueFree": "Continue in free mode",
  "paywall.bannerText": "You are on Free Plan — upgrade to run automations",
  "paywall.upgrade": "Upgrade",
  "paywall.trialRunsLeft": "trial runs left",
  "paywall.feat.multiAccount": "Multi-account execution",
  "paywall.feat.smartRouting": "Smart routing",
  "paywall.feat.advancedScheduling": "Advanced scheduling",
  "paywall.feat.priorityExecution": "Priority execution",
  "paywall.lockedFeature": "This feature requires a paid plan",
  "paywall.runLocked": "Execution is locked on the Free plan",
  "guest.badge": "Guest",
  "guest.badgeDesc": "Not signed in",
  "guest.bannerText": "You are in Guest Mode — create an account to save your work",
  "guest.createAccount": "Create Account",
  "guest.signupTitle": "Create Free Account",
  "guest.signupDefault": "Save your workflows and access them anytime",
  "guest.signupToSave": "Create an account to save your workflows permanently",
  "guest.signupToExport": "Create an account to export your workflows",
  "guest.signupToExecute": "Create an account to run workflow automation",
  "guest.signUpEmail": "Sign up with Email",
  "guest.continueGuest": "Continue as Guest",
  "guest.benefit.saveWorkflows": "Save workflows permanently",
  "guest.benefit.cloudBackup": "Cloud backup & sync",
  "guest.benefit.freeTrialRuns": "3 free trial executions",
  "guest.exitDashboard": "Exit",
  "checkout.title": "Complete Your Crypto Payment",
  "checkout.subtitle": "Send payment to activate your subscription instantly.",
  "checkout.backToPlans": "Back to plans",
  "checkout.awaitingPayment": "Awaiting payment",
  "checkout.invoiceExpires": "Invoice expires in",
  "checkout.invoiceExpired": "Invoice expired — please regenerate",
  "checkout.regenerate": "Regenerate Payment",
  "checkout.sendPaymentTo": "Send payment to this address",
  "checkout.copied": "Copied!",
  "checkout.evmNetwork": "EVM compatible network",
  "checkout.networkWarning": "Send only supported EVM assets. Wrong network = lost funds.",
  "checkout.confirmTransaction": "Confirm transaction",
  "checkout.enterTxHash": "Enter transaction hash",
  "checkout.confirmPayment": "Confirm Payment",
  "checkout.checkingBlockchain": "Checking blockchain…",
  "checkout.paymentDetected": "Payment detected",
  "checkout.subscriptionActivated": "Your subscription has been activated",
  "checkout.goToDashboard": "Go to Dashboard",
  "checkout.txNotFound": "Transaction not found. Please check the hash and try again.",
  "checkout.morePaymentMethods": "More payment methods",
  "checkout.comingSoon": "Coming soon",
  "checkout.securityFooter": "Payments are verified on-chain. Cetra never stores your private keys.",
  "checkout.duration.1month": "1 month",
  "checkout.duration.3months": "3 months",
  "checkout.duration.12months": "12 months",

  "tmpl.chooseCategory": "Choose a Category",
  "tmpl.categorySubtitle": "Select a category to browse preconfigured project templates.",
  "tmpl.projects": "projects",
  "tmpl.templates": "templates",
  "tmpl.comingSoon": "Coming Soon",
  "tmpl.useTemplate": "Use Template",
  "tmpl.blankWorkflow": "Blank Workflow",
  "tmpl.blankDesc": "Start with an empty canvas and build from scratch.",
  "tmpl.saveAsTemplate": "Save as Template",
  "tmpl.custom": "My Templates",
  "tmpl.customDesc": "Your saved custom workflow templates.",
  "tmpl.customSaved": "Custom saved workflow template.",

  "tmpl.cat.social": "Social Activity",
  "tmpl.cat.socialDesc": "Automate social engagement, quest completion, and community farming across platforms.",
  "tmpl.cat.testnet": "Testnet",
  "tmpl.cat.testnetDesc": "Automate testnet interactions including swaps, bridges, mints, and faucet claims.",
  "tmpl.cat.airdrop": "Airdrop",
  "tmpl.cat.airdropDesc": "Track and claim airdrops automatically across multiple chains.",
  "tmpl.cat.farming": "Farming",
  "tmpl.cat.farmingDesc": "Yield farming and liquidity provision automation strategies.",

  "tmpl.type.pointsFarming": "Points Farming",
  "tmpl.type.questCompletion": "Quest Completion",
  "tmpl.type.credentialFarming": "Credential Farming",
  "tmpl.type.socialEngagement": "Social Engagement",
  "tmpl.type.roleFarming": "Role Farming",
  "tmpl.type.testnetActivity": "Testnet Activity",
  "tmpl.type.crossChain": "Cross-Chain",
  "tmpl.type.l2Activity": "L2 Activity",
  "tmpl.type.ecosystemTasks": "Ecosystem Tasks",
  "tmpl.type.custom": "Custom",

  "tmpl.konnex.desc": "Earn Konnex points by completing social tasks: like, comment, repost, follow, join Discord, daily check-in, and referrals.",
  "tmpl.zealy.desc": "Automate Zealy quest completion and XP farming with daily quest monitoring.",
  "tmpl.galxe.desc": "Claim Galxe credentials and OATs by linking profiles and completing on-chain tasks.",
  "tmpl.twitter.desc": "Automate Twitter engagement: likes, retweets, and follows with human-like delays.",
  "tmpl.discord.desc": "Farm Discord roles through automated server joining, wallet verification, and activity.",
  "tmpl.pharos.desc": "Complete Pharos testnet activities: faucet claims, token swaps, bridging, NFT mints, and daily transactions.",
  "tmpl.layerzero.desc": "Automate LayerZero cross-chain bridge transactions across multiple testnets.",
  "tmpl.starknet.desc": "Generate Starknet on-chain activity: DEX swaps, liquidity provision, and NFT mints.",
  "tmpl.scroll.desc": "Interact with Scroll testnet: bridge, swap tokens, and generate daily transaction volume.",
  "tmpl.base.desc": "Complete Base ecosystem tasks: bridge, trade on Aerodrome, and mint Base NFTs.",
  "theme.light": "Light Mode",
  "theme.dark": "Dark Mode",
  "theme.default": "default",

  "tour.step1.title": "Navigation",
  "tour.step1.desc": "This is your main navigation. From here you can access all sections of the dashboard — workflows, groups, subscriptions, and more.",
  "tour.step2.title": "Workflow Builder",
  "tour.step2.desc": "Create automation workflows using a visual drag-and-drop builder. Choose from templates or build from scratch.",
  "tour.step3.title": "Subscription",
  "tour.step3.desc": "Manage your plan, view usage, and upgrade to unlock more accounts and features.",
  "tour.step4.title": "Referrals",
  "tour.step4.desc": "Invite friends and earn credits. Each referral gives you bonus automation credits.",
  "tour.step5.title": "Settings",
  "tour.step5.desc": "Customize your experience — language, theme, execution preferences, security, and more.",
  "tour.next": "Next",
  "tour.back": "Back",
  "tour.skip": "Skip",
  "tour.finish": "Finish",
  "settings.replayTour": "Onboarding Tour",
  "settings.replayTourDesc": "Replay the guided walkthrough of the dashboard",
  "settings.replayTourBtn": "Replay",

  "btour.replay": "Guide",
  "btour.step1.title": "Workflow Canvas",
  "btour.step1.desc": "This is your workflow canvas. Drag action cards here to build your automation. You can move cards freely, zoom in/out, and pan around.",
  "btour.step2.title": "Card Library",
  "btour.step2.desc": "This panel contains all available action cards. Drag any card onto the canvas to add a new automation step.",
  "btour.step3.title": "Action Card",
  "btour.step3.desc": "Each card represents an automation step. You can configure it, drag to reposition, and connect it to other cards using the ports on the sides.",
  "btour.step4.title": "Connections",
  "btour.step4.desc": "Connections define the execution order. Drag from an output port to an input port to create a flow. The workflow runs from top to bottom.",
  "btour.step5.title": "Settings Panel",
  "btour.step5.desc": "All card settings appear here when you select a card. Basic settings are visible by default, grouped by categories.",
  "btour.step6.title": "Advanced Mode",
  "btour.step6.desc": "Enable Advanced Mode to access extended parameters like execution logic, account targeting, and error handling. Recommended for experienced users.",
  "btour.step7.title": "Workflow Template",
  "btour.step7.desc": "This shows the workflow name. If built from a template, you can modify any block freely and save your changes as a custom template.",
  "btour.step8.title": "Save & Run",
  "btour.step8.desc": "Save your workflow to keep your progress. Use the Run button to start automation execution across your accounts.",

  "ctour.help": "Card settings guide",
  "ctour.step1.title": "Action Type",
  "ctour.step1.desc": "This is the type of action this card performs. It defines what the automation step does. The icon and color indicate the category.",
  "ctour.step2.title": "Basic Settings",
  "ctour.step2.desc": "These are required core parameters. Without these, the card cannot execute. Keep configuration minimal for simple workflows.",
  "ctour.step3.title": "Input Fields",
  "ctour.step3.desc": "This is a required parameter. Must be valid for execution to proceed. Some fields support variables or dynamic values.",
  "ctour.step4.title": "Delay Settings",
  "ctour.step4.desc": "Delay controls when the action executes. It helps simulate natural behavior and is useful for automation timing control.",
  "ctour.step5.title": "Retry Logic",
  "ctour.step5.desc": "Retry defines how many times the system reattempts on failure. This prevents workflow interruption. Higher retries may increase execution time.",
  "ctour.step6.title": "Advanced Mode",
  "ctour.step6.desc": "Enables extended configuration including hidden technical parameters. Recommended only for experienced users who need fine-grained control.",
  "ctour.step7.title": "Execution Behavior",
  "ctour.step7.desc": "Defines whether the action runs sequentially, in parallel, or conditionally. This affects overall workflow logic and performance.",
  "ctour.step8.title": "Save Changes",
  "ctour.step8.desc": "Changes are applied automatically as you configure. Always confirm your settings before running the workflow.",
  "onboarding.welcome": "Welcome to Cetra!",
  "onboarding.clickBuilder": "Let's get started! Click the highlighted Workflow Builder item in the sidebar to create your first automation.",
  "onboarding.builderPhase": "Great! Now explore the builder canvas. Follow the guided tour to learn the basics.",
  "onboarding.cardPhase": "Almost done! Click on any card to see its settings panel and complete the tour.",
  "onboarding.complete": "You're all set! You now know how to build and configure workflows."
}
