{
  "nav.dashboard": "Panel de control",
  "nav.workflowBuilder": "Constructor de flujos",
  "nav.subscription": "Suscripción",
  "nav.referrals": "Referidos",
  "nav.settings": "Configuración",
  "nav.accountGroups": "Grupos de cuentas",
  "nav.logOut": "Cerrar sesión",
  "dashboard.title": "Panel de control",
  "dashboard.subtitle": "Resumen de tu actividad de automatización",
  "dashboard.agentStatus": "Estado del agente",
  "dashboard.online": "En línea",
  "dashboard.efficiency": "Eficiencia",
  "dashboard.totalRuns": "Ejecuciones totales",
  "dashboard.totalAccounts": "Cuentas totales",
  "dashboard.successful": "Exitosas",
  "dashboard.failed": "Fallidas",
  "dashboard.automationActivity": "Actividad de automatización",
  "dashboard.runsAndEfficiency": "Ejecuciones y eficiencia",
  "dashboard.last7days": "Últimos 7 días",
  "dashboard.last30days": "Últimos 30 días",
  "dashboard.recentActivity": "Actividad reciente",
  "dashboard.latestEvents": "Últimos eventos en todas las cuentas",
  "dashboard.batchExecutions": "Ejecuciones por lotes",
  "dashboard.groupsSubtitle": "Grupos en todos los flujos",
  "dashboard.all": "Todos",
  "dashboard.success": "Éxito",
  "dashboard.partial": "Parcial",
  "dashboard.noGroupsMatch": "No hay grupos que coincidan con este filtro.",
  "dashboard.accounts": "cuentas",
  "dashboard.ok": "ok",
  "dashboard.err": "err",
  "dashboard.wait": "esp",
  "dashboard.retryGroup": "Reintentar grupo",
  "dashboard.retryAccount": "Reintentar",
  "dashboard.failedAccounts": "Cuentas fallidas",
  "dashboard.pending": "Pendiente",
  "dashboard.allCompleted": "Las {count} cuentas se completaron exitosamente.",
  "dashboard.noAccountsInGroup": "Aún no hay cuentas en este grupo.",
  "dashboard.recentExecutions": "Ejecuciones Recientes",
  "dashboard.step": "Paso",
  "workflow.title": "Constructor de flujos",
  "workflow.save": "Guardar",
  "workflow.simulate": "Simular",
  "workflow.stopSim": "Parar",
  "workflow.export": "Exportar",
  "workflow.import": "Importar",
  "workflow.clear": "Limpiar",
  "workflow.undo": "Deshacer",
  "workflow.redo": "Rehacer",
  "workflow.zoomIn": "Acercar",
  "workflow.zoomOut": "Alejar",
  "workflow.nodeLibrary": "Biblioteca de nodos",
  "workflow.dragToAdd": "Arrastra para añadir",
  "workflow.nodeConfig": "Configuración de nodo",
  "workflow.selectNode": "Selecciona un nodo para configurar",
  "workflow.delete": "Eliminar",
  "workflow.type": "Tipo",
  "workflow.label": "Etiqueta",
  "workflow.interval": "Intervalo",
  "workflow.duration": "Duración (días)",
  "workflow.splitPercentage": "Porcentaje",
  "workflow.splitCount": "Cantidad",
  "workflow.executionMode": "Modo de ejecución",
  "workflow.sequential": "Secuencial",
  "workflow.parallel": "Paralelo",
  "workflow.randomize": "Orden aleatorio",
  "workflow.targetGroup": "Grupo objetivo",
  "workflow.allAccounts": "Todas las cuentas",
  "workflow.selectGroup": "Seleccionar grupo...",
  "workflow.noNodes": "Sin nodos",
  "workflow.dropHere": "Arrastra nodos desde la biblioteca",
  "workflow.advancedMode": "Modo Avanzado",
  "workflow.basicSettings": "Configuración Básica",
  "workflow.timingIntervals": "Temporizado e Intervalos",
  "workflow.executionLogic": "Lógica de Ejecución",
  "workflow.accountTargeting": "Segmentación de Cuentas",
  "workflow.advancedSettings": "Configuración Avanzada",
  "workflow.websiteTargetUrl": "Sitio / URL de Destino",
  "workflow.accountGroup": "Grupo de Cuentas",
  "workflow.executionPriority": "Prioridad de Ejecución",
  "workflow.delayBeforeStart": "Retraso Antes de Iniciar",
  "workflow.delayRandomization": "Rango de Aleatorización (seg)",
  "workflow.timeoutBehavior": "Comportamiento de Tiempo Límite",
  "workflow.conditionalExecution": "Ejecución Condicional",
  "workflow.successConfirmation": "Regla de Confirmación de Éxito",
  "workflow.concurrency": "Concurrencia",
  "workflow.executionOrder": "Orden de Ejecución",
  "workflow.errorStrategy": "Estrategia de Error",
  "workflow.retryStrategy": "Estrategia de Reintento",
  "workflow.failSafeStop": "Parada de Seguridad",
  "workflow.loggingLevel": "Nivel de Registro",
  "workflow.maxAttemptsLimit": "Límite de Intentos",
  "workflow.riskLevel": "Nivel de Riesgo",
  "subscription.title": "Suscripción",
  "subscription.subtitle": "Elige el período de facturación que mejor te convenga",
  "subscription.monthly": "Mensual",
  "subscription.3months": "3 Meses",
  "subscription.yearly": "Anual",
  "subscription.billedMonthly": "Facturado mensualmente",
  "subscription.billedEvery3Months": "Facturado cada 3 meses",
  "subscription.billedAnnually": "Facturado anualmente",
  "subscription.saveVsMonthly": "Ahorra {percent}% vs mensual",
  "subscription.perMonth": "mes",
  "subscription.currentPlan": "Plan Actual",
  "subscription.status": "Estado",
  "subscription.active": "Activo",
  "subscription.freeTrial": "Prueba gratuita",
  "subscription.freeMode": "Estás en modo gratuito",
  "subscription.freeModeSub": "Funciones limitadas. Desbloquea el poder completo de la automatización.",
  "subscription.unlockFull": "Desbloquear automatización",
  "subscription.trialEnds": "La prueba termina en",
  "subscription.days": "días",
  "subscription.upgradePlan": "Mejorar plan",
  "subscription.currentPlanBadge": "Plan actual",
  "subscription.mostPopular": "Más popular",
  "subscription.allPlansUnlimited": "Todos los planes incluyen cuentas ilimitadas",
  "subscription.feat.unlimitedAccounts": "Cuentas ilimitadas",
  "subscription.feat.highSpeed": "Nivel de ejecución de alta velocidad",
  "subscription.feat.priorityQueue": "Cola prioritaria",
  "subscription.feat.advancedErrors": "Manejo avanzado de errores",
  "subscription.feat.workflowAnalytics": "Analítica de flujos",
  "subscription.feat.aiAssistant": "Asistente IA de flujos",
  "subscription.feat.premiumSupport": "Soporte premium",
  "subscription.why.fasterExec": "Ejecución más rápida",
  "subscription.why.fasterExecDesc": "La cola prioritaria garantiza automatización ultrarrápida",
  "subscription.why.smarterRecovery": "Recuperación más inteligente",
  "subscription.why.smarterRecoveryDesc": "El manejo de errores con IA recupera fallos automáticamente",
  "subscription.why.aiAssist": "Asistencia IA",
  "subscription.why.aiAssistDesc": "Sugerencias inteligentes y optimización de flujos",
  "subscription.why.priorityInfra": "Infraestructura prioritaria",
  "subscription.why.priorityInfraDesc": "Recursos dedicados para máxima fiabilidad",
  "subscription.why.premiumReliability": "Fiabilidad premium",
  "subscription.why.premiumReliabilityDesc": "Estabilidad empresarial para automatización crítica",
  "subscription.whyUpgrade": "¿Por qué mejorar?",
  "subscription.cryptoPayments": "Pagos cripto aceptados",
  "subscription.paymentMethods": "Métodos de pago",
  "referrals.title": "Referidos",
  "referrals.subtitle": "Invita amigos. Gana créditos.",
  "referrals.creditsTitle": "¿Qué son los créditos?",
  "referrals.creditsDesc": "Los créditos son un saldo de bonificación ganado por referidos.",
  "referrals.creditsUseIntro": "Puedes usar los créditos para:",
  "referrals.creditUse1": "Pagar suscripciones",
  "referrals.creditUse2": "Mejorar tu plan",
  "referrals.creditUse3": "Desbloquear funciones premium",
  "referrals.creditsAutoApply": "Los créditos se aplican automáticamente al pagar.",
  "referrals.heroText": "Recibe recompensas cada vez que tus referidos se suscriban.",
  "referrals.earnPercent": "Ganas el 20% de cada pago en créditos de la plataforma",
  "referrals.yourLink": "Tu enlace de referido",
  "referrals.shareLink": "Comparte para ganar recompensas",
  "referrals.copied": "Copiado",
  "referrals.copy": "Copiar",
  "referrals.shareTelegram": "Telegram",
  "referrals.shareX": "X",
  "referrals.shareDiscord": "Discord",
  "referrals.activeReferrals": "Referidos activos",
  "referrals.totalEarned": "Total de créditos ganados",
  "referrals.currentLevel": "Nivel actual",
  "referrals.lifetimeCommission": "Comisión vitalicia %",
  "referrals.yourLevel": "Tu nivel de referidos",
  "referrals.level1": "Inicial",
  "referrals.level1Req": "1-4 referidos activos",
  "referrals.level1Perk": "20% créditos en pagos",
  "referrals.level2": "Crecimiento",
  "referrals.level2Req": "5-9 referidos activos",
  "referrals.level2Perk1": "30% créditos en pagos",
  "referrals.level2Perk2": "20% descuento en suscripción",
  "referrals.level3": "Socio",
  "referrals.level3Req": "10+ referidos activos",
  "referrals.level3Perk1": "10% comisión vitalicia",
  "referrals.level3Perk2": "Insignia de socio",
  "referrals.level4": "Embajador",
  "referrals.level4Req": "50+ referidos activos",
  "referrals.level4Perk1": "Insignia de embajador",
  "referrals.level4Perk2": "Recompensas exclusivas",
  "referrals.unlocked": "Desbloqueado",
  "referrals.locked": "Bloqueado",
  "referrals.current": "Actual",
  "referrals.activity": "Actividad de referidos",
  "referrals.colUserId": "ID de usuario",
  "referrals.colPlan": "Plan comprado",
  "referrals.colAmount": "Monto del pago",
  "referrals.colReward": "Tu recompensa",
  "referrals.colStatus": "Estado",
  "referrals.statusPending": "Pendiente",
  "referrals.statusActive": "Activo",
  "referrals.statusExpired": "Expirado",
  "referrals.creditsWallet": "Cartera de créditos",
  "referrals.availableCredits": "Créditos disponibles",
  "referrals.lifetimeEarned": "Ganados en total",
  "referrals.creditsUsed": "Créditos usados",
  "referrals.applyCredits": "Aplicar créditos a suscripción",
  "referrals.creditsTooltip": "Los créditos reducen automáticamente tu próximo pago",
  "referrals.achievements": "Logros",
  "referrals.achFirstRef": "Primer referido",
  "referrals.achFiveRef": "5 referidos",
  "referrals.achTopPartner": "Socio top",
  "referrals.emptyTitle": "Empieza a invitar amigos para desbloquear recompensas",
  "referrals.emptyCta": "Copiar enlace de referido",
  "settings.title": "Configuración",
  "settings.subtitle": "Gestiona tus preferencias",
  "settings.profile": "Perfil",
  "settings.displayName": "Nombre",
  "settings.email": "Correo",
  "settings.saveChanges": "Guardar",
  "settings.notifications": "Notificaciones",
  "settings.emailNotifications": "Notificaciones por correo",
  "settings.emailNotificationsDesc": "Recibir actualizaciones de flujos",
  "settings.workflowAlerts": "Alertas de flujos",
  "settings.workflowAlertsDesc": "Notificación al completar o fallar",
  "settings.marketingEmails": "Correos de marketing",
  "settings.marketingEmailsDesc": "Actualizaciones y anuncios",
  "settings.security": "Seguridad",
  "settings.changePassword": "Cambiar contraseña",
  "settings.lastPasswordChange": "Último cambio de contraseña: Nunca",
  "settings.language": "Idioma",
  "settings.languageDesc": "Selecciona tu idioma preferido",
  "groups.title": "Grupos de cuentas",
  "groups.subtitle": "Organiza cuentas en grupos lógicos",
  "groups.createGroup": "Crear grupo",
  "groups.newGroup": "Nuevo grupo",
  "groups.groupName": "Nombre del grupo",
  "groups.enterGroupName": "Ingresa el nombre",
  "groups.create": "Crear",
  "groups.cancel": "Cancelar",
  "groups.rename": "Renombrar",
  "groups.delete": "Eliminar",
  "groups.deleteConfirm": "¿Eliminar este grupo? Las cuentas serán desasignadas.",
  "groups.noGroups": "Sin grupos. Crea uno para organizar tus cuentas.",
  "groups.accountCount": "{count} cuentas",
  "groups.lastActivity": "Última actividad",
  "groups.activeWorkflows": "Flujos activos",
  "groups.successRate": "Tasa de éxito",
  "groups.manageAccounts": "Gestionar cuentas",
  "groups.availableAccounts": "Cuentas disponibles",
  "groups.groupAccounts": "Cuentas del grupo",
  "groups.dragToAssign": "Arrastra para asignar",
  "groups.noAvailable": "Todas las cuentas están asignadas.",
  "groups.noAccountsInGroup": "Sin cuentas en este grupo.",
  "groups.addToGroup": "Añadir",
  "groups.removeFromGroup": "Quitar",
  "groups.overview": "Resumen",
  "groups.backToGroups": "Volver a grupos",
  "groups.totalInGroup": "Total en grupo",
  "groups.successfulRuns": "Ejecuciones exitosas",
  "groups.failedRuns": "Ejecuciones fallidas",
  "groups.recentExecutions": "Ejecuciones recientes",
  "groups.noExecutions": "Sin ejecuciones para este grupo.",
  "groups.status": "Estado",
  "groups.workflow": "Flujo",
  "groups.time": "Hora",
  "groups.moveToGroup": "Mover a grupo",
  "groups.notFound": "Grupo no encontrado.",
  "nodeType.wallet": "Acción de billetera",
  "nodeType.delay": "Retraso",
  "nodeType.split": "Dividir grupo",
  "nodeType.condition": "Condicional",
  "nodeType.swap": "Intercambio",
  "nodeType.loop": "Bucle",
  "nodeType.bridge": "Puente",
  "nodeType.notify": "Notificación",
  "nodeType.repeat": "Bucle de repetición",
  "nodeType.airdrop": "Reclamo de airdrop",
  "nodeType.script": "Script personalizado",
  "status.success": "Éxito",
  "status.partial": "Parcial",
  "status.failed": "Fallido",
  "status.pending": "Pendiente",
  "status.running": "Ejecutando",
  "common.save": "Guardar",
  "common.cancel": "Cancelar",
  "common.delete": "Eliminar",
  "common.edit": "Editar",
  "common.close": "Cerrar",
  "common.confirm": "Confirmar",
  "common.search": "Buscar",
  "common.noResults": "Sin resultados.",
  "guide.title": "Guía de Configuración",
  "guide.section.overview": "Controles Básicos",
  "guide.section.advanced": "Configuración Avanzada",
  "guide.section.timing": "Temporización y Retrasos",
  "guide.section.risk": "Indicadores de Riesgo",
  "guide.section.simulation": "Modo Simulación",
  "guide.overview.accountGroup": "Grupo de Cuentas",
  "guide.overview.accountGroupDesc": "Seleccione qué grupo de cuentas ejecutará esta acción. Los grupos se gestionan en la página de Grupos de Cuentas.",
  "guide.overview.urlTarget": "URL / Destino",
  "guide.overview.urlTargetDesc": "La URL de destino o dirección del contrato con la que interactuará esta acción.",
  "guide.overview.delay": "Retraso",
  "guide.overview.delayDesc": "Tiempo de espera antes de ejecutar esta acción. Ayuda a evitar detección y límites.",
  "guide.overview.onSuccess": "Al Éxito",
  "guide.overview.onSuccessDesc": "Qué ocurre tras completar exitosamente — continuar al siguiente, repetir o detener.",
  "guide.advanced.concurrency": "Concurrencia",
  "guide.advanced.concurrencyDesc": "Cuántas cuentas ejecutan esta acción simultáneamente. Más rápido pero más arriesgado.",
  "guide.advanced.interval": "Intervalo",
  "guide.advanced.intervalDesc": "Tiempo entre cada lote de cuentas. Controla el ritmo de ejecución.",
  "guide.advanced.jitter": "Variación",
  "guide.advanced.jitterDesc": "Añade variación aleatoria al tiempo, haciendo las acciones más humanas y naturales.",
  "guide.advanced.retryLogic": "Lógica de Reintentos",
  "guide.advanced.retryLogicDesc": "Cómo se reintentan las acciones fallidas — intentos, retraso entre reintentos y estrategia.",
  "guide.advanced.conditions": "Condiciones",
  "guide.advanced.conditionsDesc": "Verificaciones previas: saldo mínimo, límites de gas y otros requisitos.",
  "guide.advanced.errorHandling": "Manejo de Errores",
  "guide.advanced.errorHandlingDesc": "Qué ocurre cuando falla una acción — omitir la cuenta, reintentar o detener todo el flujo.",
  "guide.timing.delays": "Tipos de Retraso",
  "guide.timing.delaysDesc": "Los retrasos fijos esperan un tiempo establecido. Los aleatorios añaden variación para comportamiento más natural.",
  "guide.timing.batching": "Procesamiento por Lotes",
  "guide.timing.batchingDesc": "Las cuentas se procesan en lotes. El tamaño del lote es igual a la concurrencia, con intervalos entre cada uno.",
  "guide.timing.retries": "Temporización de Reintentos",
  "guide.timing.retriesDesc": "Las cuentas fallidas esperan antes de reintentar. El retroceso exponencial duplica el tiempo con cada intento.",
  "guide.risk.safe": "Seguro",
  "guide.risk.safeDesc": "Acciones de bajo riesgo como lectura de datos o verificación de saldos. Sin fondos en riesgo.",
  "guide.risk.medium": "Medio",
  "guide.risk.mediumDesc": "Acciones de riesgo moderado como aprobaciones de tokens o intercambios en protocolos probados.",
  "guide.risk.risky": "Arriesgado",
  "guide.risk.riskyDesc": "Acciones de alto riesgo con contratos no probados o grandes movimientos de fondos. Use con precaución.",
  "guide.simulation.preview": "Modo Vista Previa",
  "guide.simulation.previewDesc": "Simule todo el flujo sin ejecutar transacciones reales. Vea tiempos estimados y flujo de cuentas.",
  "guide.simulation.howTo": "Cómo Simular",
  "guide.simulation.howToDesc": "Haga clic en el botón de reproducción en cualquier tarjeta o use el botón de simulación de la barra de herramientas.",
  "settings.nav.account": "Cuenta",
  "settings.nav.interface": "Interfaz",
  "settings.nav.execution": "Ejecución",
  "settings.nav.security": "Seguridad",
  "settings.nav.notifications": "Notificaciones",
  "settings.nav.data": "Datos",
  "settings.nav.advanced": "Avanzado",
  "settings.emailDesc": "Tu dirección de correo electrónico registrada",
  "settings.changePasswordDesc": "Establecer una nueva contraseña para tu cuenta",
  "settings.twoFactor": "Autenticación de dos factores",
  "settings.twoFactorDesc": "Añadir una capa extra de seguridad a tu cuenta",
  "settings.activeSessions": "Sesiones activas",
  "settings.activeSessionsDesc": "Dispositivos con sesión iniciada en tu cuenta",
  "settings.active": "activa",
  "settings.logoutAll": "Cerrar sesión en todos lados",
  "settings.logoutAllDesc": "Cerrar sesión en todos los dispositivos y sesiones",
  "settings.logoutAllBtn": "Cerrar todas las sesiones",
  "settings.timezone": "Zona horaria",
  "settings.timezoneDesc": "Establece tu zona horaria preferida para la programación",
  "settings.timeFormat": "Formato de hora",
  "settings.timeFormatDesc": "Elige entre formato de 12 o 24 horas",
  "settings.compactUI": "Interfaz compacta",
  "settings.compactUIDesc": "Reducir el espaciado para una interfaz más densa",
  "settings.executionNote": "Estos ajustes afectan cómo se ejecutan los flujos en todas tus cuentas.",
  "settings.speedProfile": "Perfil de velocidad",
  "settings.speedProfileDesc": "Controla la demora entre acciones",
  "settings.speedSafe": "Seguro",
  "settings.speedSafeDesc": "Demoras máximas entre acciones",
  "settings.speedBalanced": "Equilibrado",
  "settings.speedBalancedDesc": "Demoras moderadas entre acciones",
  "settings.speedAggressive": "Agresivo",
  "settings.speedAggressiveDesc": "Demoras mínimas entre acciones",
  "settings.retryStrategy": "Estrategia de reintentos",
  "settings.retryStrategyDesc": "Cómo se reintentan las acciones fallidas",
  "settings.retryCons": "Conservador",
  "settings.retrySmart": "Inteligente",
  "settings.retryMax": "Máximo",
  "settings.randomization": "Nivel de aleatorización",
  "settings.randomizationDesc": "Añade variación aleatoria a tiempos y acciones",
  "settings.randomLow": "Bajo",
  "settings.randomMedium": "Medio",
  "settings.randomHigh": "Alto",
  "settings.failureTolerance": "Tolerancia a fallos",
  "settings.failureToleranceDesc": "Cómo el sistema gestiona los fallos de cuentas individuales",
  "settings.failStrict": "Estricto",
  "settings.failFlexible": "Flexible",
  "settings.privacyMode": "Modo de privacidad",
  "settings.privacyModeDesc": "Ocultar direcciones de billetera y datos sensibles en la interfaz",
  "settings.localExecution": "Solo ejecución local",
  "settings.localExecutionDesc": "Procesar todos los flujos localmente sin sincronización en la nube",
  "settings.dataRetention": "Período de retención de datos",
  "settings.dataRetentionDesc": "Cuánto tiempo se almacenan los registros de ejecución",
  "settings.days": "días",
  "settings.autoLogDeletion": "Eliminación automática de registros",
  "settings.autoLogDeletionDesc": "Eliminar automáticamente los registros antiguos tras el período de retención",
  "settings.notifErrors": "Alertas de errores",
  "settings.notifErrorsDesc": "Recibir notificación cuando los flujos encuentren errores",
  "settings.notifCompletion": "Alertas de finalización",
  "settings.notifCompletionDesc": "Recibir notificación cuando los flujos se completen correctamente",
  "settings.notifBilling": "Alertas de facturación",
  "settings.notifBillingDesc": "Recibir notificación sobre eventos de facturación y cambios de suscripción",
  "settings.notifReferrals": "Alertas de referidos",
  "settings.notifReferralsDesc": "Recibir notificación cuando alguien use tu enlace de referido",
  "settings.notifUpdates": "Actualizaciones del producto",
  "settings.notifUpdatesDesc": "Recibir notificación sobre nuevas funciones y actualizaciones de la plataforma",
  "settings.channels": "Canales de notificación",
  "settings.channelEmail": "Correo electrónico",
  "settings.channelInApp": "En la aplicación",
  "settings.exportWorkflows": "Exportar flujos",
  "settings.importWorkflows": "Importar flujos",
  "settings.backupSettings": "Copia de seguridad de ajustes",
  "settings.resetEnvironment": "Restablecer entorno",
  "settings.confirmTitle": "Confirmar restablecimiento",
  "settings.confirmResetDesc": "Esto restablecerá todos tus ajustes a los valores predeterminados. Esta acción no se puede deshacer.",
  "settings.confirmReset": "Restablecer todo",
  "settings.enableAdvanced": "Activar modo avanzado",
  "settings.enableAdvancedDesc": "Desbloquear registros de depuración, funciones experimentales y diagnósticos",
  "settings.debugLogs": "Registros de depuración",
  "settings.debugLogsDesc": "Mostrar registros detallados de depuración en la consola",
  "settings.experimentalFeatures": "Funciones experimentales",
  "settings.experimentalFeaturesDesc": "Activar funciones experimentales que pueden ser inestables",
  "settings.extendedDiagnostics": "Diagnósticos extendidos",
  "settings.extendedDiagnosticsDesc": "Ejecutar diagnósticos extendidos en la ejecución de flujos",
  "paywall.title": "Desbloquear ejecución",
  "paywall.description": "Actualiza tu plan para ejecutar automatizaciones reales y escalar flujos de trabajo.",
  "paywall.trialExhausted": "Has usado las 3 ejecuciones de prueba. Actualiza para continuar.",
  "paywall.trialUsed": "3 ejecuciones de prueba usadas",
  "paywall.upgradePlan": "Actualizar plan",
  "paywall.continueFree": "Continuar en modo gratuito",
  "paywall.bannerText": "Estás en el plan gratuito — actualiza para ejecutar automatizaciones",
  "paywall.upgrade": "Actualizar",
  "paywall.trialRunsLeft": "ejecuciones de prueba restantes",
  "paywall.feat.multiAccount": "Ejecución multi-cuenta",
  "paywall.feat.smartRouting": "Enrutamiento inteligente",
  "paywall.feat.advancedScheduling": "Programación avanzada",
  "paywall.feat.priorityExecution": "Ejecución prioritaria",
  "paywall.lockedFeature": "Esta función requiere un plan de pago",
  "paywall.runLocked": "La ejecución está bloqueada en el plan gratuito",
  "guest.badge": "Invitado",
  "guest.badgeDesc": "No autenticado",
  "guest.bannerText": "Estás en modo invitado — crea una cuenta para guardar tu trabajo",
  "guest.createAccount": "Crear cuenta",
  "guest.signupTitle": "Crear cuenta gratuita",
  "guest.signupDefault": "Guarda tus flujos de trabajo y accede a ellos en cualquier momento",
  "guest.signupToSave": "Crea una cuenta para guardar tus flujos de trabajo de forma permanente",
  "guest.signupToExport": "Crea una cuenta para exportar tus flujos de trabajo",
  "guest.signupToExecute": "Crea una cuenta para ejecutar la automatización",
  "guest.signUpEmail": "Registrarse con Email",
  "guest.continueGuest": "Continuar como invitado",
  "guest.benefit.saveWorkflows": "Guardar flujos de trabajo permanentemente",
  "guest.benefit.cloudBackup": "Respaldo en la nube y sincronización",
  "guest.benefit.freeTrialRuns": "3 ejecuciones de prueba gratuitas",
  "guest.exitDashboard": "Salir",
  "checkout.title": "Completa tu pago cripto",
  "checkout.subtitle": "Envía el pago para activar tu suscripción al instante.",
  "checkout.backToPlans": "Volver a planes",
  "checkout.awaitingPayment": "Esperando pago",
  "checkout.invoiceExpires": "La factura expira en",
  "checkout.invoiceExpired": "Factura expirada — regenerar pago",
  "checkout.regenerate": "Regenerar pago",
  "checkout.sendPaymentTo": "Envía el pago a esta dirección",
  "checkout.copied": "¡Copiado!",
  "checkout.evmNetwork": "Red compatible con EVM",
  "checkout.networkWarning": "Envía solo activos EVM compatibles. Red incorrecta = fondos perdidos.",
  "checkout.confirmTransaction": "Confirmar transacción",
  "checkout.enterTxHash": "Ingresa el hash de transacción",
  "checkout.confirmPayment": "Confirmar pago",
  "checkout.checkingBlockchain": "Verificando blockchain…",
  "checkout.paymentDetected": "Pago detectado",
  "checkout.subscriptionActivated": "Tu suscripción ha sido activada",
  "checkout.goToDashboard": "Ir al panel",
  "checkout.txNotFound": "Transacción no encontrada. Verifica el hash e intenta de nuevo.",
  "checkout.morePaymentMethods": "Más métodos de pago",
  "checkout.comingSoon": "Próximamente",
  "checkout.securityFooter": "Los pagos se verifican en la cadena. Cetra nunca almacena tus claves privadas.",
  "checkout.duration.1month": "1 mes",
  "checkout.duration.3months": "3 meses",
  "checkout.duration.12months": "12 meses",

  "tmpl.chooseCategory": "Elige una categoría",
  "tmpl.categorySubtitle": "Selecciona una categoría para explorar plantillas de proyectos preconfiguradas.",
  "tmpl.projects": "proyectos",
  "tmpl.templates": "plantillas",
  "tmpl.comingSoon": "Próximamente",
  "tmpl.useTemplate": "Usar plantilla",
  "tmpl.blankWorkflow": "Flujo vacío",
  "tmpl.blankDesc": "Comienza con un lienzo vacío y construye desde cero.",
  "tmpl.saveAsTemplate": "Guardar como plantilla",
  "tmpl.custom": "Mis plantillas",
  "tmpl.customDesc": "Tus plantillas de flujos personalizadas guardadas.",
  "tmpl.customSaved": "Plantilla de flujo personalizada guardada.",

  "tmpl.cat.social": "Actividad social",
  "tmpl.cat.socialDesc": "Automatiza la interacción social, la finalización de quests y el farming de comunidades en múltiples plataformas.",
  "tmpl.cat.testnet": "Testnet",
  "tmpl.cat.testnetDesc": "Automatiza interacciones con testnets incluyendo swaps, bridges, mints y reclamos de faucets.",
  "tmpl.cat.airdrop": "Airdrop",
  "tmpl.cat.airdropDesc": "Rastrea y reclama airdrops automáticamente en múltiples cadenas.",
  "tmpl.cat.farming": "Farming",
  "tmpl.cat.farmingDesc": "Estrategias de automatización de farming de rendimiento y provisión de liquidez.",

  "tmpl.type.pointsFarming": "Farming de puntos",
  "tmpl.type.questCompletion": "Completar quests",
  "tmpl.type.credentialFarming": "Farming de credenciales",
  "tmpl.type.socialEngagement": "Interacción social",
  "tmpl.type.roleFarming": "Farming de roles",
  "tmpl.type.testnetActivity": "Actividad en testnet",
  "tmpl.type.crossChain": "Cross-Chain",
  "tmpl.type.l2Activity": "Actividad L2",
  "tmpl.type.ecosystemTasks": "Tareas del ecosistema",
  "tmpl.type.custom": "Personalizado",

  "tmpl.konnex.desc": "Gana puntos Konnex completando tareas sociales: likes, comentarios, reposts, seguir, unirte a Discord, check-in diario y referidos.",
  "tmpl.zealy.desc": "Automatiza la finalización de quests de Zealy y el farming de XP con monitoreo diario de quests.",
  "tmpl.galxe.desc": "Reclama credenciales de Galxe y OATs vinculando perfiles y completando tareas on-chain.",
  "tmpl.twitter.desc": "Automatiza la interacción en Twitter: likes, retweets y follows con retrasos similares a los humanos.",
  "tmpl.discord.desc": "Farmea roles de Discord mediante unión automática a servidores, verificación de billeteras y actividad.",
  "tmpl.pharos.desc": "Completa actividades en la testnet de Pharos: reclamos de faucet, swaps de tokens, bridging, mints de NFT y transacciones diarias.",
  "tmpl.layerzero.desc": "Automatiza transacciones de bridge cross-chain de LayerZero en múltiples testnets.",
  "tmpl.starknet.desc": "Genera actividad on-chain en Starknet: swaps en DEX, provisión de liquidez y mints de NFT.",
  "tmpl.scroll.desc": "Interactúa con la testnet de Scroll: bridge, swap de tokens y genera volumen de transacciones diario.",
  "tmpl.base.desc": "Completa tareas del ecosistema Base: bridge, trading en Aerodrome y mint de NFTs en Base.",
  "theme.light": "Modo claro",
  "theme.dark": "Modo oscuro",
  "theme.default": "predeterminado",

  "tour.step1.title": "Navegación",
  "tour.step1.desc": "Esta es tu navegación principal. Desde aquí puedes acceder a todas las secciones — flujos de trabajo, grupos, suscripción y más.",
  "tour.step2.title": "Constructor de flujos",
  "tour.step2.desc": "Crea automatizaciones con el constructor visual. Elige plantillas predefinidas o crea desde cero.",
  "tour.step3.title": "Suscripción",
  "tour.step3.desc": "Gestiona tu plan, revisa el uso y mejora tu tarifa para acceder a más cuentas y funciones.",
  "tour.step4.title": "Referidos",
  "tour.step4.desc": "Invita amigos y gana créditos. Cada referido te da créditos de automatización adicionales.",
  "tour.step5.title": "Configuración",
  "tour.step5.desc": "Personaliza tu experiencia — idioma, tema, preferencias de ejecución, seguridad y más.",
  "tour.next": "Siguiente",
  "tour.back": "Atrás",
  "tour.skip": "Omitir",
  "tour.finish": "Finalizar",
  "settings.replayTour": "Tour de bienvenida",
  "settings.replayTourDesc": "Repetir el recorrido guiado del panel de control",
  "settings.replayTourBtn": "Repetir",

  "btour.replay": "Guía",
  "btour.step1.title": "Lienzo de flujo",
  "btour.step1.desc": "Este es tu lienzo de trabajo. Arrastra tarjetas de acción aquí para crear tu automatización. Puedes mover tarjetas, hacer zoom y desplazarte.",
  "btour.step2.title": "Biblioteca de tarjetas",
  "btour.step2.desc": "Este panel contiene todas las tarjetas de acción disponibles. Arrastra cualquier tarjeta al lienzo para añadir un nuevo paso de automatización.",
  "btour.step3.title": "Tarjeta de acción",
  "btour.step3.desc": "Cada tarjeta representa un paso de automatización. Configúrala, arrástrala para reposicionarla y conéctala con otras tarjetas usando los puertos laterales.",
  "btour.step4.title": "Conexiones",
  "btour.step4.desc": "Las conexiones definen el orden de ejecución. Arrastra desde un puerto de salida a uno de entrada para crear un flujo. El flujo se ejecuta de arriba a abajo.",
  "btour.step5.title": "Panel de configuración",
  "btour.step5.desc": "Todas las configuraciones de la tarjeta aparecen aquí al seleccionarla. Las opciones básicas son visibles por defecto, agrupadas por categorías.",
  "btour.step6.title": "Modo avanzado",
  "btour.step6.desc": "Activa el Modo Avanzado para acceder a parámetros extendidos como lógica de ejecución, segmentación de cuentas y manejo de errores. Recomendado para usuarios expertos.",
  "btour.step7.title": "Plantilla del flujo",
  "btour.step7.desc": "Aquí se muestra el nombre del flujo. Si se creó a partir de una plantilla, puedes modificar cualquier bloque y guardar tus cambios como plantilla personalizada.",
  "btour.step8.title": "Guardar y ejecutar",
  "btour.step8.desc": "Guarda tu flujo de trabajo para conservar tu progreso. Usa el botón Ejecutar para iniciar la automatización en tus cuentas.",

  "ctour.help": "Guía de configuración de tarjeta",
  "ctour.step1.title": "Tipo de acción",
  "ctour.step1.desc": "Este es el tipo de acción que realiza esta tarjeta. Define lo que hace el paso de automatización. El icono y color indican la categoría.",
  "ctour.step2.title": "Configuración básica",
  "ctour.step2.desc": "Estos son parámetros esenciales obligatorios. Sin ellos, la tarjeta no puede ejecutarse. Mantén la configuración mínima para flujos simples.",
  "ctour.step3.title": "Campos de entrada",
  "ctour.step3.desc": "Este es un parámetro obligatorio. Debe ser válido para que la ejecución proceda. Algunos campos admiten variables o valores dinámicos.",
  "ctour.step4.title": "Configuración de retraso",
  "ctour.step4.desc": "El retraso controla cuándo se ejecuta la acción. Ayuda a simular comportamiento natural y es útil para el control de temporización.",
  "ctour.step5.title": "Lógica de reintentos",
  "ctour.step5.desc": "El reintento define cuántas veces el sistema reintenta en caso de fallo. Previene la interrupción del flujo. Más reintentos pueden aumentar el tiempo de ejecución.",
  "ctour.step6.title": "Modo avanzado",
  "ctour.step6.desc": "Habilita configuración extendida incluyendo parámetros técnicos ocultos. Recomendado solo para usuarios experimentados que necesitan control detallado.",
  "ctour.step7.title": "Comportamiento de ejecución",
  "ctour.step7.desc": "Define si la acción se ejecuta secuencialmente, en paralelo o condicionalmente. Afecta la lógica general y el rendimiento del flujo.",
  "ctour.step8.title": "Guardar cambios",
  "ctour.step8.desc": "Los cambios se aplican automáticamente al configurar. Siempre confirma tus ajustes antes de ejecutar el flujo de trabajo.",
  "onboarding.welcome": "¡Bienvenido a Cetra!",
  "onboarding.clickBuilder": "¡Comencemos! Haz clic en el elemento resaltado Constructor de flujos en la barra lateral para crear tu primera automatización.",
  "onboarding.builderPhase": "¡Genial! Ahora explora el lienzo del constructor. Sigue el recorrido guiado para aprender lo básico.",
  "onboarding.cardPhase": "¡Casi listo! Haz clic en cualquier tarjeta para ver el panel de configuración y completar el recorrido.",
  "onboarding.complete": "¡Listo! Ahora sabes cómo crear y configurar flujos de trabajo."
}
