{
  "nav.dashboard": "Tableau de bord",
  "nav.workflowBuilder": "Constructeur de flux",
  "nav.subscription": "Abonnement",
  "nav.referrals": "Parrainages",
  "nav.settings": "Paramètres",
  "nav.accountGroups": "Groupes de comptes",
  "nav.logOut": "Déconnexion",
  "dashboard.title": "Tableau de bord",
  "dashboard.subtitle": "Aperçu de votre activité d'automatisation",
  "dashboard.agentStatus": "Statut de l'agent",
  "dashboard.online": "En ligne",
  "dashboard.efficiency": "Efficacité",
  "dashboard.totalRuns": "Exécutions totales",
  "dashboard.totalAccounts": "Comptes totaux",
  "dashboard.successful": "Réussis",
  "dashboard.failed": "Échoués",
  "dashboard.automationActivity": "Activité d'automatisation",
  "dashboard.runsAndEfficiency": "Exécutions et efficacité",
  "dashboard.last7days": "7 derniers jours",
  "dashboard.last30days": "30 derniers jours",
  "dashboard.recentActivity": "Activité récente",
  "dashboard.latestEvents": "Derniers événements sur tous les comptes",
  "dashboard.batchExecutions": "Exécutions par lots",
  "dashboard.groupsSubtitle": "Groupes sur tous les flux",
  "dashboard.all": "Tous",
  "dashboard.success": "Succès",
  "dashboard.partial": "Partiel",
  "dashboard.noGroupsMatch": "Aucun groupe ne correspond à ce filtre.",
  "dashboard.accounts": "comptes",
  "dashboard.ok": "ok",
  "dashboard.err": "err",
  "dashboard.wait": "att",
  "dashboard.retryGroup": "Réessayer le groupe",
  "dashboard.retryAccount": "Réessayer",
  "dashboard.failedAccounts": "Comptes échoués",
  "dashboard.pending": "En attente",
  "dashboard.allCompleted": "Les {count} comptes ont été complétés avec succès.",
  "dashboard.noAccountsInGroup": "Aucun compte dans ce groupe pour le moment.",
  "dashboard.recentExecutions": "Exécutions Récentes",
  "dashboard.step": "Étape",
  "workflow.title": "Constructeur de flux",
  "workflow.save": "Enregistrer",
  "workflow.simulate": "Simuler",
  "workflow.stopSim": "Arrêter",
  "workflow.export": "Exporter",
  "workflow.import": "Importer",
  "workflow.clear": "Effacer",
  "workflow.undo": "Annuler",
  "workflow.redo": "Rétablir",
  "workflow.zoomIn": "Zoom avant",
  "workflow.zoomOut": "Zoom arrière",
  "workflow.nodeLibrary": "Bibliothèque de nœuds",
  "workflow.dragToAdd": "Glissez pour ajouter",
  "workflow.nodeConfig": "Configuration du nœud",
  "workflow.selectNode": "Sélectionnez un nœud à configurer",
  "workflow.delete": "Supprimer",
  "workflow.type": "Type",
  "workflow.label": "Étiquette",
  "workflow.interval": "Intervalle",
  "workflow.duration": "Durée (jours)",
  "workflow.splitPercentage": "Pourcentage",
  "workflow.splitCount": "Nombre",
  "workflow.executionMode": "Mode d'exécution",
  "workflow.sequential": "Séquentiel",
  "workflow.parallel": "Parallèle",
  "workflow.randomize": "Ordre aléatoire",
  "workflow.targetGroup": "Groupe cible",
  "workflow.allAccounts": "Tous les comptes",
  "workflow.selectGroup": "Sélectionner un groupe...",
  "workflow.noNodes": "Aucun nœud",
  "workflow.dropHere": "Glissez des nœuds depuis la bibliothèque",
  "workflow.advancedMode": "Mode Avancé",
  "workflow.basicSettings": "Paramètres de Base",
  "workflow.timingIntervals": "Minutage et Intervalles",
  "workflow.executionLogic": "Logique d'Exécution",
  "workflow.accountTargeting": "Ciblage des Comptes",
  "workflow.advancedSettings": "Paramètres Avancés",
  "workflow.websiteTargetUrl": "Site / URL Cible",
  "workflow.accountGroup": "Groupe de Comptes",
  "workflow.executionPriority": "Priorité d'Exécution",
  "workflow.delayBeforeStart": "Délai Avant Démarrage",
  "workflow.delayRandomization": "Plage de Randomisation (sec)",
  "workflow.timeoutBehavior": "Comportement du Délai",
  "workflow.conditionalExecution": "Exécution Conditionnelle",
  "workflow.successConfirmation": "Règle de Confirmation de Succès",
  "workflow.concurrency": "Concurrence",
  "workflow.executionOrder": "Ordre d'Exécution",
  "workflow.errorStrategy": "Stratégie d'Erreur",
  "workflow.retryStrategy": "Stratégie de Réessai",
  "workflow.failSafeStop": "Arrêt de Sécurité",
  "workflow.loggingLevel": "Niveau de Journalisation",
  "workflow.maxAttemptsLimit": "Limite de Tentatives",
  "workflow.riskLevel": "Niveau de Risque",
  "subscription.title": "Abonnement",
  "subscription.subtitle": "Choisissez la période de facturation qui vous convient",
  "subscription.monthly": "Mensuel",
  "subscription.3months": "3 Mois",
  "subscription.yearly": "Annuel",
  "subscription.billedMonthly": "Facturé mensuellement",
  "subscription.billedEvery3Months": "Facturé tous les 3 mois",
  "subscription.billedAnnually": "Facturé annuellement",
  "subscription.saveVsMonthly": "Économisez {percent}% vs mensuel",
  "subscription.perMonth": "mois",
  "subscription.currentPlan": "Plan actuel",
  "subscription.status": "Statut",
  "subscription.active": "Actif",
  "subscription.freeTrial": "Essai gratuit",
  "subscription.freeMode": "Vous êtes en mode gratuit",
  "subscription.freeModeSub": "Fonctionnalités limitées. Débloquez toute la puissance de l'automatisation.",
  "subscription.unlockFull": "Débloquer l'automatisation",
  "subscription.trialEnds": "L'essai se termine dans",
  "subscription.days": "jours",
  "subscription.upgradePlan": "Améliorer le plan",
  "subscription.currentPlanBadge": "Plan actuel",
  "subscription.mostPopular": "Le plus populaire",
  "subscription.allPlansUnlimited": "Tous les plans incluent des comptes illimités",
  "subscription.feat.unlimitedAccounts": "Comptes illimités",
  "subscription.feat.highSpeed": "Niveau d'exécution haute vitesse",
  "subscription.feat.priorityQueue": "File prioritaire",
  "subscription.feat.advancedErrors": "Gestion avancée des erreurs",
  "subscription.feat.workflowAnalytics": "Analytique des flux",
  "subscription.feat.aiAssistant": "Assistant IA de flux",
  "subscription.feat.premiumSupport": "Support premium",
  "subscription.why.fasterExec": "Exécution plus rapide",
  "subscription.why.fasterExecDesc": "La file prioritaire garantit une automatisation ultra-rapide",
  "subscription.why.smarterRecovery": "Récupération plus intelligente",
  "subscription.why.smarterRecoveryDesc": "La gestion d'erreurs par IA récupère automatiquement des pannes",
  "subscription.why.aiAssist": "Assistance IA",
  "subscription.why.aiAssistDesc": "Suggestions intelligentes et optimisation des flux",
  "subscription.why.priorityInfra": "Infrastructure prioritaire",
  "subscription.why.priorityInfraDesc": "Ressources dédiées pour une fiabilité maximale",
  "subscription.why.premiumReliability": "Fiabilité premium",
  "subscription.why.premiumReliabilityDesc": "Stabilité de niveau entreprise pour l'automatisation critique",
  "subscription.whyUpgrade": "Pourquoi améliorer ?",
  "subscription.cryptoPayments": "Paiements crypto acceptés",
  "subscription.paymentMethods": "Méthodes de paiement",
  "referrals.title": "Parrainages",
  "referrals.subtitle": "Invitez des amis. Gagnez des crédits.",
  "referrals.creditsTitle": "Que sont les crédits ?",
  "referrals.creditsDesc": "Les crédits sont un solde bonus gagné grâce aux parrainages.",
  "referrals.creditsUseIntro": "Vous pouvez utiliser les crédits pour :",
  "referrals.creditUse1": "Payer des abonnements",
  "referrals.creditUse2": "Passer à un plan supérieur",
  "referrals.creditUse3": "Débloquer des fonctionnalités premium",
  "referrals.creditsAutoApply": "Les crédits sont appliqués automatiquement lors du paiement.",
  "referrals.yourLink": "Votre lien de parrainage",
  "referrals.shareLink": "Partagez pour gagner des récompenses",
  "referrals.copied": "Copié",
  "referrals.copy": "Copier",
  "referrals.activeReferrals": "Parrainages actifs",
  "settings.title": "Paramètres",
  "settings.subtitle": "Gérez vos préférences",
  "settings.profile": "Profil",
  "settings.displayName": "Nom",
  "settings.email": "E-mail",
  "settings.saveChanges": "Enregistrer",
  "settings.notifications": "Notifications",
  "settings.emailNotifications": "Notifications par e-mail",
  "settings.emailNotificationsDesc": "Recevoir les mises à jour des flux",
  "settings.workflowAlerts": "Alertes de flux",
  "settings.workflowAlertsDesc": "Notification en cas de succès ou d'échec",
  "settings.marketingEmails": "E-mails marketing",
  "settings.marketingEmailsDesc": "Mises à jour et annonces",
  "settings.security": "Sécurité",
  "settings.changePassword": "Changer le mot de passe",
  "settings.lastPasswordChange": "Dernier changement de mot de passe : Jamais",
  "settings.language": "Langue",
  "settings.languageDesc": "Sélectionnez votre langue préférée",
  "groups.title": "Groupes de comptes",
  "groups.subtitle": "Organisez les comptes en groupes logiques",
  "groups.createGroup": "Créer un groupe",
  "groups.newGroup": "Nouveau groupe",
  "groups.groupName": "Nom du groupe",
  "groups.enterGroupName": "Entrez le nom",
  "groups.create": "Créer",
  "groups.cancel": "Annuler",
  "groups.rename": "Renommer",
  "groups.delete": "Supprimer",
  "groups.deleteConfirm": "Supprimer ce groupe ? Les comptes seront désassignés.",
  "groups.noGroups": "Aucun groupe. Créez-en un pour organiser vos comptes.",
  "groups.accountCount": "{count} comptes",
  "groups.lastActivity": "Dernière activité",
  "groups.activeWorkflows": "Flux actifs",
  "groups.successRate": "Taux de réussite",
  "groups.manageAccounts": "Gérer les comptes",
  "groups.availableAccounts": "Comptes disponibles",
  "groups.groupAccounts": "Comptes du groupe",
  "groups.dragToAssign": "Glissez pour assigner",
  "groups.noAvailable": "Tous les comptes sont assignés.",
  "groups.noAccountsInGroup": "Aucun compte dans ce groupe.",
  "groups.addToGroup": "Ajouter",
  "groups.removeFromGroup": "Retirer",
  "groups.overview": "Aperçu",
  "groups.backToGroups": "Retour aux groupes",
  "groups.totalInGroup": "Total dans le groupe",
  "groups.successfulRuns": "Exécutions réussies",
  "groups.failedRuns": "Exécutions échouées",
  "groups.recentExecutions": "Exécutions récentes",
  "groups.noExecutions": "Aucune exécution pour ce groupe.",
  "groups.status": "Statut",
  "groups.workflow": "Flux",
  "groups.time": "Heure",
  "groups.moveToGroup": "Déplacer vers le groupe",
  "groups.notFound": "Groupe introuvable.",
  "nodeType.wallet": "Action portefeuille",
  "nodeType.delay": "Délai",
  "nodeType.split": "Diviser le groupe",
  "nodeType.condition": "Conditionnel",
  "nodeType.swap": "Échange",
  "nodeType.loop": "Boucle",
  "nodeType.bridge": "Pont",
  "nodeType.notify": "Notification",
  "nodeType.repeat": "Boucle répétitive",
  "nodeType.airdrop": "Réclamation airdrop",
  "nodeType.script": "Script personnalisé",
  "status.success": "Succès",
  "status.partial": "Partiel",
  "status.failed": "Échoué",
  "status.pending": "En attente",
  "status.running": "En cours",
  "common.save": "Enregistrer",
  "common.cancel": "Annuler",
  "common.delete": "Supprimer",
  "common.edit": "Modifier",
  "common.close": "Fermer",
  "common.confirm": "Confirmer",
  "common.search": "Rechercher",
  "common.noResults": "Aucun résultat.",
  "referrals.heroText": "Recevez des récompenses chaque fois que vos filleuls s'abonnent.",
  "referrals.earnPercent": "Vous gagnez 20% de chaque paiement en crédits plateforme",
  "referrals.shareTelegram": "Telegram",
  "referrals.shareX": "X",
  "referrals.shareDiscord": "Discord",
  "referrals.totalEarned": "Total crédits gagnés",
  "referrals.currentLevel": "Niveau actuel",
  "referrals.lifetimeCommission": "Commission à vie %",
  "referrals.yourLevel": "Votre niveau de parrainage",
  "referrals.level1": "Débutant",
  "referrals.level1Req": "1-4 parrainages actifs",
  "referrals.level1Perk": "20% crédits sur paiements",
  "referrals.level2": "Croissance",
  "referrals.level2Req": "5-9 parrainages actifs",
  "referrals.level2Perk1": "30% crédits sur paiements",
  "referrals.level2Perk2": "20% réduction abonnement",
  "referrals.level3": "Partenaire",
  "referrals.level3Req": "10+ parrainages actifs",
  "referrals.level3Perk1": "10% commission à vie",
  "referrals.level3Perk2": "Badge partenaire",
  "referrals.level4": "Ambassadeur",
  "referrals.level4Req": "50+ parrainages actifs",
  "referrals.level4Perk1": "Badge ambassadeur",
  "referrals.level4Perk2": "Récompenses exclusives",
  "referrals.unlocked": "Débloqué",
  "referrals.locked": "Verrouillé",
  "referrals.current": "Actuel",
  "referrals.activity": "Activité de parrainage",
  "referrals.colUserId": "ID utilisateur",
  "referrals.colPlan": "Plan acheté",
  "referrals.colAmount": "Montant du paiement",
  "referrals.colReward": "Votre récompense",
  "referrals.colStatus": "Statut",
  "referrals.statusPending": "En attente",
  "referrals.statusActive": "Actif",
  "referrals.statusExpired": "Expiré",
  "referrals.creditsWallet": "Portefeuille de crédits",
  "referrals.availableCredits": "Crédits disponibles",
  "referrals.lifetimeEarned": "Gains totaux",
  "referrals.creditsUsed": "Crédits utilisés",
  "referrals.applyCredits": "Appliquer crédits à l'abonnement",
  "referrals.creditsTooltip": "Les crédits réduisent automatiquement votre prochain paiement",
  "referrals.achievements": "Succès",
  "referrals.achFirstRef": "Premier parrainage",
  "referrals.achFiveRef": "5 parrainages",
  "referrals.achTopPartner": "Top partenaire",
  "referrals.emptyTitle": "Commencez à inviter des amis pour débloquer des récompenses",
  "referrals.emptyCta": "Copier le lien de parrainage",
  "guide.title": "Guide de Configuration",
  "guide.section.overview": "Contrôles de Base",
  "guide.section.advanced": "Paramètres Avancés",
  "guide.section.timing": "Temporisation et Délais",
  "guide.section.risk": "Indicateurs de Risque",
  "guide.section.simulation": "Mode Simulation",
  "guide.overview.accountGroup": "Groupe de Comptes",
  "guide.overview.accountGroupDesc": "Sélectionnez le groupe de comptes qui exécutera cette action. Les groupes sont gérés sur la page Groupes de Comptes.",
  "guide.overview.urlTarget": "URL / Cible",
  "guide.overview.urlTargetDesc": "L'URL de destination ou l'adresse du contrat avec lequel cette action interagira.",
  "guide.overview.delay": "Délai",
  "guide.overview.delayDesc": "Temps d'attente avant d'exécuter cette action. Aide à éviter la détection et les limites.",
  "guide.overview.onSuccess": "En Cas de Succès",
  "guide.overview.onSuccessDesc": "Ce qui se passe après la réussite — continuer, répéter ou arrêter.",
  "guide.advanced.concurrency": "Concurrence",
  "guide.advanced.concurrencyDesc": "Combien de comptes exécutent cette action simultanément. Plus rapide mais plus risqué.",
  "guide.advanced.interval": "Intervalle",
  "guide.advanced.intervalDesc": "Temps entre chaque lot de comptes. Contrôle le rythme d'exécution.",
  "guide.advanced.jitter": "Gigue",
  "guide.advanced.jitterDesc": "Ajoute une variation aléatoire au temps, rendant les actions plus humaines et naturelles.",
  "guide.advanced.retryLogic": "Logique de Réessai",
  "guide.advanced.retryLogicDesc": "Comment les actions échouées sont réessayées — tentatives, délai et stratégie de recul.",
  "guide.advanced.conditions": "Conditions",
  "guide.advanced.conditionsDesc": "Vérifications préalables : solde minimum, limites de gas et autres exigences.",
  "guide.advanced.errorHandling": "Gestion des Erreurs",
  "guide.advanced.errorHandlingDesc": "Ce qui se passe en cas d'échec — ignorer le compte, réessayer ou arrêter tout le flux.",
  "guide.timing.delays": "Types de Délais",
  "guide.timing.delaysDesc": "Les délais fixes attendent un temps défini. Les aléatoires ajoutent une variation pour un comportement plus naturel.",
  "guide.timing.batching": "Traitement par Lots",
  "guide.timing.batchingDesc": "Les comptes sont traités par lots. La taille du lot est égale à la concurrence, avec des intervalles entre chaque lot.",
  "guide.timing.retries": "Temporisation des Réessais",
  "guide.timing.retriesDesc": "Les comptes échoués attendent avant de réessayer. Le recul exponentiel double le temps à chaque tentative.",
  "guide.risk.safe": "Sûr",
  "guide.risk.safeDesc": "Actions à faible risque comme la lecture de données ou la vérification de soldes. Aucun risque pour les fonds.",
  "guide.risk.medium": "Moyen",
  "guide.risk.mediumDesc": "Actions à risque modéré comme les approbations de tokens ou les échanges sur des protocoles testés.",
  "guide.risk.risky": "Risqué",
  "guide.risk.riskyDesc": "Actions à haut risque impliquant des contrats non testés ou de gros mouvements de fonds. À utiliser avec prudence.",
  "guide.simulation.preview": "Mode Aperçu",
  "guide.simulation.previewDesc": "Simulez l'ensemble du flux sans exécuter de vraies transactions. Voyez les temps estimés et le flux de comptes.",
  "guide.simulation.howTo": "Comment Simuler",
  "guide.simulation.howToDesc": "Cliquez sur le bouton de lecture sur n'importe quelle carte ou utilisez le bouton de simulation de la barre d'outils.",
  "settings.nav.account": "Compte",
  "settings.nav.interface": "Interface",
  "settings.nav.execution": "Exécution",
  "settings.nav.security": "Sécurité",
  "settings.nav.notifications": "Notifications",
  "settings.nav.data": "Données",
  "settings.nav.advanced": "Avancé",
  "settings.emailDesc": "Votre adresse e-mail enregistrée",
  "settings.changePasswordDesc": "Définir un nouveau mot de passe pour votre compte",
  "settings.twoFactor": "Authentification à deux facteurs",
  "settings.twoFactorDesc": "Ajouter une couche de sécurité supplémentaire à votre compte",
  "settings.activeSessions": "Sessions actives",
  "settings.activeSessionsDesc": "Appareils actuellement connectés à votre compte",
  "settings.active": "active",
  "settings.logoutAll": "Se déconnecter partout",
  "settings.logoutAllDesc": "Se déconnecter de tous les appareils et sessions",
  "settings.logoutAllBtn": "Tout déconnecter",
  "settings.timezone": "Fuseau horaire",
  "settings.timezoneDesc": "Définissez votre fuseau horaire préféré pour la planification",
  "settings.timeFormat": "Format de l'heure",
  "settings.timeFormatDesc": "Choisissez l'affichage en format 12 ou 24 heures",
  "settings.compactUI": "Interface compacte",
  "settings.compactUIDesc": "Réduire l'espacement pour une interface plus dense",
  "settings.executionNote": "Ces paramètres affectent l'exécution des flux sur tous vos comptes.",
  "settings.speedProfile": "Profil de vitesse",
  "settings.speedProfileDesc": "Contrôle le délai entre les actions",
  "settings.speedSafe": "Prudent",
  "settings.speedSafeDesc": "Délais maximaux entre les actions",
  "settings.speedBalanced": "Équilibré",
  "settings.speedBalancedDesc": "Délais modérés entre les actions",
  "settings.speedAggressive": "Agressif",
  "settings.speedAggressiveDesc": "Délais minimaux entre les actions",
  "settings.retryStrategy": "Stratégie de réessai",
  "settings.retryStrategyDesc": "Comment les actions échouées sont réessayées",
  "settings.retryCons": "Conservateur",
  "settings.retrySmart": "Intelligent",
  "settings.retryMax": "Maximum",
  "settings.randomization": "Niveau de randomisation",
  "settings.randomizationDesc": "Ajoute une variation aléatoire aux délais et actions",
  "settings.randomLow": "Faible",
  "settings.randomMedium": "Moyen",
  "settings.randomHigh": "Élevé",
  "settings.failureTolerance": "Tolérance aux échecs",
  "settings.failureToleranceDesc": "Comment le système gère les échecs de comptes individuels",
  "settings.failStrict": "Strict",
  "settings.failFlexible": "Flexible",
  "settings.privacyMode": "Mode confidentialité",
  "settings.privacyModeDesc": "Masquer les adresses de portefeuille et les données sensibles dans l'interface",
  "settings.localExecution": "Exécution locale uniquement",
  "settings.localExecutionDesc": "Traiter tous les flux localement sans synchronisation cloud",
  "settings.dataRetention": "Période de rétention des données",
  "settings.dataRetentionDesc": "Durée de conservation des journaux d'exécution",
  "settings.days": "jours",
  "settings.autoLogDeletion": "Suppression automatique des journaux",
  "settings.autoLogDeletionDesc": "Supprimer automatiquement les anciens journaux après la période de rétention",
  "settings.notifErrors": "Alertes d'erreurs",
  "settings.notifErrorsDesc": "Être notifié lorsque les flux rencontrent des erreurs",
  "settings.notifCompletion": "Alertes de finalisation",
  "settings.notifCompletionDesc": "Être notifié lorsque les flux se terminent avec succès",
  "settings.notifBilling": "Alertes de facturation",
  "settings.notifBillingDesc": "Être notifié des événements de facturation et des changements d'abonnement",
  "settings.notifReferrals": "Alertes de parrainage",
  "settings.notifReferralsDesc": "Être notifié lorsque quelqu'un utilise votre lien de parrainage",
  "settings.notifUpdates": "Mises à jour du produit",
  "settings.notifUpdatesDesc": "Être notifié des nouvelles fonctionnalités et mises à jour de la plateforme",
  "settings.channels": "Canaux de notification",
  "settings.channelEmail": "E-mail",
  "settings.channelInApp": "Dans l'application",
  "settings.exportWorkflows": "Exporter les flux",
  "settings.importWorkflows": "Importer les flux",
  "settings.backupSettings": "Sauvegarder les paramètres",
  "settings.resetEnvironment": "Réinitialiser l'environnement",
  "settings.confirmTitle": "Confirmer la réinitialisation",
  "settings.confirmResetDesc": "Cela réinitialisera tous vos paramètres aux valeurs par défaut. Cette action est irréversible.",
  "settings.confirmReset": "Tout réinitialiser",
  "settings.enableAdvanced": "Activer le mode avancé",
  "settings.enableAdvancedDesc": "Débloquer les journaux de débogage, les fonctionnalités expérimentales et les diagnostics",
  "settings.debugLogs": "Journaux de débogage",
  "settings.debugLogsDesc": "Afficher les journaux de débogage détaillés dans la console",
  "settings.experimentalFeatures": "Fonctionnalités expérimentales",
  "settings.experimentalFeaturesDesc": "Activer les fonctionnalités expérimentales qui peuvent être instables",
  "settings.extendedDiagnostics": "Diagnostics étendus",
  "settings.extendedDiagnosticsDesc": "Exécuter des diagnostics étendus sur l'exécution des flux",
  "paywall.title": "Débloquer l'exécution",
  "paywall.description": "Mettez à niveau votre plan pour exécuter de véritables automatisations et dimensionner vos workflows.",
  "paywall.trialExhausted": "Vous avez utilisé vos 3 exécutions d'essai. Mettez à niveau pour continuer.",
  "paywall.trialUsed": "3 exécutions d'essai utilisées",
  "paywall.upgradePlan": "Mettre à niveau",
  "paywall.continueFree": "Continuer en mode gratuit",
  "paywall.bannerText": "Vous êtes sur le plan gratuit — mettez à niveau pour exécuter des automatisations",
  "paywall.upgrade": "Mettre à niveau",
  "paywall.trialRunsLeft": "exécutions d'essai restantes",
  "paywall.feat.multiAccount": "Exécution multi-comptes",
  "paywall.feat.smartRouting": "Routage intelligent",
  "paywall.feat.advancedScheduling": "Planification avancée",
  "paywall.feat.priorityExecution": "Exécution prioritaire",
  "paywall.lockedFeature": "Cette fonctionnalité nécessite un plan payant",
  "paywall.runLocked": "L'exécution est verrouillée sur le plan gratuit",
  "guest.badge": "Invité",
  "guest.badgeDesc": "Non connecté",
  "guest.bannerText": "Vous êtes en mode invité — créez un compte pour sauvegarder votre travail",
  "guest.createAccount": "Créer un compte",
  "guest.signupTitle": "Créer un compte gratuit",
  "guest.signupDefault": "Sauvegardez vos workflows et accédez-y à tout moment",
  "guest.signupToSave": "Créez un compte pour sauvegarder vos workflows de manière permanente",
  "guest.signupToExport": "Créez un compte pour exporter vos workflows",
  "guest.signupToExecute": "Créez un compte pour exécuter l'automatisation",
  "guest.signUpEmail": "S'inscrire par Email",
  "guest.continueGuest": "Continuer en tant qu'invité",
  "guest.benefit.saveWorkflows": "Sauvegarde permanente des workflows",
  "guest.benefit.cloudBackup": "Sauvegarde cloud et synchronisation",
  "guest.benefit.freeTrialRuns": "3 exécutions d'essai gratuites",
  "guest.exitDashboard": "Quitter",
  "checkout.title": "Complétez votre paiement crypto",
  "checkout.subtitle": "Envoyez le paiement pour activer votre abonnement instantanément.",
  "checkout.backToPlans": "Retour aux plans",
  "checkout.awaitingPayment": "En attente de paiement",
  "checkout.invoiceExpires": "La facture expire dans",
  "checkout.invoiceExpired": "Facture expirée — régénérer le paiement",
  "checkout.regenerate": "Régénérer le paiement",
  "checkout.sendPaymentTo": "Envoyez le paiement à cette adresse",
  "checkout.copied": "Copié !",
  "checkout.evmNetwork": "Réseau compatible EVM",
  "checkout.networkWarning": "Envoyez uniquement des actifs EVM compatibles. Mauvais réseau = fonds perdus.",
  "checkout.confirmTransaction": "Confirmer la transaction",
  "checkout.enterTxHash": "Entrez le hash de transaction",
  "checkout.confirmPayment": "Confirmer le paiement",
  "checkout.checkingBlockchain": "Vérification blockchain…",
  "checkout.paymentDetected": "Paiement détecté",
  "checkout.subscriptionActivated": "Votre abonnement a été activé",
  "checkout.goToDashboard": "Aller au tableau de bord",
  "checkout.txNotFound": "Transaction introuvable. Vérifiez le hash et réessayez.",
  "checkout.morePaymentMethods": "Autres méthodes de paiement",
  "checkout.comingSoon": "Bientôt disponible",
  "checkout.securityFooter": "Les paiements sont vérifiés on-chain. Cetra ne stocke jamais vos clés privées.",
  "checkout.duration.1month": "1 mois",
  "checkout.duration.3months": "3 mois",
  "checkout.duration.12months": "12 mois",

  "tmpl.chooseCategory": "Choisir une catégorie",
  "tmpl.categorySubtitle": "Sélectionnez une catégorie pour parcourir les modèles de projets préconfigurés.",
  "tmpl.projects": "projets",
  "tmpl.templates": "modèles",
  "tmpl.comingSoon": "Bientôt disponible",
  "tmpl.useTemplate": "Utiliser le modèle",
  "tmpl.blankWorkflow": "Flux vide",
  "tmpl.blankDesc": "Commencez avec un canevas vide et construisez à partir de zéro.",
  "tmpl.saveAsTemplate": "Enregistrer comme modèle",
  "tmpl.custom": "Mes modèles",
  "tmpl.customDesc": "Vos modèles de flux personnalisés enregistrés.",
  "tmpl.customSaved": "Modèle de flux personnalisé enregistré.",

  "tmpl.cat.social": "Activité sociale",
  "tmpl.cat.socialDesc": "Automatisez l'engagement social, l'accomplissement de quêtes et le farming communautaire sur plusieurs plateformes.",
  "tmpl.cat.testnet": "Testnet",
  "tmpl.cat.testnetDesc": "Automatisez les interactions testnet incluant les swaps, bridges, mints et réclamations de faucets.",
  "tmpl.cat.airdrop": "Airdrop",
  "tmpl.cat.airdropDesc": "Suivez et réclamez automatiquement les airdrops sur plusieurs chaînes.",
  "tmpl.cat.farming": "Farming",
  "tmpl.cat.farmingDesc": "Stratégies d'automatisation du farming de rendement et de fourniture de liquidité.",

  "tmpl.type.pointsFarming": "Farming de points",
  "tmpl.type.questCompletion": "Accomplissement de quêtes",
  "tmpl.type.credentialFarming": "Farming de credentials",
  "tmpl.type.socialEngagement": "Engagement social",
  "tmpl.type.roleFarming": "Farming de rôles",
  "tmpl.type.testnetActivity": "Activité testnet",
  "tmpl.type.crossChain": "Cross-Chain",
  "tmpl.type.l2Activity": "Activité L2",
  "tmpl.type.ecosystemTasks": "Tâches écosystème",
  "tmpl.type.custom": "Personnalisé",

  "tmpl.konnex.desc": "Gagnez des points Konnex en accomplissant des tâches sociales : like, commentaire, repost, follow, rejoindre Discord, check-in quotidien et parrainages.",
  "tmpl.zealy.desc": "Automatisez l'accomplissement des quêtes Zealy et le farming de XP avec un suivi quotidien des quêtes.",
  "tmpl.galxe.desc": "Réclamez les credentials Galxe et les OAT en liant vos profils et en accomplissant des tâches on-chain.",
  "tmpl.twitter.desc": "Automatisez l'engagement Twitter : likes, retweets et follows avec des délais similaires à ceux d'un humain.",
  "tmpl.discord.desc": "Farmez des rôles Discord via l'adhésion automatique aux serveurs, la vérification de portefeuille et l'activité.",
  "tmpl.pharos.desc": "Complétez les activités du testnet Pharos : réclamations de faucet, swaps de tokens, bridging, mints de NFT et transactions quotidiennes.",
  "tmpl.layerzero.desc": "Automatisez les transactions de bridge cross-chain LayerZero sur plusieurs testnets.",
  "tmpl.starknet.desc": "Générez de l'activité on-chain sur Starknet : swaps sur DEX, fourniture de liquidité et mints de NFT.",
  "tmpl.scroll.desc": "Interagissez avec le testnet Scroll : bridge, swap de tokens et génération de volume de transactions quotidien.",
  "tmpl.base.desc": "Complétez les tâches de l'écosystème Base : bridge, trading sur Aerodrome et mint de NFTs Base.",
  "theme.light": "Mode clair",
  "theme.dark": "Mode sombre",
  "theme.default": "par défaut",

  "tour.step1.title": "Navigation",
  "tour.step1.desc": "Voici votre navigation principale. Accédez à toutes les sections — workflows, groupes, abonnement et plus.",
  "tour.step2.title": "Constructeur de workflows",
  "tour.step2.desc": "Créez des automatisations avec le constructeur visuel. Choisissez des modèles ou créez depuis zéro.",
  "tour.step3.title": "Abonnement",
  "tour.step3.desc": "Gérez votre plan, consultez l'utilisation et améliorez votre forfait pour plus de comptes et fonctionnalités.",
  "tour.step4.title": "Parrainages",
  "tour.step4.desc": "Invitez des amis et gagnez des crédits. Chaque parrainage vous donne des crédits d'automatisation bonus.",
  "tour.step5.title": "Paramètres",
  "tour.step5.desc": "Personnalisez votre expérience — langue, thème, préférences d'exécution, sécurité et plus.",
  "tour.next": "Suivant",
  "tour.back": "Retour",
  "tour.skip": "Passer",
  "tour.finish": "Terminer",
  "settings.replayTour": "Visite guidée",
  "settings.replayTourDesc": "Rejouer la visite guidée du tableau de bord",
  "settings.replayTourBtn": "Rejouer",

  "btour.replay": "Guide",
  "btour.step1.title": "Canevas de workflow",
  "btour.step1.desc": "Voici votre canevas de travail. Glissez des cartes d'action ici pour créer votre automatisation. Déplacez les cartes, zoomez et naviguez librement.",
  "btour.step2.title": "Bibliothèque de cartes",
  "btour.step2.desc": "Ce panneau contient toutes les cartes d'action disponibles. Glissez une carte sur le canevas pour ajouter une nouvelle étape d'automatisation.",
  "btour.step3.title": "Carte d'action",
  "btour.step3.desc": "Chaque carte représente une étape d'automatisation. Configurez-la, déplacez-la et connectez-la aux autres cartes via les ports latéraux.",
  "btour.step4.title": "Connexions",
  "btour.step4.desc": "Les connexions définissent l'ordre d'exécution. Glissez d'un port de sortie vers un port d'entrée pour créer un flux. Le workflow s'exécute de haut en bas.",
  "btour.step5.title": "Panneau de paramètres",
  "btour.step5.desc": "Tous les paramètres de la carte apparaissent ici lorsqu'elle est sélectionnée. Les paramètres de base sont visibles par défaut, regroupés par catégories.",
  "btour.step6.title": "Mode avancé",
  "btour.step6.desc": "Activez le Mode Avancé pour accéder aux paramètres étendus : logique d'exécution, ciblage de comptes et gestion des erreurs. Recommandé pour les utilisateurs expérimentés.",
  "btour.step7.title": "Modèle de workflow",
  "btour.step7.desc": "Le nom du workflow est affiché ici. S'il a été créé à partir d'un modèle, vous pouvez modifier n'importe quel bloc et sauvegarder comme modèle personnalisé.",
  "btour.step8.title": "Sauvegarder et exécuter",
  "btour.step8.desc": "Sauvegardez votre workflow pour conserver votre progression. Utilisez le bouton Exécuter pour lancer l'automatisation sur vos comptes.",

  "ctour.help": "Guide des paramètres de carte",
  "ctour.step1.title": "Type d'action",
  "ctour.step1.desc": "C'est le type d'action que cette carte effectue. Il définit ce que fait l'étape d'automatisation. L'icône et la couleur indiquent la catégorie.",
  "ctour.step2.title": "Paramètres de base",
  "ctour.step2.desc": "Ce sont les paramètres essentiels obligatoires. Sans eux, la carte ne peut pas s'exécuter. Gardez la configuration minimale pour les workflows simples.",
  "ctour.step3.title": "Champs de saisie",
  "ctour.step3.desc": "C'est un paramètre obligatoire. Il doit être valide pour que l'exécution procède. Certains champs acceptent des variables ou valeurs dynamiques.",
  "ctour.step4.title": "Paramètres de délai",
  "ctour.step4.desc": "Le délai contrôle quand l'action s'exécute. Il aide à simuler un comportement naturel et est utile pour le contrôle du timing.",
  "ctour.step5.title": "Logique de réessai",
  "ctour.step5.desc": "Le réessai définit combien de fois le système retente en cas d'échec. Cela empêche l'interruption du workflow. Plus de réessais peut augmenter le temps d'exécution.",
  "ctour.step6.title": "Mode avancé",
  "ctour.step6.desc": "Active la configuration étendue incluant les paramètres techniques cachés. Recommandé uniquement pour les utilisateurs expérimentés nécessitant un contrôle précis.",
  "ctour.step7.title": "Comportement d'exécution",
  "ctour.step7.desc": "Définit si l'action s'exécute séquentiellement, en parallèle ou conditionnellement. Cela affecte la logique globale et les performances du workflow.",
  "ctour.step8.title": "Sauvegarder les modifications",
  "ctour.step8.desc": "Les modifications sont appliquées automatiquement lors de la configuration. Vérifiez toujours vos paramètres avant de lancer le workflow.",
  "onboarding.welcome": "Bienvenue sur Cetra !",
  "onboarding.clickBuilder": "Commençons ! Cliquez sur l'élément surligné Constructeur de flux dans la barre latérale pour créer votre première automatisation.",
  "onboarding.builderPhase": "Super ! Explorez maintenant le canevas du constructeur. Suivez le guide pour apprendre les bases.",
  "onboarding.cardPhase": "Presque terminé ! Cliquez sur n'importe quelle carte pour voir le panneau de paramètres et terminer le parcours.",
  "onboarding.complete": "C'est prêt ! Vous savez maintenant créer et configurer des workflows."
}
