{
  "nav.dashboard": "대시보드",
  "nav.workflowBuilder": "워크플로우 빌더",
  "nav.subscription": "구독",
  "nav.referrals": "추천",
  "nav.settings": "설정",
  "nav.accountGroups": "계정 그룹",
  "nav.logOut": "로그아웃",
  "dashboard.title": "대시보드",
  "dashboard.subtitle": "자동화 활동 개요",
  "dashboard.agentStatus": "에이전트 상태",
  "dashboard.online": "온라인",
  "dashboard.efficiency": "효율성",
  "dashboard.totalRuns": "총 실행",
  "dashboard.totalAccounts": "총 계정",
  "dashboard.successful": "성공",
  "dashboard.failed": "실패",
  "dashboard.automationActivity": "자동화 활동",
  "dashboard.runsAndEfficiency": "실행 및 효율성",
  "dashboard.last7days": "최근 7일",
  "dashboard.last30days": "최근 30일",
  "dashboard.recentActivity": "최근 활동",
  "dashboard.latestEvents": "모든 계정의 최근 이벤트",
  "dashboard.batchExecutions": "배치 실행",
  "dashboard.groupsSubtitle": "모든 워크플로우의 그룹",
  "dashboard.all": "전체",
  "dashboard.success": "성공",
  "dashboard.partial": "부분",
  "dashboard.noGroupsMatch": "필터와 일치하는 그룹이 없습니다.",
  "dashboard.accounts": "계정",
  "dashboard.ok": "성공",
  "dashboard.err": "오류",
  "dashboard.wait": "대기",
  "dashboard.retryGroup": "그룹 재시도",
  "dashboard.retryAccount": "재시도",
  "dashboard.failedAccounts": "실패한 계정",
  "dashboard.pending": "대기 중",
  "dashboard.allCompleted": "모든 {count}개 계정이 성공적으로 완료되었습니다.",
  "dashboard.noAccountsInGroup": "이 그룹에 아직 계정이 없습니다.",
  "dashboard.recentExecutions": "최근 실행",
  "dashboard.step": "단계",
  "workflow.title": "워크플로우 빌더",
  "workflow.save": "저장",
  "workflow.simulate": "시뮬레이션",
  "workflow.stopSim": "정지",
  "workflow.export": "내보내기",
  "workflow.import": "가져오기",
  "workflow.clear": "지우기",
  "workflow.undo": "실행 취소",
  "workflow.redo": "다시 실행",
  "workflow.zoomIn": "확대",
  "workflow.zoomOut": "축소",
  "workflow.nodeLibrary": "노드 라이브러리",
  "workflow.dragToAdd": "드래그하여 추가",
  "workflow.nodeConfig": "노드 설정",
  "workflow.selectNode": "설정할 노드를 선택하세요",
  "workflow.delete": "삭제",
  "workflow.type": "유형",
  "workflow.label": "레이블",
  "workflow.interval": "간격",
  "workflow.duration": "기간 (일)",
  "workflow.splitPercentage": "분할 %",
  "workflow.splitCount": "분할 수",
  "workflow.executionMode": "실행 모드",
  "workflow.sequential": "순차적",
  "workflow.parallel": "병렬",
  "workflow.randomize": "무작위 순서",
  "workflow.targetGroup": "대상 그룹",
  "workflow.allAccounts": "모든 계정",
  "workflow.selectGroup": "그룹 선택...",
  "workflow.noNodes": "노드 없음",
  "workflow.dropHere": "라이브러리에서 노드를 드래그하세요",
  "workflow.advancedMode": "고급 모드",
  "workflow.basicSettings": "기본 설정",
  "workflow.timingIntervals": "타이밍 및 간격",
  "workflow.executionLogic": "실행 로직",
  "workflow.accountTargeting": "계정 타겟팅",
  "workflow.advancedSettings": "고급 설정",
  "workflow.websiteTargetUrl": "웹사이트 / 대상 URL",
  "workflow.accountGroup": "계정 그룹",
  "workflow.executionPriority": "실행 우선순위",
  "workflow.delayBeforeStart": "시작 전 지연",
  "workflow.delayRandomization": "지연 무작위화 범위 (초)",
  "workflow.timeoutBehavior": "타임아웃 동작",
  "workflow.conditionalExecution": "조건부 실행",
  "workflow.successConfirmation": "성공 확인 규칙",
  "workflow.concurrency": "동시 실행",
  "workflow.executionOrder": "실행 순서",
  "workflow.errorStrategy": "오류 전략",
  "workflow.retryStrategy": "재시도 전략",
  "workflow.failSafeStop": "안전 정지",
  "workflow.loggingLevel": "로깅 레벨",
  "workflow.maxAttemptsLimit": "최대 시도 횟수",
  "workflow.riskLevel": "위험 수준",
  "subscription.title": "구독",
  "subscription.subtitle": "가장 적합한 결제 기간을 선택하세요",
  "subscription.monthly": "월간",
  "subscription.3months": "3개월",
  "subscription.yearly": "연간",
  "subscription.billedMonthly": "월별 결제",
  "subscription.billedEvery3Months": "3개월마다 결제",
  "subscription.billedAnnually": "연간 결제",
  "subscription.saveVsMonthly": "월간 대비 {percent}% 절약",
  "subscription.perMonth": "월",
  "subscription.currentPlan": "현재 플랜",
  "subscription.status": "상태",
  "subscription.active": "활성",
  "subscription.freeTrial": "무료 체험",
  "subscription.freeMode": "무료 모드입니다",
  "subscription.freeModeSub": "제한된 기능입니다. 전체 자동화를 잠금 해제하세요.",
  "subscription.unlockFull": "전체 자동화 잠금 해제",
  "subscription.trialEnds": "체험 종료까지",
  "subscription.days": "일",
  "subscription.upgradePlan": "플랜 업그레이드",
  "subscription.currentPlanBadge": "현재 플랜",
  "subscription.mostPopular": "가장 인기",
  "subscription.allPlansUnlimited": "모든 플랜에 무제한 계정 포함",
  "subscription.feat.unlimitedAccounts": "무제한 계정",
  "subscription.feat.highSpeed": "고속 실행 등급",
  "subscription.feat.priorityQueue": "우선 대기열",
  "subscription.feat.advancedErrors": "고급 오류 처리",
  "subscription.feat.workflowAnalytics": "워크플로우 분석",
  "subscription.feat.aiAssistant": "AI 워크플로우 어시스턴트",
  "subscription.feat.premiumSupport": "프리미엄 지원",
  "subscription.why.fasterExec": "더 빠른 실행",
  "subscription.why.fasterExecDesc": "우선 대기열이 번개같은 자동화를 보장합니다",
  "subscription.why.smarterRecovery": "스마트 복구",
  "subscription.why.smarterRecoveryDesc": "AI 오류 처리가 장애에서 자동으로 복구합니다",
  "subscription.why.aiAssist": "AI 어시스턴스",
  "subscription.why.aiAssistDesc": "지능형 워크플로우 제안 및 최적화",
  "subscription.why.priorityInfra": "우선 인프라",
  "subscription.why.priorityInfraDesc": "최대 안정성을 위한 전용 리소스",
  "subscription.why.premiumReliability": "프리미엄 안정성",
  "subscription.why.premiumReliabilityDesc": "중요한 자동화를 위한 엔터프라이즈급 안정성",
  "subscription.whyUpgrade": "왜 업그레이드해야 하나요?",
  "subscription.cryptoPayments": "암호화폐 결제 지원",
  "subscription.paymentMethods": "결제 방법",
  "referrals.title": "추천",
  "referrals.subtitle": "친구를 초대하고 크레딧을 받으세요.",
  "referrals.creditsTitle": "크레딧이란?",
  "referrals.creditsDesc": "크레딧은 추천을 통해 적립되는 보너스 잔액입니다.",
  "referrals.creditsUseIntro": "크레딧 사용처:",
  "referrals.creditUse1": "구독 결제",
  "referrals.creditUse2": "플랜 업그레이드",
  "referrals.creditUse3": "프리미엄 기능 잠금 해제",
  "referrals.creditsAutoApply": "크레딧은 결제 시 자동으로 적용됩니다.",
  "referrals.yourLink": "추천 링크",
  "referrals.shareLink": "공유하여 보상 획득",
  "referrals.copied": "복사됨",
  "referrals.copy": "복사",
  "referrals.activeReferrals": "활성 추천",
  "settings.title": "설정",
  "settings.subtitle": "계정 환경설정 관리",
  "settings.profile": "프로필",
  "settings.displayName": "이름",
  "settings.email": "이메일",
  "settings.saveChanges": "저장",
  "settings.notifications": "알림",
  "settings.emailNotifications": "이메일 알림",
  "settings.emailNotificationsDesc": "워크플로우 업데이트 수신",
  "settings.workflowAlerts": "워크플로우 알림",
  "settings.workflowAlertsDesc": "완료 또는 실패 시 알림",
  "settings.marketingEmails": "마케팅 이메일",
  "settings.marketingEmailsDesc": "업데이트 및 공지",
  "settings.security": "보안",
  "settings.changePassword": "비밀번호 변경",
  "settings.lastPasswordChange": "마지막 비밀번호 변경: 없음",
  "settings.language": "언어",
  "settings.languageDesc": "선호 언어 선택",
  "groups.title": "계정 그룹",
  "groups.subtitle": "계정을 논리적 그룹으로 조직",
  "groups.createGroup": "그룹 생성",
  "groups.newGroup": "새 그룹",
  "groups.groupName": "그룹 이름",
  "groups.enterGroupName": "이름 입력",
  "groups.create": "생성",
  "groups.cancel": "취소",
  "groups.rename": "이름 변경",
  "groups.delete": "삭제",
  "groups.deleteConfirm": "이 그룹을 삭제하시겠습니까? 계정이 해제됩니다.",
  "groups.noGroups": "그룹이 없습니다. 계정을 정리하려면 생성하세요.",
  "groups.accountCount": "{count}개 계정",
  "groups.lastActivity": "최근 활동",
  "groups.activeWorkflows": "활성 워크플로우",
  "groups.successRate": "성공률",
  "groups.manageAccounts": "계정 관리",
  "groups.availableAccounts": "사용 가능한 계정",
  "groups.groupAccounts": "그룹 계정",
  "groups.dragToAssign": "드래그하여 할당",
  "groups.noAvailable": "모든 계정이 할당되었습니다.",
  "groups.noAccountsInGroup": "그룹에 계정이 없습니다.",
  "groups.addToGroup": "추가",
  "groups.removeFromGroup": "제거",
  "groups.overview": "개요",
  "groups.backToGroups": "그룹으로 돌아가기",
  "groups.totalInGroup": "그룹 총계",
  "groups.successfulRuns": "성공한 실행",
  "groups.failedRuns": "실패한 실행",
  "groups.recentExecutions": "최근 실행",
  "groups.noExecutions": "이 그룹의 실행이 없습니다.",
  "groups.status": "상태",
  "groups.workflow": "워크플로우",
  "groups.time": "시간",
  "groups.moveToGroup": "그룹으로 이동",
  "groups.notFound": "그룹을 찾을 수 없습니다.",
  "nodeType.wallet": "지갑 작업",
  "nodeType.delay": "지연",
  "nodeType.split": "그룹 분할",
  "nodeType.condition": "조건",
  "nodeType.swap": "스왓",
  "nodeType.loop": "루프",
  "nodeType.bridge": "브리지",
  "nodeType.notify": "알림",
  "nodeType.repeat": "반복 루프",
  "nodeType.airdrop": "에어드롭 클레임",
  "nodeType.script": "커스텀 스크립트",
  "status.success": "성공",
  "status.partial": "부분",
  "status.failed": "실패",
  "status.pending": "대기",
  "status.running": "실행 중",
  "common.save": "저장",
  "common.cancel": "취소",
  "common.delete": "삭제",
  "common.edit": "편집",
  "common.close": "닫기",
  "common.confirm": "확인",
  "common.search": "검색",
  "common.noResults": "결과가 없습니다.",
  "referrals.heroText": "추천인이 구독할 때마다 보상을 받으세요.",
  "referrals.earnPercent": "모든 결제의 20%를 플랫폼 크레딧으로 적립",
  "referrals.shareTelegram": "Telegram",
  "referrals.shareX": "X",
  "referrals.shareDiscord": "Discord",
  "referrals.totalEarned": "총 적립 크레딧",
  "referrals.currentLevel": "현재 레벨",
  "referrals.lifetimeCommission": "평생 커미션 %",
  "referrals.yourLevel": "추천 레벨",
  "referrals.level1": "스타터",
  "referrals.level1Req": "1-4 활성 추천",
  "referrals.level1Perk": "결제의 20% 크레딧",
  "referrals.level2": "성장",
  "referrals.level2Req": "5-9 활성 추천",
  "referrals.level2Perk1": "결제의 30% 크레딧",
  "referrals.level2Perk2": "구독 20% 할인",
  "referrals.level3": "파트너",
  "referrals.level3Req": "10+ 활성 추천",
  "referrals.level3Perk1": "10% 평생 커미션",
  "referrals.level3Perk2": "파트너 배지",
  "referrals.level4": "앰배서더",
  "referrals.level4Req": "50+ 활성 추천",
  "referrals.level4Perk1": "앰배서더 배지",
  "referrals.level4Perk2": "독점 보상",
  "referrals.unlocked": "잠금 해제",
  "referrals.locked": "잠김",
  "referrals.current": "현재",
  "referrals.activity": "추천 활동",
  "referrals.colUserId": "사용자 ID",
  "referrals.colPlan": "구매한 플랜",
  "referrals.colAmount": "결제 금액",
  "referrals.colReward": "보상",
  "referrals.colStatus": "상태",
  "referrals.statusPending": "대기 중",
  "referrals.statusActive": "활성",
  "referrals.statusExpired": "만료",
  "referrals.creditsWallet": "크레딧 지갑",
  "referrals.availableCredits": "사용 가능한 크레딧",
  "referrals.lifetimeEarned": "총 누적 적립",
  "referrals.creditsUsed": "사용된 크레딧",
  "referrals.applyCredits": "구독에 크레딧 적용",
  "referrals.creditsTooltip": "크레딧은 다음 결제에서 자동으로 차감됩니다",
  "referrals.achievements": "업적",
  "referrals.achFirstRef": "첫 추천",
  "referrals.achFiveRef": "5명 추천",
  "referrals.achTopPartner": "탑 파트너",
  "referrals.emptyTitle": "보상을 잠금 해제하려면 친구를 초대하세요",
  "referrals.emptyCta": "추천 링크 복사",
  "guide.title": "카드 설정 가이드",
  "guide.section.overview": "기본 설정",
  "guide.section.advanced": "고급 설정",
  "guide.section.timing": "타이밍 및 지연",
  "guide.section.risk": "위험 지표",
  "guide.section.simulation": "시뮬레이션 모드",
  "guide.overview.accountGroup": "계정 그룹",
  "guide.overview.accountGroupDesc": "이 작업을 실행할 계정 그룹을 선택하세요. 그룹은 계정 그룹 페이지에서 관리할 수 있습니다.",
  "guide.overview.urlTarget": "URL / 대상",
  "guide.overview.urlTargetDesc": "이 작업이 상호작용할 대상 URL 또는 컨트랙트 주소입니다.",
  "guide.overview.delay": "지연",
  "guide.overview.delayDesc": "작업 실행 전 대기 시간입니다. 감지 및 속도 제한을 피하는 데 도움됩니다.",
  "guide.overview.onSuccess": "성공 시",
  "guide.overview.onSuccessDesc": "작업이 성공적으로 완료된 후 동작 — 다음으로 진행, 반복 또는 중지.",
  "guide.advanced.concurrency": "동시성",
  "guide.advanced.concurrencyDesc": "동시에 이 작업을 실행하는 계정 수입니다. 값이 높을수록 빠르지만 위험합니다.",
  "guide.advanced.interval": "간격",
  "guide.advanced.intervalDesc": "각 계정 배치 간의 시간입니다. 실행 속도를 제어합니다.",
  "guide.advanced.jitter": "지터",
  "guide.advanced.jitterDesc": "타이밍에 랜덤 변동을 추가하여 동작을 더 자연스럽게 만듭니다.",
  "guide.advanced.retryLogic": "재시도 로직",
  "guide.advanced.retryLogicDesc": "실패한 작업의 재시도 방법 — 시도 횟수, 재시도 간 지연 및 백오프 전략.",
  "guide.advanced.conditions": "조건",
  "guide.advanced.conditionsDesc": "실행 전 사전 검사: 최소 잔액, 가스 가격 제한 및 기타 요구사항.",
  "guide.advanced.errorHandling": "오류 처리",
  "guide.advanced.errorHandlingDesc": "작업 실패 시 동작 — 계정 건너뛰기, 재시도 또는 전체 워크플로우 중지.",
  "guide.timing.delays": "지연 유형",
  "guide.timing.delaysDesc": "고정 지연은 설정된 시간을 대기합니다. 랜덤 지연은 더 자연스러운 동작을 위해 범위 내 변동을 추가합니다.",
  "guide.timing.batching": "배치 처리",
  "guide.timing.batchingDesc": "계정은 배치로 처리됩니다. 배치 크기는 동시성과 같으며, 각 배치 사이에 간격 지연이 있습니다.",
  "guide.timing.retries": "재시도 타이밍",
  "guide.timing.retriesDesc": "실패한 계정은 재시도 전에 대기합니다. 지수 백오프는 각 시도마다 대기 시간을 두 배로 늘립니다.",
  "guide.risk.safe": "안전",
  "guide.risk.safeDesc": "데이터 읽기 또는 잔액 확인과 같은 저위험 작업. 자금 위험 없음.",
  "guide.risk.medium": "중간",
  "guide.risk.mediumDesc": "검증된 프로토콜에서의 토큰 승인 또는 스왑과 같은 중간 위험 작업.",
  "guide.risk.risky": "위험",
  "guide.risk.riskyDesc": "미검증 컨트랙트 또는 대규모 자금 이동을 포함하는 고위험 작업. 주의하여 사용하세요.",
  "guide.simulation.preview": "미리보기 모드",
  "guide.simulation.previewDesc": "실제 트랜잭션 없이 전체 워크플로우를 시뮬레이션합니다. 예상 시간과 계정 흐름을 확인하세요.",
  "guide.simulation.howTo": "시뮬레이션 방법",
  "guide.simulation.howToDesc": "카드의 재생 버튼을 클릭하거나 상단 도구 모음의 시뮬레이션 버튼을 사용하세요.",
  "settings.nav.account": "계정",
  "settings.nav.interface": "인터페이스",
  "settings.nav.execution": "실행",
  "settings.nav.security": "보안",
  "settings.nav.notifications": "알림",
  "settings.nav.data": "데이터",
  "settings.nav.advanced": "고급",
  "settings.emailDesc": "등록된 이메일 주소입니다",
  "settings.changePasswordDesc": "계정의 새 비밀번호를 설정합니다",
  "settings.twoFactor": "2단계 인증",
  "settings.twoFactorDesc": "계정에 추가 보안 계층을 적용합니다",
  "settings.activeSessions": "활성 세션",
  "settings.activeSessionsDesc": "현재 계정에 로그인된 기기",
  "settings.active": "활성",
  "settings.logoutAll": "모든 곳에서 로그아웃",
  "settings.logoutAllDesc": "모든 기기 및 세션에서 로그아웃합니다",
  "settings.logoutAllBtn": "전체 로그아웃",
  "settings.timezone": "시간대",
  "settings.timezoneDesc": "예약에 사용할 시간대를 설정합니다",
  "settings.timeFormat": "시간 형식",
  "settings.timeFormatDesc": "12시간 또는 24시간 형식을 선택합니다",
  "settings.compactUI": "컴팩트 UI",
  "settings.compactUIDesc": "간격을 줄여 더 밀집된 인터페이스로 표시합니다",
  "settings.executionNote": "이 설정은 모든 계정에서 워크플로우가 실행되는 방식에 영향을 줍니다.",
  "settings.speedProfile": "속도 프로필",
  "settings.speedProfileDesc": "작업 간 지연 시간을 제어합니다",
  "settings.speedSafe": "안전",
  "settings.speedSafeDesc": "작업 간 최대 지연",
  "settings.speedBalanced": "균형",
  "settings.speedBalancedDesc": "작업 간 적절한 지연",
  "settings.speedAggressive": "적극적",
  "settings.speedAggressiveDesc": "작업 간 최소 지연",
  "settings.retryStrategy": "재시도 전략",
  "settings.retryStrategyDesc": "실패한 작업의 재시도 방식",
  "settings.retryCons": "보수적",
  "settings.retrySmart": "스마트",
  "settings.retryMax": "최대",
  "settings.randomization": "랜덤화 수준",
  "settings.randomizationDesc": "타이밍과 작업에 무작위 변동을 추가합니다",
  "settings.randomLow": "낮음",
  "settings.randomMedium": "중간",
  "settings.randomHigh": "높음",
  "settings.failureTolerance": "실패 허용 수준",
  "settings.failureToleranceDesc": "개별 계정 실패를 시스템이 처리하는 방식",
  "settings.failStrict": "엄격",
  "settings.failFlexible": "유연",
  "settings.privacyMode": "개인정보 보호 모드",
  "settings.privacyModeDesc": "UI에서 지갑 주소 및 민감한 데이터를 숨깁니다",
  "settings.localExecution": "로컬 실행만",
  "settings.localExecutionDesc": "클라우드 동기화 없이 모든 워크플로우를 로컬에서 처리합니다",
  "settings.dataRetention": "데이터 보존 기간",
  "settings.dataRetentionDesc": "실행 로그가 저장되는 기간",
  "settings.days": "일",
  "settings.autoLogDeletion": "로그 자동 삭제",
  "settings.autoLogDeletionDesc": "보존 기간 후 오래된 로그를 자동으로 삭제합니다",
  "settings.notifErrors": "오류 알림",
  "settings.notifErrorsDesc": "워크플로우에서 오류가 발생하면 알림을 받습니다",
  "settings.notifCompletion": "완료 알림",
  "settings.notifCompletionDesc": "워크플로우가 성공적으로 완료되면 알림을 받습니다",
  "settings.notifBilling": "결제 알림",
  "settings.notifBillingDesc": "결제 이벤트 및 구독 변경에 대한 알림을 받습니다",
  "settings.notifReferrals": "추천 알림",
  "settings.notifReferralsDesc": "누군가 추천 링크를 사용하면 알림을 받습니다",
  "settings.notifUpdates": "제품 업데이트",
  "settings.notifUpdatesDesc": "새 기능 및 플랫폼 업데이트에 대한 알림을 받습니다",
  "settings.channels": "알림 채널",
  "settings.channelEmail": "이메일",
  "settings.channelInApp": "인앱",
  "settings.exportWorkflows": "워크플로우 내보내기",
  "settings.importWorkflows": "워크플로우 가져오기",
  "settings.backupSettings": "설정 백업",
  "settings.resetEnvironment": "환경 초기화",
  "settings.confirmTitle": "초기화 확인",
  "settings.confirmResetDesc": "모든 설정이 기본값으로 초기화됩니다. 이 작업은 되돌릴 수 없습니다.",
  "settings.confirmReset": "전체 초기화",
  "settings.enableAdvanced": "고급 모드 활성화",
  "settings.enableAdvancedDesc": "디버그 로그, 실험적 기능 및 진단 도구를 잠금 해제합니다",
  "settings.debugLogs": "디버그 로그",
  "settings.debugLogsDesc": "콘솔에 상세 디버그 로그를 표시합니다",
  "settings.experimentalFeatures": "실험적 기능",
  "settings.experimentalFeaturesDesc": "불안정할 수 있는 실험적 기능을 활성화합니다",
  "settings.extendedDiagnostics": "확장 진단",
  "settings.extendedDiagnosticsDesc": "워크플로우 실행에 대한 확장 진단을 수행합니다",
  "paywall.title": "실행 잠금 해제",
  "paywall.description": "플랜을 업그레이드하여 실제 자동화를 실행하고 워크플로를 확장하세요.",
  "paywall.trialExhausted": "3회 무료 체험 실행을 모두 사용했습니다. 계속하려면 업그레이드하세요.",
  "paywall.trialUsed": "3회 무료 체험 실행 모두 사용됨",
  "paywall.upgradePlan": "플랜 업그레이드",
  "paywall.continueFree": "무료 모드로 계속",
  "paywall.bannerText": "무료 플랜 사용 중 — 자동화를 실행하려면 업그레이드하세요",
  "paywall.upgrade": "업그레이드",
  "paywall.trialRunsLeft": "체험 실행 남음",
  "paywall.feat.multiAccount": "다중 계정 실행",
  "paywall.feat.smartRouting": "스마트 라우팅",
  "paywall.feat.advancedScheduling": "고급 스케줄링",
  "paywall.feat.priorityExecution": "우선순위 실행",
  "paywall.lockedFeature": "이 기능은 유료 플랜이 필요합니다",
  "paywall.runLocked": "무료 플랜에서는 실행이 잠겨 있습니다",
  "guest.badge": "게스트",
  "guest.badgeDesc": "로그인되지 않음",
  "guest.bannerText": "게스트 모드입니다 — 작업을 저장하려면 계정을 만드세요",
  "guest.createAccount": "계정 만들기",
  "guest.signupTitle": "무료 계정 만들기",
  "guest.signupDefault": "워크플로우를 저장하고 언제든지 접근하세요",
  "guest.signupToSave": "워크플로우를 영구적으로 저장하려면 계정을 만드세요",
  "guest.signupToExport": "워크플로우를 내보내려면 계정을 만드세요",
  "guest.signupToExecute": "자동화를 실행하려면 계정을 만드세요",
  "guest.signUpEmail": "이메일로 가입",
  "guest.continueGuest": "게스트로 계속",
  "guest.benefit.saveWorkflows": "워크플로우 영구 저장",
  "guest.benefit.cloudBackup": "클라우드 백업 및 동기화",
  "guest.benefit.freeTrialRuns": "3회 무료 체험 실행",
  "guest.exitDashboard": "나가기",
  "checkout.title": "암호화폐 결제 완료",
  "checkout.subtitle": "결제를 보내 즉시 구독을 활성화하세요.",
  "checkout.backToPlans": "플랜으로 돌아가기",
  "checkout.awaitingPayment": "결제 대기 중",
  "checkout.invoiceExpires": "인보이스 만료까지",
  "checkout.invoiceExpired": "인보이스 만료됨 — 다시 생성하세요",
  "checkout.regenerate": "결제 재생성",
  "checkout.sendPaymentTo": "이 주소로 결제를 보내세요",
  "checkout.copied": "복사됨!",
  "checkout.evmNetwork": "EVM 호환 네트워크",
  "checkout.networkWarning": "지원되는 EVM 자산만 보내세요. 잘못된 네트워크 = 자금 손실.",
  "checkout.confirmTransaction": "거래 확인",
  "checkout.enterTxHash": "거래 해시를 입력하세요",
  "checkout.confirmPayment": "결제 확인",
  "checkout.checkingBlockchain": "블록체인 확인 중…",
  "checkout.paymentDetected": "결제가 감지되었습니다",
  "checkout.subscriptionActivated": "구독이 활성화되었습니다",
  "checkout.goToDashboard": "대시보드로 이동",
  "checkout.txNotFound": "거래를 찾을 수 없습니다. 해시를 확인하고 다시 시도하세요.",
  "checkout.morePaymentMethods": "다른 결제 방법",
  "checkout.comingSoon": "곧 출시",
  "checkout.securityFooter": "결제는 온체인으로 검증됩니다. Cetra는 개인 키를 저장하지 않습니다.",
  "checkout.duration.1month": "1개월",
  "checkout.duration.3months": "3개월",
  "checkout.duration.12months": "12개월",

  "tmpl.chooseCategory": "카테고리 선택",
  "tmpl.categorySubtitle": "미리 구성된 프로젝트 템플릿을 탐색할 카테고리를 선택하세요.",
  "tmpl.projects": "프로젝트",
  "tmpl.templates": "템플릿",
  "tmpl.comingSoon": "출시 예정",
  "tmpl.useTemplate": "템플릿 사용",
  "tmpl.blankWorkflow": "빈 워크플로우",
  "tmpl.blankDesc": "빈 캔버스에서 시작하여 처음부터 구축하세요.",
  "tmpl.saveAsTemplate": "템플릿으로 저장",
  "tmpl.custom": "내 템플릿",
  "tmpl.customDesc": "저장된 사용자 정의 워크플로우 템플릿.",
  "tmpl.customSaved": "사용자 정의 저장 워크플로우 템플릿.",

  "tmpl.cat.social": "소셜 활동",
  "tmpl.cat.socialDesc": "여러 플랫폼에서 소셜 참여, 퀘스트 완료 및 커뮤니티 파밍을 자동화합니다.",
  "tmpl.cat.testnet": "Testnet",
  "tmpl.cat.testnetDesc": "스왑, 브리지, 민트, 파우셋 클레임을 포함한 테스트넷 상호작용을 자동화합니다.",
  "tmpl.cat.airdrop": "Airdrop",
  "tmpl.cat.airdropDesc": "여러 체인에서 에어드롭을 자동으로 추적하고 클레임합니다.",
  "tmpl.cat.farming": "파밍",
  "tmpl.cat.farmingDesc": "수익률 파밍 및 유동성 공급 자동화 전략.",

  "tmpl.type.pointsFarming": "포인트 파밍",
  "tmpl.type.questCompletion": "퀘스트 완료",
  "tmpl.type.credentialFarming": "자격 증명 파밍",
  "tmpl.type.socialEngagement": "소셜 참여",
  "tmpl.type.roleFarming": "역할 파밍",
  "tmpl.type.testnetActivity": "테스트넷 활동",
  "tmpl.type.crossChain": "Cross-Chain",
  "tmpl.type.l2Activity": "L2 활동",
  "tmpl.type.ecosystemTasks": "생태계 작업",
  "tmpl.type.custom": "사용자 정의",

  "tmpl.konnex.desc": "소셜 작업을 완료하여 Konnex 포인트를 획득하세요: 좋아요, 댓글, 리포스트, 팔로우, Discord 참여, 일일 출석 및 추천.",
  "tmpl.zealy.desc": "일일 퀘스트 모니터링으로 Zealy 퀘스트 완료 및 XP 파밍을 자동화합니다.",
  "tmpl.galxe.desc": "프로필을 연동하고 온체인 작업을 완료하여 Galxe 자격 증명 및 OAT를 클레임합니다.",
  "tmpl.twitter.desc": "Twitter 참여를 자동화합니다: 인간과 유사한 지연으로 좋아요, 리트윗 및 팔로우.",
  "tmpl.discord.desc": "자동 서버 참여, 지갑 인증 및 활동을 통해 Discord 역할을 파밍합니다.",
  "tmpl.pharos.desc": "Pharos 테스트넷 활동 완료: 파우셋 클레임, 토큰 스왑, 브리징, NFT 민트 및 일일 트랜잭션.",
  "tmpl.layerzero.desc": "여러 테스트넷에서 LayerZero 크로스체인 브리지 트랜잭션을 자동화합니다.",
  "tmpl.starknet.desc": "Starknet 온체인 활동 생성: DEX 스왑, 유동성 공급 및 NFT 민트.",
  "tmpl.scroll.desc": "Scroll 테스트넷과 상호작용: 브리지, 토큰 스왑 및 일일 트랜잭션 볼륨 생성.",
  "tmpl.base.desc": "Base 생태계 작업 완료: 브리지, Aerodrome에서 거래 및 Base NFT 민트.",
  "theme.light": "라이트 모드",
  "theme.dark": "다크 모드",
  "theme.default": "기본",

  "tour.step1.title": "내비게이션",
  "tour.step1.desc": "메인 내비게이션입니다. 여기서 워크플로우, 그룹, 구독 등 모든 섹션에 접근할 수 있습니다.",
  "tour.step2.title": "워크플로우 빌더",
  "tour.step2.desc": "비주얼 드래그 앤 드롭 빌더로 자동화 워크플로우를 만드세요. 템플릿을 선택하거나 처음부터 만들 수 있습니다.",
  "tour.step3.title": "구독",
  "tour.step3.desc": "플랜을 관리하고, 사용량을 확인하고, 업그레이드하여 더 많은 계정과 기능을 이용하세요.",
  "tour.step4.title": "추천",
  "tour.step4.desc": "친구를 초대하고 크레딧을 받으세요. 추천할 때마다 보너스 자동화 크레딧을 받습니다.",
  "tour.step5.title": "설정",
  "tour.step5.desc": "경험을 맞춤 설정하세요 — 언어, 테마, 실행 설정, 보안 등.",
  "tour.next": "다음",
  "tour.back": "이전",
  "tour.skip": "건너뛰기",
  "tour.finish": "완료",
  "settings.replayTour": "온보딩 투어",
  "settings.replayTourDesc": "대시보드 가이드 투어 다시 보기",
  "settings.replayTourBtn": "다시 보기",

  "btour.replay": "가이드",
  "btour.step1.title": "워크플로우 캔버스",
  "btour.step1.desc": "워크플로우 캔버스입니다. 액션 카드를 여기로 드래그하여 자동화를 구축하세요. 카드를 자유롭게 이동하고, 확대/축소하고, 화면을 이동할 수 있습니다.",
  "btour.step2.title": "카드 라이브러리",
  "btour.step2.desc": "이 패널에 사용 가능한 모든 액션 카드가 있습니다. 캔버스로 카드를 드래그하여 새 자동화 단계를 추가하세요.",
  "btour.step3.title": "액션 카드",
  "btour.step3.desc": "각 카드는 자동화 단계를 나타냅니다. 설정하고, 드래그하여 위치를 변경하고, 양쪽 포트를 통해 다른 카드와 연결할 수 있습니다.",
  "btour.step4.title": "연결",
  "btour.step4.desc": "연결은 실행 순서를 정의합니다. 출력 포트에서 입력 포트로 드래그하여 흐름을 만드세요. 워크플로우는 위에서 아래로 실행됩니다.",
  "btour.step5.title": "설정 패널",
  "btour.step5.desc": "카드를 선택하면 모든 카드 설정이 여기에 표시됩니다. 기본 설정은 기본적으로 표시되며 카테고리별로 그룹화됩니다.",
  "btour.step6.title": "고급 모드",
  "btour.step6.desc": "고급 모드를 활성화하면 실행 로직, 계정 타겟팅, 오류 처리 등 확장 매개변수에 접근할 수 있습니다. 숙련된 사용자에게 권장됩니다.",
  "btour.step7.title": "워크플로우 템플릿",
  "btour.step7.desc": "워크플로우 이름이 표시됩니다. 템플릿에서 만든 경우 모든 블록을 자유롭게 수정하고 사용자 정의 템플릿으로 저장할 수 있습니다.",
  "btour.step8.title": "저장 및 실행",
  "btour.step8.desc": "워크플로우를 저장하여 진행 상황을 유지하세요. 실행 버튼을 사용하여 계정에서 자동화 실행을 시작하세요.",

  "ctour.help": "카드 설정 가이드",
  "ctour.step1.title": "액션 유형",
  "ctour.step1.desc": "이 카드가 수행하는 액션 유형입니다. 자동화 단계가 무엇을 하는지 정의합니다. 아이콘과 색상이 카테고리를 나타냅니다.",
  "ctour.step2.title": "기본 설정",
  "ctour.step2.desc": "필수 핵심 매개변수입니다. 이것 없이는 카드를 실행할 수 없습니다. 간단한 워크플로우에서는 설정을 최소화하세요.",
  "ctour.step3.title": "입력 필드",
  "ctour.step3.desc": "필수 매개변수입니다. 실행을 위해 유효해야 합니다. 일부 필드는 변수나 동적 값을 지원합니다.",
  "ctour.step4.title": "지연 설정",
  "ctour.step4.desc": "지연은 액션이 실행되는 시점을 제어합니다. 자연스러운 행동을 시뮬레이션하고 자동화 타이밍 제어에 유용합니다.",
  "ctour.step5.title": "재시도 로직",
  "ctour.step5.desc": "재시도는 실패 시 시스템이 몇 번 재시도하는지 정의합니다. 워크플로우 중단을 방지합니다. 재시도가 많을수록 실행 시간이 길어질 수 있습니다.",
  "ctour.step6.title": "고급 모드",
  "ctour.step6.desc": "숨겨진 기술 매개변수를 포함한 확장 구성을 활성화합니다. 세밀한 제어가 필요한 숙련된 사용자에게만 권장됩니다.",
  "ctour.step7.title": "실행 동작",
  "ctour.step7.desc": "액션이 순차적으로, 병렬로, 또는 조건부로 실행되는지 정의합니다. 전체 워크플로우 로직과 성능에 영향을 미칩니다.",
  "ctour.step8.title": "변경 사항 저장",
  "ctour.step8.desc": "변경 사항은 구성 시 자동으로 적용됩니다. 워크플로우를 실행하기 전에 항상 설정을 확인하세요.",
  "onboarding.welcome": "Cetra에 오신 것을 환영합니다!",
  "onboarding.clickBuilder": "시작해 봅시다! 사이드바에서 강조된 워크플로우 빌더 항목을 클릭하여 첫 번째 자동화를 만드세요.",
  "onboarding.builderPhase": "좋습니다! 이제 빌더 캔버스를 탐색하세요. 가이드를 따라 기본 사항을 배워보세요.",
  "onboarding.cardPhase": "거의 완료! 아무 카드나 클릭하여 설정 패널을 확인하고 투어를 완료하세요.",
  "onboarding.complete": "준비 완료! 이제 워크플로우를 만들고 구성하는 방법을 알게 되었습니다."
}
