{
  "nav.dashboard": "Панель управления",
  "nav.workflowBuilder": "Конструктор сценариев",
  "nav.subscription": "Подписка",
  "nav.referrals": "Рефералы",
  "nav.settings": "Настройки",
  "nav.accountGroups": "Группы аккаунтов",
  "nav.logOut": "Выход",
  "dashboard.title": "Панель управления",
  "dashboard.subtitle": "Обзор вашей автоматизации",
  "dashboard.agentStatus": "Статус агента",
  "dashboard.online": "Онлайн",
  "dashboard.efficiency": "Эффективность",
  "dashboard.totalRuns": "Всего запусков",
  "dashboard.totalAccounts": "Всего аккаунтов",
  "dashboard.successful": "Успешных",
  "dashboard.failed": "Ошибки",
  "dashboard.automationActivity": "Активность автоматизации",
  "dashboard.runsAndEfficiency": "Запуски и эффективность",
  "dashboard.last7days": "Последние 7 дней",
  "dashboard.last30days": "Последние 30 дней",
  "dashboard.recentActivity": "Последняя активность",
  "dashboard.latestEvents": "Последние события по всем аккаунтам",
  "dashboard.batchExecutions": "Пакетные выполнения",
  "dashboard.groupsSubtitle": "Группы по всем сценариям",
  "dashboard.all": "Все",
  "dashboard.success": "Успех",
  "dashboard.partial": "Частично",
  "dashboard.noGroupsMatch": "Нет групп, соответствующих фильтру.",
  "dashboard.accounts": "аккаунтов",
  "dashboard.ok": "ок",
  "dashboard.err": "ошиб.",
  "dashboard.wait": "ожид.",
  "dashboard.retryGroup": "Повторить группу",
  "dashboard.retryAccount": "Повтор",
  "dashboard.failedAccounts": "Неудачные аккаунты",
  "dashboard.pending": "Ожидание",
  "dashboard.allCompleted": "Все {count} аккаунтов завершены успешно.",
  "dashboard.noAccountsInGroup": "В этой группе пока нет аккаунтов.",
  "dashboard.recentExecutions": "Недавние выполнения",
  "dashboard.step": "Шаг",
  "workflow.title": "Конструктор сценариев",
  "workflow.save": "Сохранить",
  "workflow.simulate": "Симуляция",
  "workflow.stopSim": "Стоп",
  "workflow.export": "Экспорт",
  "workflow.import": "Импорт",
  "workflow.clear": "Очистить",
  "workflow.undo": "Отмена",
  "workflow.redo": "Вернуть",
  "workflow.zoomIn": "Приблизить",
  "workflow.zoomOut": "Отдалить",
  "workflow.nodeLibrary": "Библиотека узлов",
  "workflow.dragToAdd": "Перетащите",
  "workflow.nodeConfig": "Настройка узла",
  "workflow.selectNode": "Выберите узел для настройки",
  "workflow.delete": "Удалить",
  "workflow.type": "Тип",
  "workflow.label": "Название",
  "workflow.interval": "Интервал",
  "workflow.duration": "Продолжительность (дни)",
  "workflow.splitPercentage": "Процент разделения",
  "workflow.splitCount": "Кол-во разделений",
  "workflow.executionMode": "Режим выполнения",
  "workflow.sequential": "Последовательный",
  "workflow.parallel": "Параллельный",
  "workflow.randomize": "Случайный порядок",
  "workflow.targetGroup": "Целевая группа",
  "workflow.allAccounts": "Все аккаунты",
  "workflow.selectGroup": "Выберите группу...",
  "workflow.noNodes": "Нет узлов",
  "workflow.dropHere": "Перетащите узлы из библиотеки",
  "workflow.advancedMode": "Расширенный режим",
  "workflow.basicSettings": "Основные настройки",
  "workflow.timingIntervals": "Тайминг и интервалы",
  "workflow.executionLogic": "Логика выполнения",
  "workflow.accountTargeting": "Таргетинг аккаунтов",
  "workflow.advancedSettings": "Расширенные настройки",
  "workflow.websiteTargetUrl": "Сайт / Целевой URL",
  "workflow.accountGroup": "Группа аккаунтов",
  "workflow.executionPriority": "Приоритет выполнения",
  "workflow.delayBeforeStart": "Задержка перед стартом",
  "workflow.delayRandomization": "Диапазон рандомизации задержки (сек)",
  "workflow.timeoutBehavior": "Поведение таймаута",
  "workflow.conditionalExecution": "Условное выполнение",
  "workflow.successConfirmation": "Правило подтверждения успеха",
  "workflow.concurrency": "Параллельность",
  "workflow.executionOrder": "Порядок выполнения",
  "workflow.errorStrategy": "Стратегия ошибок",
  "workflow.retryStrategy": "Стратегия повтора",
  "workflow.failSafeStop": "Аварийная остановка",
  "workflow.loggingLevel": "Уровень логирования",
  "workflow.maxAttemptsLimit": "Лимит попыток",
  "workflow.riskLevel": "Уровень риска",
  "subscription.title": "Подписка",
  "subscription.subtitle": "Выберите удобный период оплаты",
  "subscription.monthly": "Ежемесячно",
  "subscription.3months": "3 месяца",
  "subscription.yearly": "Годовой",
  "subscription.billedMonthly": "Ежемесячная оплата",
  "subscription.billedEvery3Months": "Оплата каждые 3 месяца",
  "subscription.billedAnnually": "Ежегодная оплата",
  "subscription.saveVsMonthly": "Экономия {percent}% от ежемесячной",
  "subscription.perMonth": "мес",
  "subscription.currentPlan": "Текущий план",
  "subscription.status": "Статус",
  "subscription.active": "Активный",
  "subscription.freeTrial": "Пробный период",
  "subscription.freeMode": "Вы в бесплатном режиме",
  "subscription.freeModeSub": "Ограниченные возможности. Разблокируйте полную автоматизацию.",
  "subscription.unlockFull": "Разблокировать автоматизацию",
  "subscription.trialEnds": "Пробный период заканчивается через",
  "subscription.days": "дней",
  "subscription.upgradePlan": "Улучшить план",
  "subscription.currentPlanBadge": "Текущий план",
  "subscription.mostPopular": "Самый популярный",
  "subscription.allPlansUnlimited": "Все планы включают безлимитные аккаунты",
  "subscription.feat.unlimitedAccounts": "Безлимитные аккаунты",
  "subscription.feat.highSpeed": "Высокоскоростной уровень выполнения",
  "subscription.feat.priorityQueue": "Приоритетная очередь",
  "subscription.feat.advancedErrors": "Расширенная обработка ошибок",
  "subscription.feat.workflowAnalytics": "Аналитика сценариев",
  "subscription.feat.aiAssistant": "ИИ-ассистент сценариев",
  "subscription.feat.premiumSupport": "Премиум-поддержка",
  "subscription.why.fasterExec": "Быстрое выполнение",
  "subscription.why.fasterExecDesc": "Приоритетная очередь обеспечивает молниеносную автоматизацию",
  "subscription.why.smarterRecovery": "Умное восстановление",
  "subscription.why.smarterRecoveryDesc": "ИИ-обработка ошибок автоматически восстанавливает после сбоев",
  "subscription.why.aiAssist": "ИИ-помощь",
  "subscription.why.aiAssistDesc": "Интеллектуальные предложения и оптимизация сценариев",
  "subscription.why.priorityInfra": "Приоритетная инфраструктура",
  "subscription.why.priorityInfraDesc": "Выделенные ресурсы для максимальной надёжности",
  "subscription.why.premiumReliability": "Премиум-надёжность",
  "subscription.why.premiumReliabilityDesc": "Корпоративная стабильность для критической автоматизации",
  "subscription.whyUpgrade": "Зачем улучшать?",
  "subscription.cryptoPayments": "Криптооплата поддерживается",
  "subscription.paymentMethods": "Методы оплаты",
  "referrals.title": "Рефералы",
  "referrals.subtitle": "Приглашай друзей. Получай кредиты.",
  "referrals.creditsTitle": "Что такое кредиты?",
  "referrals.creditsDesc": "Кредиты — это бонусный баланс за приглашённых друзей.",
  "referrals.creditsUseIntro": "Кредиты можно использовать для:",
  "referrals.creditUse1": "Оплаты подписок",
  "referrals.creditUse2": "Повышения тарифа",
  "referrals.creditUse3": "Разблокировки премиум-функций",
  "referrals.creditsAutoApply": "Кредиты автоматически применяются при оплате.",
  "referrals.heroText": "Получайте награду за каждую подписку ваших рефералов.",
  "referrals.earnPercent": "Вы получаете 20% от каждого платежа в кредитах платформы",
  "referrals.yourLink": "Ваша реферальная ссылка",
  "referrals.shareLink": "Поделитесь для получения наград",
  "referrals.copied": "Скопировано",
  "referrals.copy": "Копировать",
  "referrals.shareTelegram": "Telegram",
  "referrals.shareX": "X",
  "referrals.shareDiscord": "Discord",
  "referrals.activeReferrals": "Активные рефералы",
  "referrals.totalEarned": "Всего заработано кредитов",
  "referrals.currentLevel": "Текущий уровень",
  "referrals.lifetimeCommission": "Пожизненная комиссия %",
  "referrals.yourLevel": "Ваш реферальный уровень",
  "referrals.level1": "Стартовый",
  "referrals.level1Req": "1-4 активных реферала",
  "referrals.level1Perk": "20% кредитов с платежей",
  "referrals.level2": "Рост",
  "referrals.level2Req": "5-9 активных рефералов",
  "referrals.level2Perk1": "30% кредитов с платежей",
  "referrals.level2Perk2": "20% скидка на подписку",
  "referrals.level3": "Партнёр",
  "referrals.level3Req": "10+ активных рефералов",
  "referrals.level3Perk1": "10% пожизненная комиссия",
  "referrals.level3Perk2": "Статус партнёра",
  "referrals.level4": "Амбассадор",
  "referrals.level4Req": "50+ активных рефералов",
  "referrals.level4Perk1": "Значок амбассадора",
  "referrals.level4Perk2": "Эксклюзивные награды",
  "referrals.unlocked": "Открыт",
  "referrals.locked": "Закрыт",
  "referrals.current": "Текущий",
  "referrals.activity": "Реферальная активность",
  "referrals.colUserId": "ID пользователя",
  "referrals.colPlan": "Купленный план",
  "referrals.colAmount": "Сумма платежа",
  "referrals.colReward": "Ваша награда",
  "referrals.colStatus": "Статус",
  "referrals.statusPending": "Ожидание",
  "referrals.statusActive": "Активный",
  "referrals.statusExpired": "Истёк",
  "referrals.creditsWallet": "Кошелёк кредитов",
  "referrals.availableCredits": "Доступные кредиты",
  "referrals.lifetimeEarned": "Заработано за всё время",
  "referrals.creditsUsed": "Использовано кредитов",
  "referrals.applyCredits": "Применить кредиты к подписке",
  "referrals.creditsTooltip": "Кредиты автоматически уменьшают ваш следующий платёж",
  "referrals.achievements": "Достижения",
  "referrals.achFirstRef": "Первый реферал",
  "referrals.achFiveRef": "5 рефералов",
  "referrals.achTopPartner": "Топ-партнёр",
  "referrals.emptyTitle": "Начните приглашать друзей для разблокировки наград",
  "referrals.emptyCta": "Скопировать реферальную ссылку",
  "settings.title": "Настройки",
  "settings.subtitle": "Управление предпочтениями",
  "settings.profile": "Профиль",
  "settings.displayName": "Имя",
  "settings.email": "Эл. почта",
  "settings.saveChanges": "Сохранить",
  "settings.notifications": "Уведомления",
  "settings.emailNotifications": "Эл. уведомления",
  "settings.emailNotificationsDesc": "Получать обновления о сценариях",
  "settings.workflowAlerts": "Оповещения",
  "settings.workflowAlertsDesc": "Уведомления о сценариях",
  "settings.marketingEmails": "Маркетинговые письма",
  "settings.marketingEmailsDesc": "Обновления и анонсы",
  "settings.security": "Безопасность",
  "settings.changePassword": "Сменить пароль",
  "settings.lastPasswordChange": "Последняя смена пароля: никогда",
  "settings.language": "Язык",
  "settings.languageDesc": "Выберите предпочтительный язык",
  "groups.title": "Группы аккаунтов",
  "groups.subtitle": "Организуйте аккаунты в логические группы",
  "groups.createGroup": "Создать группу",
  "groups.newGroup": "Новая группа",
  "groups.groupName": "Название группы",
  "groups.enterGroupName": "Введите название",
  "groups.create": "Создать",
  "groups.cancel": "Отмена",
  "groups.rename": "Переименовать",
  "groups.delete": "Удалить",
  "groups.deleteConfirm": "Удалить эту группу? Аккаунты будут освобождены.",
  "groups.noGroups": "Нет групп. Создайте для организации аккаунтов.",
  "groups.accountCount": "{count} аккаунтов",
  "groups.lastActivity": "Последняя активность",
  "groups.activeWorkflows": "Активные сценарии",
  "groups.successRate": "Успешность",
  "groups.manageAccounts": "Управление аккаунтами",
  "groups.availableAccounts": "Доступные аккаунты",
  "groups.groupAccounts": "Аккаунты группы",
  "groups.dragToAssign": "Перетащите для назначения",
  "groups.noAvailable": "Все аккаунты назначены.",
  "groups.noAccountsInGroup": "Нет аккаунтов в группе.",
  "groups.addToGroup": "Добавить",
  "groups.removeFromGroup": "Убрать",
  "groups.overview": "Обзор",
  "groups.backToGroups": "Назад к группам",
  "groups.totalInGroup": "Всего в группе",
  "groups.successfulRuns": "Успешные запуски",
  "groups.failedRuns": "Неудачные запуски",
  "groups.recentExecutions": "Последние выполнения",
  "groups.noExecutions": "Нет выполнений для группы.",
  "groups.status": "Статус",
  "groups.workflow": "Сценарий",
  "groups.time": "Время",
  "groups.moveToGroup": "Переместить в группу",
  "groups.notFound": "Группа не найдена.",
  "nodeType.wallet": "Действие кошелька",
  "nodeType.delay": "Задержка",
  "nodeType.split": "Разделить группу",
  "nodeType.condition": "Условие",
  "nodeType.swap": "Обмен",
  "nodeType.loop": "Цикл",
  "nodeType.bridge": "Мост",
  "nodeType.notify": "Уведомление",
  "nodeType.repeat": "Повтор цикла",
  "nodeType.airdrop": "Клейм эйрдропа",
  "nodeType.script": "Пользовательский скрипт",
  "status.success": "Успех",
  "status.partial": "Частично",
  "status.failed": "Ошибка",
  "status.pending": "Ожидание",
  "status.running": "Выполняется",
  "common.save": "Сохранить",
  "common.cancel": "Отмена",
  "common.delete": "Удалить",
  "common.edit": "Редактировать",
  "common.close": "Закрыть",
  "common.confirm": "Подтвердить",
  "common.search": "Поиск",
  "common.noResults": "Результатов не найдено.",
  "guide.title": "Руководство по настройкам",
  "guide.section.overview": "Основные настройки",
  "guide.section.advanced": "Расширенные настройки",
  "guide.section.timing": "Тайминг и задержки",
  "guide.section.risk": "Индикаторы риска",
  "guide.section.simulation": "Режим симуляции",
  "guide.overview.accountGroup": "Группа аккаунтов",
  "guide.overview.accountGroupDesc": "Выберите группу аккаунтов для выполнения этого действия. Группами можно управлять на странице Группы аккаунтов.",
  "guide.overview.urlTarget": "URL / Цель",
  "guide.overview.urlTargetDesc": "Целевой URL или адрес контракта для взаимодействия.",
  "guide.overview.delay": "Задержка",
  "guide.overview.delayDesc": "Время ожидания перед выполнением действия. Помогает избежать обнаружения и лимитов.",
  "guide.overview.onSuccess": "При успехе",
  "guide.overview.onSuccessDesc": "Что происходит после успешного выполнения — перейти к следующему, повторить или остановить.",
  "guide.advanced.concurrency": "Параллельность",
  "guide.advanced.concurrencyDesc": "Сколько аккаунтов выполняют действие одновременно. Больше — быстрее, но рискованнее.",
  "guide.advanced.interval": "Интервал",
  "guide.advanced.intervalDesc": "Время между каждой партией аккаунтов. Контролирует скорость выполнения.",
  "guide.advanced.jitter": "Джиттер",
  "guide.advanced.jitterDesc": "Добавляет случайные вариации во время, делая действия более естественными.",
  "guide.advanced.retryLogic": "Логика повторов",
  "guide.advanced.retryLogicDesc": "Как повторяются неудачные действия — количество попыток, задержка и стратегия отступления.",
  "guide.advanced.conditions": "Условия",
  "guide.advanced.conditionsDesc": "Проверки перед выполнением: минимальный баланс, лимиты газа и другие требования.",
  "guide.advanced.errorHandling": "Обработка ошибок",
  "guide.advanced.errorHandlingDesc": "Что происходит при ошибке — пропустить аккаунт, повторить или остановить весь процесс.",
  "guide.timing.delays": "Типы задержек",
  "guide.timing.delaysDesc": "Фиксированные задержки ждут заданное время. Случайные добавляют вариацию для более естественного поведения.",
  "guide.timing.batching": "Пакетная обработка",
  "guide.timing.batchingDesc": "Аккаунты обрабатываются пакетами. Размер пакета равен параллельности, с интервалами между ними.",
  "guide.timing.retries": "Время повторов",
  "guide.timing.retriesDesc": "Неудачные аккаунты ждут перед повтором. Экспоненциальный откат удваивает время с каждой попыткой.",
  "guide.risk.safe": "Безопасно",
  "guide.risk.safeDesc": "Действия с низким риском: чтение данных или проверка балансов. Без риска для средств.",
  "guide.risk.medium": "Средний",
  "guide.risk.mediumDesc": "Действия со средним риском: апрувы токенов или свопы на проверенных протоколах.",
  "guide.risk.risky": "Рискованно",
  "guide.risk.riskyDesc": "Действия с высоким риском: непроверенные контракты или крупные операции. Используйте осторожно.",
  "guide.simulation.preview": "Режим предпросмотра",
  "guide.simulation.previewDesc": "Симулируйте весь рабочий процесс без реальных транзакций. Увидите расчётное время и поток аккаунтов.",
  "guide.simulation.howTo": "Как запустить симуляцию",
  "guide.simulation.howToDesc": "Нажмите кнопку воспроизведения на карточке или используйте кнопку симуляции на панели инструментов.",
  "settings.nav.account": "Аккаунт",
  "settings.nav.interface": "Интерфейс",
  "settings.nav.execution": "Выполнение",
  "settings.nav.security": "Безопасность",
  "settings.nav.notifications": "Уведомления",
  "settings.nav.data": "Данные",
  "settings.nav.advanced": "Расширенные",
  "settings.emailDesc": "Ваш зарегистрированный адрес электронной почты",
  "settings.changePasswordDesc": "Установить новый пароль для аккаунта",
  "settings.twoFactor": "Двухфакторная аутентификация",
  "settings.twoFactorDesc": "Добавить дополнительный уровень защиты аккаунта",
  "settings.activeSessions": "Активные сессии",
  "settings.activeSessionsDesc": "Устройства, на которых выполнен вход в аккаунт",
  "settings.active": "активно",
  "settings.logoutAll": "Выйти везде",
  "settings.logoutAllDesc": "Выйти из аккаунта на всех устройствах и сессиях",
  "settings.logoutAllBtn": "Завершить все сессии",
  "settings.timezone": "Часовой пояс",
  "settings.timezoneDesc": "Установите предпочтительный часовой пояс для планирования",
  "settings.timeFormat": "Формат времени",
  "settings.timeFormatDesc": "Выберите 12-часовой или 24-часовой формат отображения",
  "settings.compactUI": "Компактный интерфейс",
  "settings.compactUIDesc": "Уменьшить отступы для более плотного интерфейса",
  "settings.executionNote": "Эти настройки влияют на выполнение сценариев по всем аккаунтам.",
  "settings.speedProfile": "Профиль скорости",
  "settings.speedProfileDesc": "Контролирует задержку между действиями",
  "settings.speedSafe": "Безопасный",
  "settings.speedSafeDesc": "Максимальные задержки между действиями",
  "settings.speedBalanced": "Сбалансированный",
  "settings.speedBalancedDesc": "Умеренные задержки между действиями",
  "settings.speedAggressive": "Агрессивный",
  "settings.speedAggressiveDesc": "Минимальные задержки между действиями",
  "settings.retryStrategy": "Стратегия повторов",
  "settings.retryStrategyDesc": "Как повторяются неудачные действия",
  "settings.retryCons": "Консервативный",
  "settings.retrySmart": "Умный",
  "settings.retryMax": "Максимальный",
  "settings.randomization": "Уровень рандомизации",
  "settings.randomizationDesc": "Добавляет случайные отклонения во времени и действиях",
  "settings.randomLow": "Низкий",
  "settings.randomMedium": "Средний",
  "settings.randomHigh": "Высокий",
  "settings.failureTolerance": "Допустимость ошибок",
  "settings.failureToleranceDesc": "Как система обрабатывает ошибки отдельных аккаунтов",
  "settings.failStrict": "Строгий",
  "settings.failFlexible": "Гибкий",
  "settings.privacyMode": "Режим конфиденциальности",
  "settings.privacyModeDesc": "Скрывать адреса кошельков и конфиденциальные данные в интерфейсе",
  "settings.localExecution": "Только локальное выполнение",
  "settings.localExecutionDesc": "Обрабатывать все сценарии локально без облачной синхронизации",
  "settings.dataRetention": "Период хранения данных",
  "settings.dataRetentionDesc": "Сколько хранятся журналы выполнения",
  "settings.days": "дней",
  "settings.autoLogDeletion": "Автоудаление журналов",
  "settings.autoLogDeletionDesc": "Автоматически удалять старые журналы после истечения срока хранения",
  "settings.notifErrors": "Уведомления об ошибках",
  "settings.notifErrorsDesc": "Получать уведомления при возникновении ошибок в сценариях",
  "settings.notifCompletion": "Уведомления о завершении",
  "settings.notifCompletionDesc": "Получать уведомления при успешном завершении сценариев",
  "settings.notifBilling": "Уведомления об оплате",
  "settings.notifBillingDesc": "Получать уведомления о платежах и изменениях подписки",
  "settings.notifReferrals": "Уведомления о рефералах",
  "settings.notifReferralsDesc": "Получать уведомления, когда кто-то использует вашу реферальную ссылку",
  "settings.notifUpdates": "Обновления продукта",
  "settings.notifUpdatesDesc": "Получать уведомления о новых функциях и обновлениях платформы",
  "settings.channels": "Каналы уведомлений",
  "settings.channelEmail": "Эл. почта",
  "settings.channelInApp": "В приложении",
  "settings.exportWorkflows": "Экспорт сценариев",
  "settings.importWorkflows": "Импорт сценариев",
  "settings.backupSettings": "Резервное копирование настроек",
  "settings.resetEnvironment": "Сброс окружения",
  "settings.confirmTitle": "Подтвердить сброс",
  "settings.confirmResetDesc": "Это сбросит все настройки к значениям по умолчанию. Это действие нельзя отменить.",
  "settings.confirmReset": "Сбросить всё",
  "settings.enableAdvanced": "Включить расширенный режим",
  "settings.enableAdvancedDesc": "Открыть доступ к журналам отладки, экспериментальным функциям и диагностике",
  "settings.debugLogs": "Журналы отладки",
  "settings.debugLogsDesc": "Показывать подробные журналы отладки в консоли",
  "settings.experimentalFeatures": "Экспериментальные функции",
  "settings.experimentalFeaturesDesc": "Включить экспериментальные функции, которые могут быть нестабильны",
  "settings.extendedDiagnostics": "Расширенная диагностика",
  "settings.extendedDiagnosticsDesc": "Запускать расширенную диагностику выполнения сценариев",
  "paywall.title": "Разблокировать выполнение",
  "paywall.description": "Обновите план, чтобы запускать реальные автоматизации и масштабировать рабочие процессы.",
  "paywall.trialExhausted": "Вы использовали все 3 пробных запуска. Обновите план для продолжения.",
  "paywall.trialUsed": "Все 3 пробных запуска использованы",
  "paywall.upgradePlan": "Обновить план",
  "paywall.continueFree": "Продолжить бесплатно",
  "paywall.bannerText": "Вы на бесплатном плане — обновите для запуска автоматизаций",
  "paywall.upgrade": "Обновить",
  "paywall.trialRunsLeft": "пробных запусков осталось",
  "paywall.feat.multiAccount": "Мульти-аккаунт выполнение",
  "paywall.feat.smartRouting": "Умная маршрутизация",
  "paywall.feat.advancedScheduling": "Расширенное планирование",
  "paywall.feat.priorityExecution": "Приоритетное выполнение",
  "paywall.lockedFeature": "Эта функция требует платного плана",
  "paywall.runLocked": "Выполнение заблокировано на бесплатном плане",
  "guest.badge": "Гость",
  "guest.badgeDesc": "Не авторизован",
  "guest.bannerText": "Вы в гостевом режиме — создайте аккаунт, чтобы сохранить работу",
  "guest.createAccount": "Создать аккаунт",
  "guest.signupTitle": "Создать бесплатный аккаунт",
  "guest.signupDefault": "Сохраняйте воркфлоу и получайте к ним доступ в любое время",
  "guest.signupToSave": "Создайте аккаунт, чтобы сохранять воркфлоу навсегда",
  "guest.signupToExport": "Создайте аккаунт для экспорта воркфлоу",
  "guest.signupToExecute": "Создайте аккаунт для запуска автоматизации",
  "guest.signUpEmail": "Зарегистрироваться по Email",
  "guest.continueGuest": "Продолжить как гость",
  "guest.benefit.saveWorkflows": "Сохранение воркфлоу навсегда",
  "guest.benefit.cloudBackup": "Облачное резервное копирование",
  "guest.benefit.freeTrialRuns": "3 бесплатных пробных запуска",
  "guest.exitDashboard": "Выйти",
  "checkout.title": "Оплата криптовалютой",
  "checkout.subtitle": "Отправьте платёж для мгновенной активации подписки.",
  "checkout.backToPlans": "Назад к тарифам",
  "checkout.awaitingPayment": "Ожидание оплаты",
  "checkout.invoiceExpires": "Счёт истекает через",
  "checkout.invoiceExpired": "Счёт истёк — создайте новый",
  "checkout.regenerate": "Создать новый счёт",
  "checkout.sendPaymentTo": "Отправьте платёж на этот адрес",
  "checkout.copied": "Скопировано!",
  "checkout.evmNetwork": "EVM-совместимая сеть",
  "checkout.networkWarning": "Отправляйте только поддерживаемые EVM-активы. Неверная сеть = потеря средств.",
  "checkout.confirmTransaction": "Подтвердить транзакцию",
  "checkout.enterTxHash": "Введите хеш транзакции",
  "checkout.confirmPayment": "Подтвердить оплату",
  "checkout.checkingBlockchain": "Проверка блокчейна…",
  "checkout.paymentDetected": "Платёж обнаружен",
  "checkout.subscriptionActivated": "Ваша подписка активирована",
  "checkout.goToDashboard": "Перейти в панель",
  "checkout.txNotFound": "Транзакция не найдена. Проверьте хеш и попробуйте снова.",
  "checkout.morePaymentMethods": "Другие способы оплаты",
  "checkout.comingSoon": "Скоро",
  "checkout.securityFooter": "Платежи проверяются в блокчейне. Cetra не хранит ваши приватные ключи.",
  "checkout.duration.1month": "1 месяц",
  "checkout.duration.3months": "3 месяца",
  "checkout.duration.12months": "12 месяцев",

  "tmpl.chooseCategory": "Выберите категорию",
  "tmpl.categorySubtitle": "Выберите категорию для просмотра готовых шаблонов проектов.",
  "tmpl.projects": "проекты",
  "tmpl.templates": "шаблоны",
  "tmpl.comingSoon": "Скоро",
  "tmpl.useTemplate": "Использовать шаблон",
  "tmpl.blankWorkflow": "Пустой сценарий",
  "tmpl.blankDesc": "Начните с чистого холста и создайте с нуля.",
  "tmpl.saveAsTemplate": "Сохранить как шаблон",
  "tmpl.custom": "Мои шаблоны",
  "tmpl.customDesc": "Ваши сохранённые пользовательские шаблоны сценариев.",
  "tmpl.customSaved": "Пользовательский сохранённый шаблон сценария.",

  "tmpl.cat.social": "Социальная активность",
  "tmpl.cat.socialDesc": "Автоматизация социального взаимодействия, выполнения квестов и фарминга сообществ на разных платформах.",
  "tmpl.cat.testnet": "Testnet",
  "tmpl.cat.testnetDesc": "Автоматизация взаимодействий с тестнетами, включая свопы, бриджи, минты и клеймы из фаусетов.",
  "tmpl.cat.airdrop": "Airdrop",
  "tmpl.cat.airdropDesc": "Отслеживание и автоматический клейм эйрдропов в нескольких сетях.",
  "tmpl.cat.farming": "Фарминг",
  "tmpl.cat.farmingDesc": "Стратегии автоматизации фарминга доходности и предоставления ликвидности.",

  "tmpl.type.pointsFarming": "Фарминг очков",
  "tmpl.type.questCompletion": "Выполнение квестов",
  "tmpl.type.credentialFarming": "Фарминг учётных данных",
  "tmpl.type.socialEngagement": "Социальное взаимодействие",
  "tmpl.type.roleFarming": "Фарминг ролей",
  "tmpl.type.testnetActivity": "Активность в тестнете",
  "tmpl.type.crossChain": "Cross-Chain",
  "tmpl.type.l2Activity": "Активность L2",
  "tmpl.type.ecosystemTasks": "Задачи экосистемы",
  "tmpl.type.custom": "Пользовательский",

  "tmpl.konnex.desc": "Зарабатывайте очки Konnex, выполняя социальные задания: лайки, комментарии, репосты, подписки, вступление в Discord, ежедневная отметка и рефералы.",
  "tmpl.zealy.desc": "Автоматизация выполнения квестов Zealy и фарминга XP с ежедневным мониторингом квестов.",
  "tmpl.galxe.desc": "Клейм учётных данных Galxe и OAT путём привязки профилей и выполнения задач в сети.",
  "tmpl.twitter.desc": "Автоматизация взаимодействия в Twitter: лайки, ретвиты и подписки с человекоподобными задержками.",
  "tmpl.discord.desc": "Фарминг ролей Discord через автоматическое присоединение к серверам, верификацию кошельков и активность.",
  "tmpl.pharos.desc": "Выполнение активностей в тестнете Pharos: клеймы из фаусета, свопы токенов, бриджинг, минт NFT и ежедневные транзакции.",
  "tmpl.layerzero.desc": "Автоматизация кросс-чейн бридж-транзакций LayerZero в нескольких тестнетах.",
  "tmpl.starknet.desc": "Генерация ончейн-активности Starknet: свопы на DEX, предоставление ликвидности и минт NFT.",
  "tmpl.scroll.desc": "Взаимодействие с тестнетом Scroll: бридж, свопы токенов и генерация ежедневного объёма транзакций.",
  "tmpl.base.desc": "Выполнение задач экосистемы Base: бридж, торговля на Aerodrome и минт NFT на Base.",
  "theme.light": "Светлая тема",
  "theme.dark": "Тёмная тема",
  "theme.default": "по умолч.",

  "tour.step1.title": "Навигация",
  "tour.step1.desc": "Это ваша главная навигация. Отсюда вы можете перейти ко всем разделам — воркфлоу, группы, подписка и другие.",
  "tour.step2.title": "Конструктор воркфлоу",
  "tour.step2.desc": "Создавайте автоматизации с помощью визуального конструктора. Выбирайте из шаблонов или создавайте с нуля.",
  "tour.step3.title": "Подписка",
  "tour.step3.desc": "Управляйте своим планом, отслеживайте использование и улучшайте тариф для доступа к большему количеству аккаунтов.",
  "tour.step4.title": "Рефералы",
  "tour.step4.desc": "Приглашайте друзей и получайте кредиты. За каждого реферала вы получаете бонусные кредиты.",
  "tour.step5.title": "Настройки",
  "tour.step5.desc": "Настройте интерфейс — язык, тема, параметры выполнения, безопасность и многое другое.",
  "tour.next": "Далее",
  "tour.back": "Назад",
  "tour.skip": "Пропустить",
  "tour.finish": "Готово",
  "settings.replayTour": "Обучающий тур",
  "settings.replayTourDesc": "Повторить пошаговое руководство по дашборду",
  "settings.replayTourBtn": "Повторить",

  "btour.replay": "Гайд",
  "btour.step1.title": "Рабочий холст",
  "btour.step1.desc": "Это ваш рабочий холст. Перетаскивайте сюда карточки действий для создания автоматизации. Можно свободно перемещать, масштабировать и прокручивать.",
  "btour.step2.title": "Библиотека карточек",
  "btour.step2.desc": "Эта панель содержит все доступные карточки действий. Перетащите любую на холст, чтобы добавить новый шаг автоматизации.",
  "btour.step3.title": "Карточка действия",
  "btour.step3.desc": "Каждая карточка — это шаг автоматизации. Настройте её, перемещайте и соединяйте с другими карточками через порты по бокам.",
  "btour.step4.title": "Соединения",
  "btour.step4.desc": "Соединения определяют порядок выполнения. Перетащите от выхода к входу, чтобы создать поток. Воркфлоу выполняется сверху вниз.",
  "btour.step5.title": "Панель настроек",
  "btour.step5.desc": "Все настройки карточки отображаются здесь при её выборе. Базовые настройки видны по умолчанию, сгруппированы по категориям.",
  "btour.step6.title": "Расширенный режим",
  "btour.step6.desc": "Включите расширенный режим для доступа к дополнительным параметрам: логика выполнения, таргетинг аккаунтов и обработка ошибок. Рекомендуется для опытных пользователей.",
  "btour.step7.title": "Шаблон воркфлоу",
  "btour.step7.desc": "Здесь отображается название воркфлоу. Если создан из шаблона, можно свободно изменять любой блок и сохранить как свой шаблон.",
  "btour.step8.title": "Сохранить и запустить",
  "btour.step8.desc": "Сохраните воркфлоу, чтобы сохранить прогресс. Нажмите «Запустить» для начала автоматизации на ваших аккаунтах.",

  "ctour.help": "Гайд по настройкам карточки",
  "ctour.step1.title": "Тип действия",
  "ctour.step1.desc": "Это тип действия, которое выполняет карточка. Он определяет, что делает шаг автоматизации. Иконка и цвет указывают на категорию.",
  "ctour.step2.title": "Базовые настройки",
  "ctour.step2.desc": "Это обязательные основные параметры. Без них карточка не сможет выполниться. Для простых воркфлоу держите настройки минимальными.",
  "ctour.step3.title": "Поля ввода",
  "ctour.step3.desc": "Это обязательный параметр. Должен быть корректным для выполнения. Некоторые поля поддерживают переменные или динамические значения.",
  "ctour.step4.title": "Настройки задержки",
  "ctour.step4.desc": "Задержка контролирует, когда действие выполняется. Помогает имитировать естественное поведение и полезна для управления таймингом.",
  "ctour.step5.title": "Логика повторов",
  "ctour.step5.desc": "Повтор определяет, сколько раз система повторяет попытку при сбое. Это предотвращает прерывание воркфлоу. Больше повторов — дольше выполнение.",
  "ctour.step6.title": "Расширенный режим",
  "ctour.step6.desc": "Включает расширенную конфигурацию и скрытые технические параметры. Рекомендуется только для опытных пользователей.",
  "ctour.step7.title": "Поведение выполнения",
  "ctour.step7.desc": "Определяет, выполняется ли действие последовательно, параллельно или условно. Влияет на логику и производительность воркфлоу.",
  "ctour.step8.title": "Сохранить изменения",
  "ctour.step8.desc": "Изменения применяются автоматически при настройке. Всегда проверяйте настройки перед запуском воркфлоу.",
  "onboarding.welcome": "Добро пожаловать в Cetra!",
  "onboarding.clickBuilder": "Начнём! Нажмите на выделенный пункт «Конструктор сценариев» в боковой панели, чтобы создать вашу первую автоматизацию.",
  "onboarding.builderPhase": "Отлично! Теперь изучите холст конструктора. Следуйте гиду, чтобы узнать основы.",
  "onboarding.cardPhase": "Почти готово! Нажмите на любую карточку, чтобы увидеть панель настроек и завершить тур.",
  "onboarding.complete": "Готово! Теперь вы знаете, как создавать и настраивать сценарии."
}
