{
  "nav.dashboard": "Панель керування",
  "nav.workflowBuilder": "Конструктор сценаріїв",
  "nav.subscription": "Підписка",
  "nav.referrals": "Реферали",
  "nav.settings": "Налаштування",
  "nav.accountGroups": "Групи акаунтів",
  "nav.logOut": "Вихід",
  "dashboard.title": "Панель керування",
  "dashboard.subtitle": "Огляд вашої автоматизації",
  "dashboard.agentStatus": "Статус агента",
  "dashboard.online": "Онлайн",
  "dashboard.efficiency": "Ефективність",
  "dashboard.totalRuns": "Всього запусків",
  "dashboard.totalAccounts": "Всього акаунтів",
  "dashboard.successful": "Успішних",
  "dashboard.failed": "Помилки",
  "dashboard.automationActivity": "Активність автоматизації",
  "dashboard.runsAndEfficiency": "Запуски та ефективність",
  "dashboard.last7days": "Останні 7 днів",
  "dashboard.last30days": "Останні 30 днів",
  "dashboard.recentActivity": "Остання активність",
  "dashboard.latestEvents": "Останні події по всіх акаунтах",
  "dashboard.batchExecutions": "Пакетні виконання",
  "dashboard.groupsSubtitle": "Групи по всіх сценаріях",
  "dashboard.all": "Всі",
  "dashboard.success": "Успіх",
  "dashboard.partial": "Частково",
  "dashboard.noGroupsMatch": "Немає груп за цим фільтром.",
  "dashboard.accounts": "акаунтів",
  "dashboard.ok": "ок",
  "dashboard.err": "пом.",
  "dashboard.wait": "очік.",
  "dashboard.retryGroup": "Повторити групу",
  "dashboard.retryAccount": "Повтор",
  "dashboard.failedAccounts": "Невдалі акаунти",
  "dashboard.pending": "Очікування",
  "dashboard.allCompleted": "Всі {count} акаунтів завершені успішно.",
  "dashboard.noAccountsInGroup": "У цій групі поки немає акаунтів.",
  "dashboard.recentExecutions": "Нещодавні виконання",
  "dashboard.step": "Крок",
  "workflow.title": "Конструктор сценаріїв",
  "workflow.save": "Зберегти",
  "workflow.simulate": "Симуляція",
  "workflow.stopSim": "Стоп",
  "workflow.export": "Експорт",
  "workflow.import": "Імпорт",
  "workflow.clear": "Очистити",
  "workflow.undo": "Скасувати",
  "workflow.redo": "Повернути",
  "workflow.zoomIn": "Наблизити",
  "workflow.zoomOut": "Віддалити",
  "workflow.nodeLibrary": "Бібліотека вузлів",
  "workflow.dragToAdd": "Перетягніть",
  "workflow.nodeConfig": "Налаштування вузла",
  "workflow.selectNode": "Виберіть вузол для налаштування",
  "workflow.delete": "Видалити",
  "workflow.type": "Тип",
  "workflow.label": "Назва",
  "workflow.interval": "Інтервал",
  "workflow.duration": "Тривалість (дні)",
  "workflow.splitPercentage": "Відсоток розділення",
  "workflow.splitCount": "Кількість розділень",
  "workflow.executionMode": "Режим виконання",
  "workflow.sequential": "Послідовний",
  "workflow.parallel": "Паралельний",
  "workflow.randomize": "Випадковий порядок",
  "workflow.targetGroup": "Цільова група",
  "workflow.allAccounts": "Всі акаунти",
  "workflow.selectGroup": "Виберіть групу...",
  "workflow.noNodes": "Немає вузлів",
  "workflow.dropHere": "Перетягніть вузли з бібліотеки",
  "workflow.advancedMode": "Розширений режим",
  "workflow.basicSettings": "Основні налаштування",
  "workflow.timingIntervals": "Таймінг та інтервали",
  "workflow.executionLogic": "Логіка виконання",
  "workflow.accountTargeting": "Таргетинг акаунтів",
  "workflow.advancedSettings": "Розширені налаштування",
  "workflow.websiteTargetUrl": "Сайт / Цільова URL",
  "workflow.accountGroup": "Група акаунтів",
  "workflow.executionPriority": "Пріоритет виконання",
  "workflow.delayBeforeStart": "Затримка перед стартом",
  "workflow.delayRandomization": "Діапазон рандомізації затримки (сек)",
  "workflow.timeoutBehavior": "Поведінка таймауту",
  "workflow.conditionalExecution": "Умовне виконання",
  "workflow.successConfirmation": "Правило підтвердження успіху",
  "workflow.concurrency": "Паралельність",
  "workflow.executionOrder": "Порядок виконання",
  "workflow.errorStrategy": "Стратегія помилок",
  "workflow.retryStrategy": "Стратегія повтору",
  "workflow.failSafeStop": "Аварійна зупинка",
  "workflow.loggingLevel": "Рівень логування",
  "workflow.maxAttemptsLimit": "Ліміт спроб",
  "workflow.riskLevel": "Рівень ризику",
  "subscription.title": "Підписка",
  "subscription.subtitle": "Оберіть зручний період оплати",
  "subscription.monthly": "Щомісячно",
  "subscription.3months": "3 місяці",
  "subscription.yearly": "Річний",
  "subscription.billedMonthly": "Щомісячна оплата",
  "subscription.billedEvery3Months": "Оплата кожні 3 місяці",
  "subscription.billedAnnually": "Щорічна оплата",
  "subscription.saveVsMonthly": "Економія {percent}% від щомісячної",
  "subscription.perMonth": "міс",
  "subscription.currentPlan": "Поточний план",
  "subscription.status": "Статус",
  "subscription.active": "Активний",
  "subscription.freeTrial": "Пробний період",
  "subscription.freeMode": "Ви у безкоштовному режимі",
  "subscription.freeModeSub": "Обмежені можливості. Розблокуйте повну автоматизацію.",
  "subscription.unlockFull": "Розблокувати автоматизацію",
  "subscription.trialEnds": "Пробний період закінчується через",
  "subscription.days": "днів",
  "subscription.upgradePlan": "Покращити план",
  "subscription.currentPlanBadge": "Поточний план",
  "subscription.mostPopular": "Найпопулярніший",
  "subscription.allPlansUnlimited": "Усі плани включають безлімітні акаунти",
  "subscription.feat.unlimitedAccounts": "Безлімітні акаунти",
  "subscription.feat.highSpeed": "Високошвидкісний рівень виконання",
  "subscription.feat.priorityQueue": "Пріоритетна черга",
  "subscription.feat.advancedErrors": "Розширена обробка помилок",
  "subscription.feat.workflowAnalytics": "Аналітика сценаріїв",
  "subscription.feat.aiAssistant": "ШІ-асистент сценаріїв",
  "subscription.feat.premiumSupport": "Преміум-підтримка",
  "subscription.why.fasterExec": "Швидке виконання",
  "subscription.why.fasterExecDesc": "Пріоритетна черга забезпечує блискавичну автоматизацію",
  "subscription.why.smarterRecovery": "Розумне відновлення",
  "subscription.why.smarterRecoveryDesc": "ШІ-обробка помилок автоматично відновлює після збоїв",
  "subscription.why.aiAssist": "ШІ-допомога",
  "subscription.why.aiAssistDesc": "Інтелектуальні пропозиції та оптимізація сценаріїв",
  "subscription.why.priorityInfra": "Пріоритетна інфраструктура",
  "subscription.why.priorityInfraDesc": "Виділені ресурси для максимальної надійності",
  "subscription.why.premiumReliability": "Преміум-надійність",
  "subscription.why.premiumReliabilityDesc": "Корпоративна стабільність для критичної автоматизації",
  "subscription.whyUpgrade": "Навіщо покращувати?",
  "subscription.cryptoPayments": "Криптооплата підтримується",
  "subscription.paymentMethods": "Методи оплати",
  "referrals.title": "Реферали",
  "referrals.subtitle": "Запрошуй друзів. Отримуй кредити.",
  "referrals.creditsTitle": "Що таке кредити?",
  "referrals.creditsDesc": "Кредити — це бонусний баланс за запрошених друзів.",
  "referrals.creditsUseIntro": "Кредити можна використовувати для:",
  "referrals.creditUse1": "Оплати підписок",
  "referrals.creditUse2": "Підвищення тарифу",
  "referrals.creditUse3": "Розблокування преміум-функцій",
  "referrals.creditsAutoApply": "Кредити автоматично застосовуються при оплаті.",
  "referrals.heroText": "Отримуйте нагороду за кожну підписку ваших рефералів.",
  "referrals.earnPercent": "Ви отримуєте 20% від кожного платежу в кредитах платформи",
  "referrals.yourLink": "Ваше реферальне посилання",
  "referrals.shareLink": "Поділіться для отримання нагород",
  "referrals.copied": "Скопійовано",
  "referrals.copy": "Копіювати",
  "referrals.shareTelegram": "Telegram",
  "referrals.shareX": "X",
  "referrals.shareDiscord": "Discord",
  "referrals.activeReferrals": "Активні реферали",
  "referrals.totalEarned": "Всього зароблено кредитів",
  "referrals.currentLevel": "Поточний рівень",
  "referrals.lifetimeCommission": "Довічна комісія %",
  "referrals.yourLevel": "Ваш реферальний рівень",
  "referrals.level1": "Стартовий",
  "referrals.level1Req": "1-4 активних реферали",
  "referrals.level1Perk": "20% кредитів з платежів",
  "referrals.level2": "Зростання",
  "referrals.level2Req": "5-9 активних рефералів",
  "referrals.level2Perk1": "30% кредитів з платежів",
  "referrals.level2Perk2": "20% знижка на підписку",
  "referrals.level3": "Партнер",
  "referrals.level3Req": "10+ активних рефералів",
  "referrals.level3Perk1": "10% довічна комісія",
  "referrals.level3Perk2": "Статус партнера",
  "referrals.level4": "Амбасадор",
  "referrals.level4Req": "50+ активних рефералів",
  "referrals.level4Perk1": "Значок амбасадора",
  "referrals.level4Perk2": "Ексклюзивні нагороди",
  "referrals.unlocked": "Відкрито",
  "referrals.locked": "Закрито",
  "referrals.current": "Поточний",
  "referrals.activity": "Реферальна активність",
  "referrals.colUserId": "ID користувача",
  "referrals.colPlan": "Придбаний план",
  "referrals.colAmount": "Сума платежу",
  "referrals.colReward": "Ваша нагорода",
  "referrals.colStatus": "Статус",
  "referrals.statusPending": "Очікування",
  "referrals.statusActive": "Активний",
  "referrals.statusExpired": "Закінчився",
  "referrals.creditsWallet": "Гаманец кредитів",
  "referrals.availableCredits": "Доступні кредити",
  "referrals.lifetimeEarned": "Зароблено за весь час",
  "referrals.creditsUsed": "Використано кредитів",
  "referrals.applyCredits": "Застосувати кредити до підписки",
  "referrals.creditsTooltip": "Кредити автоматично зменшують ваш наступний платіж",
  "referrals.achievements": "Досягнення",
  "referrals.achFirstRef": "Перший реферал",
  "referrals.achFiveRef": "5 рефералів",
  "referrals.achTopPartner": "Топ-партнер",
  "referrals.emptyTitle": "Почніть запрошувати друзів для розблокування нагород",
  "referrals.emptyCta": "Скопіювати реферальне посилання",
  "settings.title": "Налаштування",
  "settings.subtitle": "Управління налаштуваннями",
  "settings.profile": "Профіль",
  "settings.displayName": "Імʼя",
  "settings.email": "Ел. пошта",
  "settings.saveChanges": "Зберегти",
  "settings.notifications": "Сповіщення",
  "settings.emailNotifications": "Ел. сповіщення",
  "settings.emailNotificationsDesc": "Отримувати оновлення про сценарії",
  "settings.workflowAlerts": "Оповіщення",
  "settings.workflowAlertsDesc": "Сповіщення про сценарії",
  "settings.marketingEmails": "Маркетингові листи",
  "settings.marketingEmailsDesc": "Оновлення та анонси",
  "settings.security": "Безпека",
  "settings.changePassword": "Змінити пароль",
  "settings.lastPasswordChange": "Остання зміна паролю: ніколи",
  "settings.language": "Мова",
  "settings.languageDesc": "Виберіть бажану мову",
  "groups.title": "Групи акаунтів",
  "groups.subtitle": "Організуйте акаунти в логічні групи",
  "groups.createGroup": "Створити групу",
  "groups.newGroup": "Нова група",
  "groups.groupName": "Назва групи",
  "groups.enterGroupName": "Введіть назву",
  "groups.create": "Створити",
  "groups.cancel": "Скасувати",
  "groups.rename": "Перейменувати",
  "groups.delete": "Видалити",
  "groups.deleteConfirm": "Видалити групу? Акаунти будуть звільнені.",
  "groups.noGroups": "Немає груп. Створіть для організації акаунтів.",
  "groups.accountCount": "{count} акаунтів",
  "groups.lastActivity": "Остання активність",
  "groups.activeWorkflows": "Активні сценарії",
  "groups.successRate": "Успішність",
  "groups.manageAccounts": "Управління акаунтами",
  "groups.availableAccounts": "Доступні акаунти",
  "groups.groupAccounts": "Акаунти групи",
  "groups.dragToAssign": "Перетягніть для призначення",
  "groups.noAvailable": "Всі акаунти призначені.",
  "groups.noAccountsInGroup": "Немає акаунтів в групі.",
  "groups.addToGroup": "Додати",
  "groups.removeFromGroup": "Видалити",
  "groups.overview": "Огляд",
  "groups.backToGroups": "Назад до груп",
  "groups.totalInGroup": "Всього в групі",
  "groups.successfulRuns": "Успішні запуски",
  "groups.failedRuns": "Невдалі запуски",
  "groups.recentExecutions": "Останні виконання",
  "groups.noExecutions": "Немає виконань для групи.",
  "groups.status": "Статус",
  "groups.workflow": "Сценарій",
  "groups.time": "Час",
  "groups.moveToGroup": "Перемістити в групу",
  "groups.notFound": "Групу не знайдено.",
  "nodeType.wallet": "Дія гаманця",
  "nodeType.delay": "Затримка",
  "nodeType.split": "Розділити групу",
  "nodeType.condition": "Умова",
  "nodeType.swap": "Обмін",
  "nodeType.loop": "Цикл",
  "nodeType.bridge": "Міст",
  "nodeType.notify": "Сповіщення",
  "nodeType.repeat": "Повторюваний цикл",
  "nodeType.airdrop": "Клейм ейрдропу",
  "nodeType.script": "Користувацький скрипт",
  "status.success": "Успіх",
  "status.partial": "Частково",
  "status.failed": "Помилка",
  "status.pending": "Очікування",
  "status.running": "Виконується",
  "common.save": "Зберегти",
  "common.cancel": "Скасувати",
  "common.delete": "Видалити",
  "common.edit": "Редагувати",
  "common.close": "Закрити",
  "common.confirm": "Підтвердити",
  "common.search": "Пошук",
  "common.noResults": "Результатів не знайдено.",
  "guide.title": "Посібник з налаштувань",
  "guide.section.overview": "Основні налаштування",
  "guide.section.advanced": "Розширені налаштування",
  "guide.section.timing": "Таймінг та затримки",
  "guide.section.risk": "Індикатори ризику",
  "guide.section.simulation": "Режим симуляції",
  "guide.overview.accountGroup": "Група акаунтів",
  "guide.overview.accountGroupDesc": "Оберіть групу акаунтів для виконання цієї дії. Групами можна керувати на сторінці Групи акаунтів.",
  "guide.overview.urlTarget": "URL / Ціль",
  "guide.overview.urlTargetDesc": "Цільова URL-адреса або адреса контракту для взаємодії.",
  "guide.overview.delay": "Затримка",
  "guide.overview.delayDesc": "Час очікування перед виконанням дії. Допомагає уникнути виявлення та лімітів.",
  "guide.overview.onSuccess": "При успіху",
  "guide.overview.onSuccessDesc": "Що відбувається після успішного виконання — перейти далі, повторити або зупинити.",
  "guide.advanced.concurrency": "Паралельність",
  "guide.advanced.concurrencyDesc": "Скільки акаунтів виконують дію одночасно. Більше — швидше, але ризикованіше.",
  "guide.advanced.interval": "Інтервал",
  "guide.advanced.intervalDesc": "Час між кожною партією акаунтів. Контролює швидкість виконання.",
  "guide.advanced.jitter": "Джиттер",
  "guide.advanced.jitterDesc": "Додає випадкові варіації часу, роблячи дії більш природними.",
  "guide.advanced.retryLogic": "Логіка повторів",
  "guide.advanced.retryLogicDesc": "Як повторюються невдалі дії — кількість спроб, затримка та стратегія відступу.",
  "guide.advanced.conditions": "Умови",
  "guide.advanced.conditionsDesc": "Перевірки перед виконанням: мінімальний баланс, ліміти газу та інші вимоги.",
  "guide.advanced.errorHandling": "Обробка помилок",
  "guide.advanced.errorHandlingDesc": "Що відбувається при помилці — пропустити акаунт, повторити або зупинити весь процес.",
  "guide.timing.delays": "Типи затримок",
  "guide.timing.delaysDesc": "Фіксовані затримки чекають заданий час. Випадкові додають варіацію для природнішої поведінки.",
  "guide.timing.batching": "Пакетна обробка",
  "guide.timing.batchingDesc": "Акаунти обробляються пакетами. Розмір пакета дорівнює паралельності, з інтервалами між ними.",
  "guide.timing.retries": "Час повторів",
  "guide.timing.retriesDesc": "Невдалі акаунти чекають перед повтором. Експоненціальний відкат подвоює час з кожною спробою.",
  "guide.risk.safe": "Безпечно",
  "guide.risk.safeDesc": "Дії з низьким ризиком: читання даних або перевірка балансів. Без ризику для коштів.",
  "guide.risk.medium": "Середній",
  "guide.risk.mediumDesc": "Дії з середнім ризиком: апруви токенів або свопи на перевірених протоколах.",
  "guide.risk.risky": "Ризиковано",
  "guide.risk.riskyDesc": "Дії з високим ризиком: неперевірені контракти або великі операції. Використовуйте обережно.",
  "guide.simulation.preview": "Режим попереднього перегляду",
  "guide.simulation.previewDesc": "Симулюйте весь робочий процес без реальних транзакцій. Побачите розрахунковий час та потік акаунтів.",
  "guide.simulation.howTo": "Як запустити симуляцію",
  "guide.simulation.howToDesc": "Натисніть кнопку відтворення на картці або використовуйте кнопку симуляції на панелі інструментів.",
  "settings.nav.account": "Акаунт",
  "settings.nav.interface": "Інтерфейс",
  "settings.nav.execution": "Виконання",
  "settings.nav.security": "Безпека",
  "settings.nav.notifications": "Сповіщення",
  "settings.nav.data": "Дані",
  "settings.nav.advanced": "Розширені",
  "settings.emailDesc": "Ваша зареєстрована електронна адреса",
  "settings.changePasswordDesc": "Встановити новий пароль для акаунту",
  "settings.twoFactor": "Двофакторна автентифікація",
  "settings.twoFactorDesc": "Додати додатковий рівень захисту акаунту",
  "settings.activeSessions": "Активні сесії",
  "settings.activeSessionsDesc": "Пристрої, на яких виконано вхід в акаунт",
  "settings.active": "активно",
  "settings.logoutAll": "Вийти скрізь",
  "settings.logoutAllDesc": "Вийти з акаунту на всіх пристроях та сесіях",
  "settings.logoutAllBtn": "Завершити всі сесії",
  "settings.timezone": "Часовий пояс",
  "settings.timezoneDesc": "Встановіть бажаний часовий пояс для планування",
  "settings.timeFormat": "Формат часу",
  "settings.timeFormatDesc": "Оберіть 12-годинний або 24-годинний формат відображення",
  "settings.compactUI": "Компактний інтерфейс",
  "settings.compactUIDesc": "Зменшити відступи для щільнішого інтерфейсу",
  "settings.executionNote": "Ці налаштування впливають на виконання сценаріїв по всіх акаунтах.",
  "settings.speedProfile": "Профіль швидкості",
  "settings.speedProfileDesc": "Контролює затримку між діями",
  "settings.speedSafe": "Безпечний",
  "settings.speedSafeDesc": "Максимальні затримки між діями",
  "settings.speedBalanced": "Збалансований",
  "settings.speedBalancedDesc": "Помірні затримки між діями",
  "settings.speedAggressive": "Агресивний",
  "settings.speedAggressiveDesc": "Мінімальні затримки між діями",
  "settings.retryStrategy": "Стратегія повторів",
  "settings.retryStrategyDesc": "Як повторюються невдалі дії",
  "settings.retryCons": "Консервативний",
  "settings.retrySmart": "Розумний",
  "settings.retryMax": "Максимальний",
  "settings.randomization": "Рівень рандомізації",
  "settings.randomizationDesc": "Додає випадкові відхилення в часі та діях",
  "settings.randomLow": "Низький",
  "settings.randomMedium": "Середній",
  "settings.randomHigh": "Високий",
  "settings.failureTolerance": "Допустимість помилок",
  "settings.failureToleranceDesc": "Як система обробляє помилки окремих акаунтів",
  "settings.failStrict": "Суворий",
  "settings.failFlexible": "Гнучкий",
  "settings.privacyMode": "Режим конфіденційності",
  "settings.privacyModeDesc": "Приховувати адреси гаманців та конфіденційні дані в інтерфейсі",
  "settings.localExecution": "Тільки локальне виконання",
  "settings.localExecutionDesc": "Обробляти всі сценарії локально без хмарної синхронізації",
  "settings.dataRetention": "Період зберігання даних",
  "settings.dataRetentionDesc": "Скільки зберігаються журнали виконання",
  "settings.days": "днів",
  "settings.autoLogDeletion": "Автовидалення журналів",
  "settings.autoLogDeletionDesc": "Автоматично видаляти старі журнали після закінчення терміну зберігання",
  "settings.notifErrors": "Сповіщення про помилки",
  "settings.notifErrorsDesc": "Отримувати сповіщення при виникненні помилок у сценаріях",
  "settings.notifCompletion": "Сповіщення про завершення",
  "settings.notifCompletionDesc": "Отримувати сповіщення при успішному завершенні сценаріїв",
  "settings.notifBilling": "Сповіщення про оплату",
  "settings.notifBillingDesc": "Отримувати сповіщення про платежі та зміни підписки",
  "settings.notifReferrals": "Сповіщення про рефералів",
  "settings.notifReferralsDesc": "Отримувати сповіщення, коли хтось використовує ваше реферальне посилання",
  "settings.notifUpdates": "Оновлення продукту",
  "settings.notifUpdatesDesc": "Отримувати сповіщення про нові функції та оновлення платформи",
  "settings.channels": "Канали сповіщень",
  "settings.channelEmail": "Ел. пошта",
  "settings.channelInApp": "У додатку",
  "settings.exportWorkflows": "Експорт сценаріїв",
  "settings.importWorkflows": "Імпорт сценаріїв",
  "settings.backupSettings": "Резервне копіювання налаштувань",
  "settings.resetEnvironment": "Скидання оточення",
  "settings.confirmTitle": "Підтвердити скидання",
  "settings.confirmResetDesc": "Це скине всі налаштування до значень за замовчуванням. Цю дію не можна скасувати.",
  "settings.confirmReset": "Скинути все",
  "settings.enableAdvanced": "Увімкнути розширений режим",
  "settings.enableAdvancedDesc": "Відкрити доступ до журналів налагодження, експериментальних функцій та діагностики",
  "settings.debugLogs": "Журнали налагодження",
  "settings.debugLogsDesc": "Показувати детальні журнали налагодження в консолі",
  "settings.experimentalFeatures": "Експериментальні функції",
  "settings.experimentalFeaturesDesc": "Увімкнути експериментальні функції, які можуть бути нестабільними",
  "settings.extendedDiagnostics": "Розширена діагностика",
  "settings.extendedDiagnosticsDesc": "Запускати розширену діагностику виконання сценаріїв",
  "paywall.title": "Розблокувати виконання",
  "paywall.description": "Оновіть план, щоб запускати реальні автоматизації та масштабувати робочі процеси.",
  "paywall.trialExhausted": "Ви використали всі 3 пробних запуски. Оновіть план для продовження.",
  "paywall.trialUsed": "Усі 3 пробних запуски використані",
  "paywall.upgradePlan": "Оновити план",
  "paywall.continueFree": "Продовжити безкоштовно",
  "paywall.bannerText": "Ви на безкоштовному плані — оновіть для запуску автоматизацій",
  "paywall.upgrade": "Оновити",
  "paywall.trialRunsLeft": "пробних запусків залишилось",
  "paywall.feat.multiAccount": "Мульти-акаунт виконання",
  "paywall.feat.smartRouting": "Розумна маршрутизація",
  "paywall.feat.advancedScheduling": "Розширене планування",
  "paywall.feat.priorityExecution": "Пріоритетне виконання",
  "paywall.lockedFeature": "Ця функція потребує платного плану",
  "paywall.runLocked": "Виконання заблоковано на безкоштовному плані",
  "guest.badge": "Гість",
  "guest.badgeDesc": "Не авторизовано",
  "guest.bannerText": "Ви в гостьовому режимі — створіть акаунт, щоб зберегти роботу",
  "guest.createAccount": "Створити акаунт",
  "guest.signupTitle": "Створити безкоштовний акаунт",
  "guest.signupDefault": "Зберігайте воркфлоу та отримуйте до них доступ будь-коли",
  "guest.signupToSave": "Створіть акаунт, щоб зберігати воркфлоу назавжди",
  "guest.signupToExport": "Створіть акаунт для експорту воркфлоу",
  "guest.signupToExecute": "Створіть акаунт для запуску автоматизації",
  "guest.signUpEmail": "Зареєструватися через Email",
  "guest.continueGuest": "Продовжити як гість",
  "guest.benefit.saveWorkflows": "Збереження воркфлоу назавжди",
  "guest.benefit.cloudBackup": "Хмарне резервне копіювання",
  "guest.benefit.freeTrialRuns": "3 безкоштовних пробних запуски",
  "guest.exitDashboard": "Вийти",
  "checkout.title": "Оплата криптовалютою",
  "checkout.subtitle": "Надішліть платіж для миттєвої активації підписки.",
  "checkout.backToPlans": "Назад до тарифів",
  "checkout.awaitingPayment": "Очікування оплати",
  "checkout.invoiceExpires": "Рахунок закінчується через",
  "checkout.invoiceExpired": "Рахунок прострочено — створіть новий",
  "checkout.regenerate": "Створити новий рахунок",
  "checkout.sendPaymentTo": "Надішліть платіж на цю адресу",
  "checkout.copied": "Скопійовано!",
  "checkout.evmNetwork": "EVM-сумісна мережа",
  "checkout.networkWarning": "Надсилайте лише підтримувані EVM-активи. Невірна мережа = втрата коштів.",
  "checkout.confirmTransaction": "Підтвердити транзакцію",
  "checkout.enterTxHash": "Введіть хеш транзакції",
  "checkout.confirmPayment": "Підтвердити оплату",
  "checkout.checkingBlockchain": "Перевірка блокчейну…",
  "checkout.paymentDetected": "Платіж виявлено",
  "checkout.subscriptionActivated": "Вашу підписку активовано",
  "checkout.goToDashboard": "Перейти до панелі",
  "checkout.txNotFound": "Транзакцію не знайдено. Перевірте хеш і спробуйте знову.",
  "checkout.morePaymentMethods": "Інші способи оплати",
  "checkout.comingSoon": "Незабаром",
  "checkout.securityFooter": "Платежі перевіряються в блокчейні. Cetra не зберігає ваші приватні ключі.",
  "checkout.duration.1month": "1 місяць",
  "checkout.duration.3months": "3 місяці",
  "checkout.duration.12months": "12 місяців",

  "tmpl.chooseCategory": "Оберіть категорію",
  "tmpl.categorySubtitle": "Виберіть категорію для перегляду готових шаблонів проєктів.",
  "tmpl.projects": "проєкти",
  "tmpl.templates": "шаблони",
  "tmpl.comingSoon": "Незабаром",
  "tmpl.useTemplate": "Використати шаблон",
  "tmpl.blankWorkflow": "Порожній сценарій",
  "tmpl.blankDesc": "Почніть з чистого полотна та створіть з нуля.",
  "tmpl.saveAsTemplate": "Зберегти як шаблон",
  "tmpl.custom": "Мої шаблони",
  "tmpl.customDesc": "Ваші збережені користувацькі шаблони сценаріїв.",
  "tmpl.customSaved": "Користувацький збережений шаблон сценарію.",

  "tmpl.cat.social": "Соціальна активність",
  "tmpl.cat.socialDesc": "Автоматизація соціальної взаємодії, виконання квестів та фармінгу спільнот на різних платформах.",
  "tmpl.cat.testnet": "Testnet",
  "tmpl.cat.testnetDesc": "Автоматизація взаємодій з тестнетами, включаючи свопи, бріджі, мінти та клейми з фаусетів.",
  "tmpl.cat.airdrop": "Airdrop",
  "tmpl.cat.airdropDesc": "Відстеження та автоматичний клейм ейрдропів у кількох мережах.",
  "tmpl.cat.farming": "Фармінг",
  "tmpl.cat.farmingDesc": "Стратегії автоматизації фармінгу прибутковості та надання ліквідності.",

  "tmpl.type.pointsFarming": "Фармінг очок",
  "tmpl.type.questCompletion": "Виконання квестів",
  "tmpl.type.credentialFarming": "Фармінг облікових даних",
  "tmpl.type.socialEngagement": "Соціальна взаємодія",
  "tmpl.type.roleFarming": "Фармінг ролей",
  "tmpl.type.testnetActivity": "Активність у тестнеті",
  "tmpl.type.crossChain": "Cross-Chain",
  "tmpl.type.l2Activity": "Активність L2",
  "tmpl.type.ecosystemTasks": "Завдання екосистеми",
  "tmpl.type.custom": "Користувацький",

  "tmpl.konnex.desc": "Заробляйте очки Konnex, виконуючи соціальні завдання: лайки, коментарі, репости, підписки, приєднання до Discord, щоденна відмітка та реферали.",
  "tmpl.zealy.desc": "Автоматизація виконання квестів Zealy та фармінгу XP з щоденним моніторингом квестів.",
  "tmpl.galxe.desc": "Клейм облікових даних Galxe та OAT шляхом привʼязки профілів та виконання завдань у мережі.",
  "tmpl.twitter.desc": "Автоматизація взаємодії в Twitter: лайки, ретвіти та підписки з людиноподібними затримками.",
  "tmpl.discord.desc": "Фармінг ролей Discord через автоматичне приєднання до серверів, верифікацію гаманців та активність.",
  "tmpl.pharos.desc": "Виконання активностей у тестнеті Pharos: клейми з фаусету, свопи токенів, бріджинг, мінт NFT та щоденні транзакції.",
  "tmpl.layerzero.desc": "Автоматизація крос-чейн бридж-транзакцій LayerZero у кількох тестнетах.",
  "tmpl.starknet.desc": "Генерація ончейн-активності Starknet: свопи на DEX, надання ліквідності та мінт NFT.",
  "tmpl.scroll.desc": "Взаємодія з тестнетом Scroll: бридж, свопи токенів та генерація щоденного обсягу транзакцій.",
  "tmpl.base.desc": "Виконання завдань екосистеми Base: бридж, торгівля на Aerodrome та мінт NFT на Base.",
  "theme.light": "Світла тема",
  "theme.dark": "Темна тема",
  "theme.default": "за замовч.",

  "tour.step1.title": "Навігація",
  "tour.step1.desc": "Це ваша головна навігація. Звідси ви можете перейти до всіх розділів — воркфлоу, групи, підписка та інше.",
  "tour.step2.title": "Конструктор воркфлоу",
  "tour.step2.desc": "Створюйте автоматизації за допомогою візуального конструктора. Обирайте з шаблонів або створюйте з нуля.",
  "tour.step3.title": "Підписка",
  "tour.step3.desc": "Керуйте своїм планом, відстежуйте використання та покращуйте тариф для доступу до більшої кількості акаунтів.",
  "tour.step4.title": "Реферали",
  "tour.step4.desc": "Запрошуйте друзів та отримуйте кредити. За кожного реферала ви отримуєте бонусні кредити.",
  "tour.step5.title": "Налаштування",
  "tour.step5.desc": "Налаштуйте інтерфейс — мова, тема, параметри виконання, безпека та багато іншого.",
  "tour.next": "Далі",
  "tour.back": "Назад",
  "tour.skip": "Пропустити",
  "tour.finish": "Готово",
  "settings.replayTour": "Навчальний тур",
  "settings.replayTourDesc": "Повторити покрокове керівництво по дашборду",
  "settings.replayTourBtn": "Повторити",

  "btour.replay": "Гайд",
  "btour.step1.title": "Робочий полотно",
  "btour.step1.desc": "Це ваше робоче полотно. Перетягуйте сюди картки дій для створення автоматизації. Можна вільно переміщувати, масштабувати та прокручувати.",
  "btour.step2.title": "Бібліотека карток",
  "btour.step2.desc": "Ця панель містить усі доступні картки дій. Перетягніть будь-яку на полотно, щоб додати новий крок автоматизації.",
  "btour.step3.title": "Картка дії",
  "btour.step3.desc": "Кожна картка — це крок автоматизації. Налаштуйте її, переміщуйте та з'єднуйте з іншими картками через порти з боків.",
  "btour.step4.title": "З'єднання",
  "btour.step4.desc": "З'єднання визначають порядок виконання. Перетягніть від виходу до входу, щоб створити потік. Воркфлоу виконується зверху вниз.",
  "btour.step5.title": "Панель налаштувань",
  "btour.step5.desc": "Усі налаштування картки відображаються тут при її виборі. Базові налаштування видні за замовчуванням, згруповані за категоріями.",
  "btour.step6.title": "Розширений режим",
  "btour.step6.desc": "Увімкніть розширений режим для доступу до додаткових параметрів: логіка виконання, таргетинг акаунтів та обробка помилок. Рекомендується для досвідчених користувачів.",
  "btour.step7.title": "Шаблон воркфлоу",
  "btour.step7.desc": "Тут відображається назва воркфлоу. Якщо створено з шаблону, можна вільно змінювати будь-який блок та зберегти як власний шаблон.",
  "btour.step8.title": "Зберегти та запустити",
  "btour.step8.desc": "Збережіть воркфлоу, щоб зберегти прогрес. Натисніть «Запустити» для початку автоматизації на ваших акаунтах.",

  "ctour.help": "Гайд з налаштувань картки",
  "ctour.step1.title": "Тип дії",
  "ctour.step1.desc": "Це тип дії, яку виконує картка. Він визначає, що робить крок автоматизації. Іконка та колір вказують на категорію.",
  "ctour.step2.title": "Базові налаштування",
  "ctour.step2.desc": "Це обов'язкові основні параметри. Без них картка не зможе виконатися. Для простих воркфлоу тримайте налаштування мінімальними.",
  "ctour.step3.title": "Поля введення",
  "ctour.step3.desc": "Це обов'язковий параметр. Має бути коректним для виконання. Деякі поля підтримують змінні або динамічні значення.",
  "ctour.step4.title": "Налаштування затримки",
  "ctour.step4.desc": "Затримка контролює, коли дія виконується. Допомагає імітувати природну поведінку та корисна для управління таймінгом.",
  "ctour.step5.title": "Логіка повторів",
  "ctour.step5.desc": "Повтор визначає, скільки разів система повторює спробу при збої. Це запобігає перериванню воркфлоу. Більше повторів — довше виконання.",
  "ctour.step6.title": "Розширений режим",
  "ctour.step6.desc": "Вмикає розширену конфігурацію та приховані технічні параметри. Рекомендується лише для досвідчених користувачів.",
  "ctour.step7.title": "Поведінка виконання",
  "ctour.step7.desc": "Визначає, чи виконується дія послідовно, паралельно або умовно. Впливає на логіку та продуктивність воркфлоу.",
  "ctour.step8.title": "Зберегти зміни",
  "ctour.step8.desc": "Зміни застосовуються автоматично при налаштуванні. Завжди перевіряйте налаштування перед запуском воркфлоу.",
  "onboarding.welcome": "Ласкаво просимо до Cetra!",
  "onboarding.clickBuilder": "Почнемо! Натисніть на виділений пункт «Конструктор сценаріїв» у бічній панелі, щоб створити вашу першу автоматизацію.",
  "onboarding.builderPhase": "Чудово! Тепер дослідіть полотно конструктора. Слідуйте гіду, щоб дізнатися основи.",
  "onboarding.cardPhase": "Майже готово! Натисніть на будь-яку картку, щоб побачити панель налаштувань і завершити тур.",
  "onboarding.complete": "Готово! Тепер ви знаєте, як створювати та налаштовувати сценарії."
}
